return {
  storyName = "Home",
  storyDescription = "",
  lineData = {
    {
      startStory = "17816860338881",
      startPort = "StoryStart",
      endStory = "1781686084679521",
      endPort = "In"
    },
    {
      startStory = "1781686084679521",
      startPort = "Success",
      endStory = "17816860338895",
      endPort = "StoryEnd"
    }
  },
  storyNodeData = {
    ["17816860338881"] = {
      isStoryNode = true,
      key = "17816860338881",
      type = "StoryStartNode",
      name = "StoryStart",
      pos = {x = 1382, y = 324},
      propsData = {QuestChainId = 0},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["17816860338895"] = {
      isStoryNode = true,
      key = "17816860338895",
      type = "StoryEndNode",
      name = "StoryEnd",
      pos = {x = 2616, y = 326},
      propsData = {},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["1781686084679521"] = {
      isStoryNode = true,
      key = "1781686084679521",
      type = "StoryNode",
      name = "噩梦游乐园",
      pos = {x = 1958, y = 306},
      propsData = {
        QuestId = 0,
        QuestDescriptionComment = "",
        QuestDescription = "",
        QuestDeatil = "",
        TaskRegionReName = "",
        TaskSubRegionReName = "",
        RecommendLevel = -1,
        bIsStartQuest = false,
        bIsEndQuest = false,
        bIsNotifyGameMode = true,
        bIsStartChapter = false,
        bIsEndChapter = false,
        bIsPlayBlackScreenOnComplete = false,
        bIsPlayBlackScreenOnFail = false,
        bIsDynamicEvent = false,
        ResurgencePoint = "",
        bUseQuestCoordinate = false,
        bDeadTriggerQuestFail = false,
        IsFairyLand = false,
        SubRegionId = 0,
        SubRegionIdList = {},
        StoryGuideType = "Point",
        StoryGuidePointName = "",
        JumpId = 0,
        IsBacktrack = false
      },
      questNodeData = {
        lineData = {
          {
            startQuest = "1781686084680533",
            startPort = "Out",
            endQuest = "1781686084680534",
            endPort = "In"
          },
          {
            startQuest = "1781686084680534",
            startPort = "Out",
            endQuest = "1781686084680535",
            endPort = "In"
          },
          {
            startQuest = "1781686084680535",
            startPort = "Out",
            endQuest = "1781686084680536",
            endPort = "In"
          },
          {
            startQuest = "1781686084680526",
            startPort = "QuestStart",
            endQuest = "1781686084680531",
            endPort = "In"
          },
          {
            startQuest = "1781686084680531",
            startPort = "Out",
            endQuest = "1781686084680537",
            endPort = "In"
          },
          {
            startQuest = "1781686084680537",
            startPort = "Out",
            endQuest = "17816992638431058099",
            endPort = "In"
          },
          {
            startQuest = "17816992638431058099",
            startPort = "Out",
            endQuest = "1781686084680527",
            endPort = "Success"
          }
        },
        nodeData = {
          ["1781686084680526"] = {
            key = "1781686084680526",
            type = "QuestStartNode",
            name = "QuestStart",
            pos = {x = 731, y = 321},
            propsData = {ModeType = 0}
          },
          ["1781686084680527"] = {
            key = "1781686084680527",
            type = "QuestSuccessNode",
            name = "QuestSuccess",
            pos = {x = 2178.5511969723643, y = 348.0164759725401},
            propsData = {ModeType = 0}
          },
          ["1781686084680528"] = {
            key = "1781686084680528",
            type = "QuestFailNode",
            name = "QuestFail",
            pos = {x = 2910.217391304348, y = 1191.086956521739},
            propsData = {}
          },
          ["1781686084680529"] = {
            key = "1781686084680529",
            type = "TalkNode",
            name = "【特殊演出】到达梦境游乐园",
            pos = {x = 1311.165789473684, y = -173.3605263157895},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              AllowSurroundDialogue = false,
              FirstDialogueId = 10010101,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {},
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1781686084680530"] = {
            key = "1781686084680530",
            type = "ChangeStaticCreatorNode",
            name = "生成伊薇",
            pos = {x = 970.0184210526318, y = 106.42196796338663},
            propsData = {
              ActiveEnable = true,
              EnableBlackScreenSync = false,
              EnableFadeIn = false,
              EnableFadeOut = false,
              NewTargetPointName = "",
              StaticCreatorIdList = {}
            }
          },
          ["1781686084680531"] = {
            key = "1781686084680531",
            type = "TalkNode",
            name = "【Ex02_FixSimple_17】",
            pos = {x = 1125.4298245614038, y = 340.0903890160182},
            propsData = {
              IsNpcNode = false,
              bUseFlowAssetActors = true,
              FirstDialogueId = 0,
              FlowAssetPath = "DialogueAsset'/Game/Dialogue/MainStory/1102/110201/11020117.11020117'",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = true,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1781686084680532"] = {
            key = "1781686084680532",
            type = "GoToNode",
            name = "前往",
            pos = {x = 1215.6184210526317, y = 155.17196796338663},
            propsData = {
              GuideUIEnable = true,
              StaticCreatorId = 0,
              GuideType = "M",
              GuidePointName = ""
            }
          },
          ["1781686084680533"] = {
            key = "1781686084680533",
            type = "TalkNode",
            name = "【机关】打靶",
            pos = {x = 768.0091533180778, y = 843.4782608695652},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              AllowSurroundDialogue = false,
              FirstDialogueId = 10010101,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {},
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1781686084680534"] = {
            key = "1781686084680534",
            type = "AsyncSetActorLocationAndRotationNode",
            name = "异步设置玩家位置旋转",
            pos = {x = 1108.4287185354697, y = 862.8143020594964},
            propsData = {
              UnitId = 0,
              NewTargetPointName = "",
              FadeIn = false,
              FadeOut = false,
              bResetCamera = true,
              bForceAsyncLoading = false,
              IsWhite = false
            }
          },
          ["1781686084680535"] = {
            key = "1781686084680535",
            type = "ChangeStaticCreatorNode",
            name = "生成伊薇",
            pos = {x = 1400.745308924485, y = 878.6558352402745},
            propsData = {
              ActiveEnable = true,
              EnableBlackScreenSync = false,
              EnableFadeIn = false,
              EnableFadeOut = false,
              NewTargetPointName = "",
              StaticCreatorIdList = {}
            }
          },
          ["1781686084680536"] = {
            key = "1781686084680536",
            type = "GoToNode",
            name = "前往",
            pos = {x = 1744.7188248754887, y = 873.0186599811549},
            propsData = {
              GuideUIEnable = true,
              StaticCreatorId = 0,
              GuideType = "N",
              GuidePointName = ""
            }
          },
          ["1781686084680537"] = {
            key = "1781686084680537",
            type = "TalkNode",
            name = "【Ex02_FixSimple_19】过山车",
            pos = {x = 1511.9118073316283, y = 340.8256775250148},
            propsData = {
              IsNpcNode = false,
              bUseFlowAssetActors = true,
              FirstDialogueId = 0,
              FlowAssetPath = "DialogueAsset'/Game/Dialogue/MainStory/1102/110201/11020119.11020119'",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = true,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1781686084680538"] = {
            key = "1781686084680538",
            type = "GoToNode",
            name = "前往",
            pos = {x = 2088.9293511912783, y = 852.4923441916812},
            propsData = {
              GuideUIEnable = true,
              StaticCreatorId = 0,
              GuideType = "N",
              GuidePointName = ""
            }
          },
          ["17816992638431058099"] = {
            key = "17816992638431058099",
            type = "TalkNode",
            name = "【Ex02_FixSimple_20】跑出轨道",
            pos = {x = 1827.1089507947972, y = 351.78930729386394},
            propsData = {
              IsNpcNode = false,
              bUseFlowAssetActors = true,
              FirstDialogueId = 0,
              FlowAssetPath = "DialogueAsset'/Game/Dialogue/MainStory/1102/110201/11020120.11020120'",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = true,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          }
        },
        commentData = {}
      }
    }
  },
  commentData = {}
}
