return {
  storyName = "Home",
  storyDescription = "",
  lineData = {
    {
      startStory = "1773818091783488011",
      startPort = "StoryStart",
      endStory = "1773818091783488013",
      endPort = "In"
    },
    {
      startStory = "1773818091783488013",
      startPort = "Success",
      endStory = "1773818091783488012",
      endPort = "StoryEnd"
    }
  },
  storyNodeData = {
    ["1773818091783488011"] = {
      isStoryNode = true,
      key = "1773818091783488011",
      type = "StoryStartNode",
      name = "StoryStart",
      pos = {x = 800, y = 300},
      propsData = {QuestChainId = 0},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["1773818091783488012"] = {
      isStoryNode = true,
      key = "1773818091783488012",
      type = "StoryEndNode",
      name = "StoryEnd",
      pos = {x = 2800, y = 300},
      propsData = {},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["1773818091783488013"] = {
      isStoryNode = true,
      key = "1773818091783488013",
      type = "StoryNode",
      name = "皓京棋子对话",
      pos = {x = 1522, y = 318},
      propsData = {
        QuestId = 0,
        QuestDescriptionComment = "",
        QuestDescription = "",
        QuestDeatil = "",
        TaskRegionReName = "",
        TaskSubRegionReName = "",
        RecommendLevel = -1,
        bIsStartQuest = false,
        bIsEndQuest = false,
        bIsNotifyGameMode = true,
        bIsStartChapter = false,
        bIsEndChapter = false,
        bIsPlayBlackScreenOnComplete = false,
        bIsPlayBlackScreenOnFail = false,
        bIsDynamicEvent = false,
        ResurgencePoint = "",
        bUseQuestCoordinate = false,
        bDeadTriggerQuestFail = false,
        IsFairyLand = false,
        IsBacktrack = false,
        SubRegionId = 0,
        SubRegionIdList = {},
        StoryGuideType = "Point",
        StoryGuidePointName = "",
        JumpId = 0
      },
      questNodeData = {
        lineData = {
          {
            startQuest = "1773818091783488014",
            startPort = "QuestStart",
            endQuest = "1773818091783488017",
            endPort = "In"
          },
          {
            startQuest = "1773818091783488017",
            startPort = "Branch_1",
            endQuest = "17738177810372172",
            endPort = "In"
          },
          {
            startQuest = "17738177810372172",
            startPort = "Out",
            endQuest = "1773818091783488015",
            endPort = "Success"
          },
          {
            startQuest = "1773818091783488017",
            startPort = "Branch_2",
            endQuest = "17738178227722767",
            endPort = "In"
          },
          {
            startQuest = "17738178227722767",
            startPort = "Out",
            endQuest = "1773818091783488015",
            endPort = "Success"
          },
          {
            startQuest = "1773818091783488017",
            startPort = "Branch_3",
            endQuest = "17738179246923370",
            endPort = "In"
          },
          {
            startQuest = "1773818091783488017",
            startPort = "Branch_4",
            endQuest = "17738179246923371",
            endPort = "In"
          },
          {
            startQuest = "1773818091783488017",
            startPort = "Branch_5",
            endQuest = "17738179372423794",
            endPort = "In"
          },
          {
            startQuest = "1773818091783488017",
            startPort = "Branch_6",
            endQuest = "17738179372423795",
            endPort = "In"
          },
          {
            startQuest = "1773818091783488017",
            startPort = "Branch_7",
            endQuest = "17738179410923886",
            endPort = "In"
          },
          {
            startQuest = "1773818091783488017",
            startPort = "Branch_8",
            endQuest = "17738179410933887",
            endPort = "In"
          },
          {
            startQuest = "1773818091783488017",
            startPort = "Branch_9",
            endQuest = "17738179439253954",
            endPort = "In"
          },
          {
            startQuest = "1773818091783488017",
            startPort = "Branch_10",
            endQuest = "17738179439253955",
            endPort = "In"
          },
          {
            startQuest = "1773818091783488017",
            startPort = "Branch_11",
            endQuest = "17738179712895018",
            endPort = "In"
          },
          {
            startQuest = "1773818091783488017",
            startPort = "Branch_12",
            endQuest = "17738179712895019",
            endPort = "In"
          },
          {
            startQuest = "17738179246923370",
            startPort = "Out",
            endQuest = "1773818091783488015",
            endPort = "Success"
          },
          {
            startQuest = "17738179246923371",
            startPort = "Out",
            endQuest = "1773818091783488015",
            endPort = "Success"
          },
          {
            startQuest = "17738179372423794",
            startPort = "Out",
            endQuest = "1773818091783488015",
            endPort = "Success"
          },
          {
            startQuest = "17738179372423795",
            startPort = "Out",
            endQuest = "1773818091783488015",
            endPort = "Success"
          },
          {
            startQuest = "17738179410923886",
            startPort = "Out",
            endQuest = "1773818091783488015",
            endPort = "Success"
          },
          {
            startQuest = "17738179410933887",
            startPort = "Out",
            endQuest = "1773818091783488015",
            endPort = "Success"
          },
          {
            startQuest = "17738179439253954",
            startPort = "Out",
            endQuest = "1773818091783488015",
            endPort = "Success"
          },
          {
            startQuest = "17738179439253955",
            startPort = "Out",
            endQuest = "1773818091783488015",
            endPort = "Success"
          },
          {
            startQuest = "17738179712895018",
            startPort = "Out",
            endQuest = "1773818091783488015",
            endPort = "Success"
          },
          {
            startQuest = "17738179712895019",
            startPort = "Out",
            endQuest = "1773818091783488015",
            endPort = "Success"
          }
        },
        nodeData = {
          ["17738177810372172"] = {
            key = "17738177810372172",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1730.4705882352941, y = -42.11764705882346},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 84000101,
              FlowAssetPath = "",
              TalkType = "Bubble",
              BubblePlayType = "Once",
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              bBubblePlayCDEnable = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              TalkActors = {},
              OverrideFailBlend = false
            }
          },
          ["17738178227722767"] = {
            key = "17738178227722767",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1735.637443438914, y = 109.09558823529426},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 84000103,
              FlowAssetPath = "",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0.5,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17738179246923370"] = {
            key = "17738179246923370",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1736.7559389140274, y = 256.7582013574662},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 84000201,
              FlowAssetPath = "",
              TalkType = "Bubble",
              BubblePlayType = "Once",
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              bBubblePlayCDEnable = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              TalkActors = {},
              OverrideFailBlend = false
            }
          },
          ["17738179246923371"] = {
            key = "17738179246923371",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1741.9227941176473, y = 412.5868212669685},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 84000203,
              FlowAssetPath = "",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0.5,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17738179372423794"] = {
            key = "17738179372423794",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1740.2751696832581, y = 570.056278280543},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 84000301,
              FlowAssetPath = "",
              TalkType = "Bubble",
              BubblePlayType = "Once",
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              bBubblePlayCDEnable = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              TalkActors = {},
              OverrideFailBlend = false
            }
          },
          ["17738179372423795"] = {
            key = "17738179372423795",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1743.942024886878, y = 736.3848981900453},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 84000303,
              FlowAssetPath = "",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0.5,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17738179410923886"] = {
            key = "17738179410923886",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1745.6982466063353, y = 885.1716628959276},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 84000401,
              FlowAssetPath = "",
              TalkType = "Bubble",
              BubblePlayType = "Once",
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              bBubblePlayCDEnable = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              TalkActors = {},
              OverrideFailBlend = false
            }
          },
          ["17738179410933887"] = {
            key = "17738179410933887",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1752.1694496360421, y = 1041.0002828054298},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 84000403,
              FlowAssetPath = "",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0.5,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17738179439253954"] = {
            key = "17738179439253954",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1748.0059389140276, y = 1196.710124434389},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 84000501,
              FlowAssetPath = "",
              TalkType = "Bubble",
              BubblePlayType = "Once",
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              bBubblePlayCDEnable = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              TalkActors = {},
              OverrideFailBlend = false
            }
          },
          ["17738179439253955"] = {
            key = "17738179439253955",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1753.1727941176475, y = 1352.5387443438913},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 84000503,
              FlowAssetPath = "",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0.5,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17738179712895018"] = {
            key = "17738179712895018",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1761.4810520361996, y = 1548.6015271493216},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 84000601,
              FlowAssetPath = "",
              TalkType = "Bubble",
              BubblePlayType = "Once",
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              bBubblePlayCDEnable = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              TalkActors = {},
              OverrideFailBlend = false
            }
          },
          ["17738179712895019"] = {
            key = "17738179712895019",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1766.6479072398195, y = 1704.4301470588239},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 84000603,
              FlowAssetPath = "",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0.5,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1773818091783488014"] = {
            key = "1773818091783488014",
            type = "QuestStartNode",
            name = "QuestStart",
            pos = {x = 489.5959595959596, y = 416.12121212121224},
            propsData = {ModeType = 0}
          },
          ["1773818091783488015"] = {
            key = "1773818091783488015",
            type = "QuestSuccessNode",
            name = "QuestSuccess",
            pos = {x = 3159.888785699426, y = 435.12559313303007},
            propsData = {ModeType = 0}
          },
          ["1773818091783488016"] = {
            key = "1773818091783488016",
            type = "QuestFailNode",
            name = "QuestFail",
            pos = {x = 3138.909090909091, y = 145.63636363636363},
            propsData = {}
          },
          ["1773818091783488017"] = {
            key = "1773818091783488017",
            type = "BranchTriggerNode",
            name = "触发分支节点",
            pos = {x = 1076, y = 318},
            propsData = {
              Branches = {
                84000101,
                84000103,
                84000201,
                84000203,
                84000301,
                84000303,
                84000401,
                84000403,
                84000501,
                84000503,
                84000601,
                84000603
              }
            }
          }
        },
        commentData = {}
      }
    }
  },
  commentData = {}
}
