return {
  storyName = "Home",
  storyDescription = "",
  lineData = {
    {
      startStory = "1748589440592372300",
      startPort = "StoryStart",
      endStory = "1748589440592372302",
      endPort = "In"
    },
    {
      startStory = "1748589440592372302",
      startPort = "Success",
      endStory = "1748589440592372301",
      endPort = "StoryEnd"
    }
  },
  storyNodeData = {
    ["1748589440592372300"] = {
      isStoryNode = true,
      key = "1748589440592372300",
      type = "StoryStartNode",
      name = "StoryStart",
      pos = {x = 800, y = 300},
      propsData = {QuestChainId = 0},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["1748589440592372301"] = {
      isStoryNode = true,
      key = "1748589440592372301",
      type = "StoryEndNode",
      name = "StoryEnd",
      pos = {x = 1469.3333333333333, y = 302.6666666666667},
      propsData = {},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["1748589440592372302"] = {
      isStoryNode = true,
      key = "1748589440592372302",
      type = "StoryNode",
      name = "常驻探索玩法",
      pos = {x = 1122.4147316821466, y = 295.16862745098035},
      propsData = {
        QuestId = 0,
        QuestDescriptionComment = "",
        QuestDescription = "",
        QuestDeatil = "",
        TaskRegionReName = "",
        TaskSubRegionReName = "",
        RecommendLevel = -1,
        bIsStartQuest = false,
        bIsEndQuest = false,
        bIsNotifyGameMode = true,
        bIsStartChapter = false,
        bIsEndChapter = false,
        bIsShowOnComplete = true,
        bIsPlayBlackScreenOnComplete = false,
        bIsPlayBlackScreenOnFail = false,
        bIsDynamicEvent = false,
        ResurgencePoint = "",
        bUseQuestCoordinate = false,
        bDeadTriggerQuestFail = false,
        IsFairyLand = false,
        SubRegionId = 0,
        SubRegionIdList = {},
        StoryGuideType = "Point",
        StoryGuidePointName = "",
        JumpId = 0
      },
      questNodeData = {
        lineData = {
          {
            startQuest = "1748589440592372303",
            startPort = "QuestStart",
            endQuest = "1748589440592372306",
            endPort = "In"
          },
          {
            startQuest = "17400474081841570247",
            startPort = "Option_1",
            endQuest = "1740122660018775",
            endPort = "In"
          },
          {
            startQuest = "1740122660018775",
            startPort = "Out",
            endQuest = "1748589440592372304",
            endPort = "Success"
          },
          {
            startQuest = "1740128244429669",
            startPort = "Out",
            endQuest = "1748589440592372304",
            endPort = "Success"
          },
          {
            startQuest = "1740128253049887",
            startPort = "Out",
            endQuest = "1748589440592372304",
            endPort = "Success"
          },
          {
            startQuest = "1743130164967975",
            startPort = "Out",
            endQuest = "1748589440592372304",
            endPort = "Success"
          },
          {
            startQuest = "17431302077341400",
            startPort = "Out",
            endQuest = "1748589440592372304",
            endPort = "Success"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_1",
            endQuest = "1743157689698263966",
            endPort = "In"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_2",
            endQuest = "17400474081841570247",
            endPort = "In"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_3",
            endQuest = "1743130164967975",
            endPort = "In"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_4",
            endQuest = "17431302077341400",
            endPort = "In"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_5",
            endQuest = "1743157774868265807",
            endPort = "In"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_6",
            endQuest = "17400489212604692955",
            endPort = "In"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_7",
            endQuest = "1743157789680266263",
            endPort = "In"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_8",
            endQuest = "1743157789680266264",
            endPort = "In"
          },
          {
            startQuest = "17400489212604692955",
            startPort = "Option_1",
            endQuest = "1740128244429669",
            endPort = "In"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_9",
            endQuest = "1743157846239268163",
            endPort = "In"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_10",
            endQuest = "17400489266054693105",
            endPort = "In"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_11",
            endQuest = "1743157866727268737",
            endPort = "In"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_12",
            endQuest = "1743157866727268738",
            endPort = "In"
          },
          {
            startQuest = "1743157689698263966",
            startPort = "Out",
            endQuest = "1748589440592372304",
            endPort = "Success"
          },
          {
            startQuest = "1743157774868265807",
            startPort = "Out",
            endQuest = "1748589440592372304",
            endPort = "Success"
          },
          {
            startQuest = "1743157789680266263",
            startPort = "Out",
            endQuest = "1748589440592372304",
            endPort = "Success"
          },
          {
            startQuest = "1743157789680266264",
            startPort = "Out",
            endQuest = "1748589440592372304",
            endPort = "Success"
          },
          {
            startQuest = "1743157846239268163",
            startPort = "Out",
            endQuest = "1748589440592372304",
            endPort = "Success"
          },
          {
            startQuest = "17400489266054693105",
            startPort = "Option_1",
            endQuest = "1740128253049887",
            endPort = "In"
          },
          {
            startQuest = "1743157866727268737",
            startPort = "Out",
            endQuest = "1748589440592372304",
            endPort = "Success"
          },
          {
            startQuest = "1743157866727268738",
            startPort = "Out",
            endQuest = "1748589440592372304",
            endPort = "Success"
          },
          {
            startQuest = "1743157896835269516",
            startPort = "Option_1",
            endQuest = "1740122660018775",
            endPort = "In"
          },
          {
            startQuest = "1743157896835269516",
            startPort = "Option_2",
            endQuest = "1740128244429669",
            endPort = "In"
          },
          {
            startQuest = "1743157896835269516",
            startPort = "Option_3",
            endQuest = "1740128253049887",
            endPort = "In"
          },
          {
            startQuest = "17400474081841570247",
            startPort = "Option_2",
            endQuest = "1748589440592372305",
            endPort = "Fail"
          },
          {
            startQuest = "17400489212604692955",
            startPort = "Option_2",
            endQuest = "1748589440592372305",
            endPort = "Fail"
          },
          {
            startQuest = "17400489266054693105",
            startPort = "Option_2",
            endQuest = "1748589440592372305",
            endPort = "Fail"
          },
          {
            startQuest = "1743157896835269516",
            startPort = "Option_4",
            endQuest = "1748589440592372305",
            endPort = "Fail"
          },
          {
            startQuest = "1748589440592372306",
            startPort = "Branch_13",
            endQuest = "1743157896835269516",
            endPort = "In"
          }
        },
        nodeData = {
          ["17400474081841570247"] = {
            key = "17400474081841570247",
            type = "TalkNode",
            name = "开启激光挑战一",
            pos = {x = 1637.9987417546638, y = -513.8679841897233},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 73000202,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {
                {
                  OptionText = "730002021",
                  OverrideBlend = false,
                  OverrideOutype = "FadeOut",
                  OverrideOutTime = 0
                },
                {
                  OptionText = "730002022",
                  OverrideBlend = false,
                  OverrideOutype = "FadeOut",
                  OverrideOutTime = 0
                }
              },
              OverrideFailBlend = false
            }
          },
          ["17400489212604692955"] = {
            key = "17400489212604692955",
            type = "TalkNode",
            name = "开启激光挑战二",
            pos = {x = 1625.5040322580646, y = 84.9177419354838},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 73000302,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {
                {
                  OptionText = "730003021",
                  OverrideBlend = false,
                  OverrideOutype = "FadeOut",
                  OverrideOutTime = 0
                },
                {
                  OptionText = "730003022",
                  OverrideBlend = false,
                  OverrideOutype = "FadeOut",
                  OverrideOutTime = 0
                }
              },
              OverrideFailBlend = false
            }
          },
          ["17400489266054693105"] = {
            key = "17400489266054693105",
            type = "TalkNode",
            name = "开启激光挑战三",
            pos = {x = 1655.3125, y = 685.9500000000002},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 73000402,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {
                {
                  OptionText = "730004021",
                  OverrideBlend = false,
                  OverrideOutype = "FadeOut",
                  OverrideOutTime = 0
                },
                {
                  OptionText = "730004022",
                  OverrideBlend = false,
                  OverrideOutype = "FadeOut",
                  OverrideOutTime = 0
                }
              },
              OverrideFailBlend = false
            }
          },
          ["1740122660018775"] = {
            key = "1740122660018775",
            type = "SendMessageNode",
            name = "开启挑战1",
            pos = {x = 2627.01628959276, y = 118.14906270200383},
            propsData = {
              MessageType = "GameMode",
              MessageContent = "StartChallenge1",
              UnitId = -1
            }
          },
          ["1740128244429669"] = {
            key = "1740128244429669",
            type = "SendMessageNode",
            name = "开启挑战2",
            pos = {x = 2577.4360902255644, y = 715.75},
            propsData = {
              MessageType = "GameMode",
              MessageContent = "StartChallenge2",
              UnitId = -1
            }
          },
          ["1740128253049887"] = {
            key = "1740128253049887",
            type = "SendMessageNode",
            name = "开启挑战3",
            pos = {x = 2533.276426360018, y = 968.0462184873951},
            propsData = {
              MessageType = "GameMode",
              MessageContent = "StartChallenge3",
              UnitId = -1
            }
          },
          ["1743130164967975"] = {
            key = "1743130164967975",
            type = "TalkNode",
            name = "挑战一挑战成功",
            pos = {x = 1638.0454545454545, y = -330.09090909090895},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 73000203,
              FlowAssetPath = "",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17431302077341400"] = {
            key = "17431302077341400",
            type = "TalkNode",
            name = "挑战一挑战失败",
            pos = {x = 1638.840909090909, y = -195.88636363636346},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 73000204,
              FlowAssetPath = "",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1743157689698263966"] = {
            key = "1743157689698263966",
            type = "TalkNode",
            name = "剧情引入挑战一",
            pos = {x = 1640.4073897403132, y = -647.6835928881693},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 73000201,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1743157774868265807"] = {
            key = "1743157774868265807",
            type = "TalkNode",
            name = "剧情引入挑战二",
            pos = {x = 1632.9073897403132, y = -45.1835928881693},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 73000301,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1743157789680266263"] = {
            key = "1743157789680266263",
            type = "TalkNode",
            name = "挑战二挑战成功",
            pos = {x = 1642.509662467586, y = 296.988327932945},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 73000303,
              FlowAssetPath = "",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1743157789680266264"] = {
            key = "1743157789680266264",
            type = "TalkNode",
            name = "挑战二挑战失败",
            pos = {x = 1643.3051170130404, y = 424.41867983910345},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 73000304,
              FlowAssetPath = "",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1743157846239268163"] = {
            key = "1743157846239268163",
            type = "TalkNode",
            name = "剧情引入挑战三",
            pos = {x = 1648.2219058693454, y = 556.680043475467},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 73000401,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1743157866727268737"] = {
            key = "1743157866727268737",
            type = "TalkNode",
            name = "挑战三挑战成功",
            pos = {x = 1659.291920532102, y = 870.0777707481942},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 73000403,
              FlowAssetPath = "",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0.5,
              BlendOutTime = 2,
              InType = "BlendIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1743157866727268738"] = {
            key = "1743157866727268738",
            type = "TalkNode",
            name = "挑战三挑战失败",
            pos = {x = 1672.0551170130404, y = 1018.2823162027397},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 73000405,
              FlowAssetPath = "",
              TalkType = "FixSimple",
              TalkStageName = "",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1743157896835269516"] = {
            key = "1743157896835269516",
            type = "TalkNode",
            name = "开启激光重复挑战",
            pos = {x = 1668.4261363636365, y = 1173.6488636363638},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 73000502,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {
                {
                  OptionText = "730005021",
                  OverrideBlend = false,
                  OverrideOutype = "FadeOut",
                  OverrideOutTime = 0
                },
                {
                  OptionText = "730005022",
                  OverrideBlend = false,
                  OverrideOutype = "FadeOut",
                  OverrideOutTime = 0
                },
                {
                  OptionText = "730005023",
                  OverrideBlend = false,
                  OverrideOutype = "FadeOut",
                  OverrideOutTime = 0
                },
                {
                  OptionText = "730005024",
                  OverrideBlend = false,
                  OverrideOutype = "FadeOut",
                  OverrideOutTime = 0
                }
              },
              OverrideFailBlend = false
            }
          },
          ["1748589440592372303"] = {
            key = "1748589440592372303",
            type = "QuestStartNode",
            name = "QuestStart",
            pos = {x = 530, y = 398.5},
            propsData = {ModeType = 0}
          },
          ["1748589440592372304"] = {
            key = "1748589440592372304",
            type = "QuestSuccessNode",
            name = "QuestSuccess",
            pos = {x = 3024.7688311688316, y = 513.0038961038961},
            propsData = {ModeType = 0}
          },
          ["1748589440592372305"] = {
            key = "1748589440592372305",
            type = "QuestFailNode",
            name = "QuestFail",
            pos = {x = 2998.1090909090913, y = -24.06363636363642},
            propsData = {}
          },
          ["1748589440592372306"] = {
            key = "1748589440592372306",
            type = "BranchTriggerNode",
            name = "触发分支节点",
            pos = {x = 862.9446640316207, y = 211.03201581027662},
            propsData = {
              Branches = {
                8200011,
                8200012,
                8200013,
                8200014,
                8200021,
                8200022,
                8200023,
                8200024,
                8200031,
                8200032,
                8200033,
                8200034,
                8200042
              }
            }
          }
        },
        commentData = {}
      }
    }
  },
  commentData = {}
}
