local hotfix_data = "\t-- 请在此处编写HotFix代码,请组长编写\n\tlocal ActivityUtils = require \"Blueprints.UI.WBP.Activity.ActivityUtils\"\n\tHotFix(ActivityUtils, \"GetCurrentAllActivityWithoutSystemCheck\",\n\t\tfunction( ... )\n\t\t\tlocal AllActivityTabIdx = {}\n\t\t\tlocal CheckIsBanList = {114001, 109001, 103019}\n\t\t\tfor key, TabConfigInfo in pairs(DataMgr.EventTab) do\n\t\t\t\tlocal bIsNeedAddInList = true\n\t\t\t\tif (type(TabConfigInfo.EventId) == \"table\") then\n\t\t\t\t\tfor _, CheckEventId in ipairs(TabConfigInfo.EventId) do\n\t\t\t\t\t\tif CheckEventId == CheckIsBanList[1] or CheckEventId == CheckIsBanList[2] or CheckEventId == CheckIsBanList[3] then\n\t\t\t\t\t\t\tbIsNeedAddInList = false\n\t\t\t\t\t\t\tbreak\n\t\t\t\t\t\tend\n\t\t\t\t\tend\n\t\t\t\t\tif bIsNeedAddInList then\n\t\t\t\t\t\tlocal EventConfigData = DataMgr.EventMain[TabConfigInfo.EventId[1]]\n\t\t\t\t\t\tif ActivityUtils.IsComeBackEvent(TabConfigInfo.EventId[1]) then\n\t\t\t\t\t\t\tif ActivityUtils.CheckComeBackEventIsOpen(TabConfigInfo.EventId[1]) then\n\t\t\t\t\t\t\t\ttable.insert(AllActivityTabIdx, TabConfigInfo.EventTabId) -- 还有问题，需要考虑配表回归活动交替时的情况\n\t\t\t\t\t\t\tend\n\t\t\t\t\t\telse\n\t\t\t\t\t\t\tif (ActivityUtils.CheckEventIsOpen(TabConfigInfo.EventId[1], EventConfigData, true, nil)) then\n\t\t\t\t\t\t\t\ttable.insert(AllActivityTabIdx, TabConfigInfo.EventTabId)\n\t\t\t\t\t\t\tend\n\t\t\t\t\t\tend\n\t\t\t\t\tend\n\t\t\t\telse\n\t\t\t\t\tif TabConfigInfo.EventId == CheckIsBanList[1] or TabConfigInfo.EventId == CheckIsBanList[2] or TabConfigInfo.EventId == CheckIsBanList[3] then\n\t\t\t\t\t\tbIsNeedAddInList = false\n\t\t\t\t\tend\n\t\t\t\t\tif bIsNeedAddInList then\n\t\t\t\t\t\tlocal EventConfigData = DataMgr.EventMain[TabConfigInfo.EventId]\n\t\t\t\t\t\tif (ActivityUtils.CheckEventIsOpen(TabConfigInfo.EventId, EventConfigData, true, nil)) then\n\t\t\t\t\t\t\ttable.insert(AllActivityTabIdx, TabConfigInfo.EventTabId)\n\t\t\t\t\t\tend\n\t\t\t\t\tend\n\t\t\t\tend\n\t\t\tend\n\n\t\t\ttable.sort(AllActivityTabIdx, function(Data1, Data2)\n\t\t\t\tif (DataMgr.EventTab[Data1].Sequence == DataMgr.EventTab[Data2].Sequence) then\n\t\t\t\t\treturn DataMgr.EventTab[Data1].EventTabId < DataMgr.EventTab[Data2].EventTabId\n\t\t\t\telse\n\t\t\t\t\treturn DataMgr.EventTab[Data1].Sequence > DataMgr.EventTab[Data2].Sequence\n\t\t\t\tend\n\t\t\tend)\n\n\t\t\tlocal AllActivityID = {}\n\t\t\tfor _, v in ipairs(AllActivityTabIdx) do\n\t\t\t\tlocal EventConfigData = DataMgr.EventTab[v]\n\t\t\t\tif (type(EventConfigData.EventId) == \"table\") then\n\t\t\t\t\ttable.insert(AllActivityID, EventConfigData.EventId)\n\t\t\t\telse\n\t\t\t\t\ttable.insert(AllActivityID, {EventConfigData.EventId})\n\t\t\t\tend\n\t\t\tend\n\n\t\t\treturn AllActivityID, AllActivityTabIdx\n\t\tend\n\t)\n"
return {
  index = 1,
  script = hotfix_data,
  client_version = {ForceUpdateCheck = "4"},
  force_update_version = "4",
  patch_version = {
    ["1"] = "0"
  }
}
