local T = {}
T.RT_1 = {0, 0}
T.RT_2 = {4, 4}
T.RT_3 = {2, 2}
T.RT_4 = {300, 500}
T.RT_5 = {
  1,
  1,
  1,
  1
}
T.RT_6 = {1000, 1500}
T.RT_7 = {
  0,
  0,
  0,
  0,
  0
}
T.RT_8 = {
  2,
  2,
  2,
  2,
  0
}
T.RT_9 = {200, 2000}
T.RT_10 = {
  2,
  2,
  2,
  2,
  1
}
T.RT_11 = {800, 2000}
T.RT_12 = {
  0,
  0,
  0,
  0,
  0,
  0
}
T.RT_13 = {
  3,
  3,
  1,
  3,
  3,
  1
}
T.RT_14 = {1200, 2000}
T.RT_15 = {
  2,
  2,
  1,
  2,
  2,
  1
}
T.RT_16 = {
  6012,
  6022,
  6023,
  8011,
  8021,
  8022
}
T.RT_17 = {0, 2000}
T.RT_18 = {
  6012,
  6022,
  6023,
  7012,
  7023,
  7024
}
T.RT_19 = {
  3,
  3,
  1,
  3,
  3
}
T.RT_20 = {
  2,
  2,
  1,
  2,
  2
}
T.RT_21 = {
  6012,
  6022,
  6023,
  9011,
  9021
}
T.RT_22 = {
  6010,
  6011,
  6020,
  6021,
  6030
}
T.RT_23 = {1, 1}
T.RT_24 = {1000, 3000}
T.RT_25 = {0}
T.RT_26 = {1}
T.RT_27 = {1500, 2000}
T.RT_28 = {
  0,
  0,
  0,
  0
}
T.RT_29 = {
  2,
  1,
  1,
  1
}
T.RT_30 = {200, 3000}
T.RT_31 = {
  6010,
  6011,
  6020,
  6021
}
T.RT_32 = {
  2,
  1,
  2,
  1
}
T.RT_33 = {1200, 3000}
T.RT_34 = {
  2,
  1,
  2,
  1,
  1
}
T.RT_35 = {
  0,
  0,
  0
}
T.RT_36 = {
  2,
  1,
  1
}
T.RT_37 = {
  3,
  1,
  1
}
T.RT_38 = {600, 2000}
T.RT_39 = {400, 3000}
T.RT_40 = {
  6050,
  6051,
  6052
}
T.RT_41 = {
  7010,
  7020,
  7022
}
T.RT_42 = {
  2,
  2,
  1
}
T.RT_43 = {
  1,
  3,
  1
}
T.RT_44 = {
  7010,
  7020,
  7022,
  6010
}
T.RT_45 = {
  2,
  2,
  1,
  1
}
T.RT_46 = {
  1,
  2,
  1,
  1
}
T.RT_47 = {
  2,
  1,
  2
}
T.RT_48 = {
  2,
  3,
  1
}
T.RT_49 = {
  1,
  2,
  2
}
T.RT_50 = {
  1,
  1,
  2
}
T.RT_51 = {
  6040,
  6042,
  8040
}
T.RT_52 = {
  6050,
  6052,
  8050
}
T.RT_53 = {
  6040,
  6042,
  9040
}
T.RT_54 = {600, 3000}
T.RT_55 = {
  6050,
  6052,
  9050
}
local LocalTimeProxy = (DataMgr or {}).LocalTimeProxy or function(x)
  return x
end
local ReadOnly = (DataMgr or {}).ReadOnly or function(n, x)
  return x
end
return ReadOnly("MonsterGroupSpawn", {
  [1] = {
    GroupDetectDelayTime = 5,
    GroupDetectTime = 2,
    GroupInitUnitSpawnCenterRange = {2000, 2100},
    GroupLevel = T.RT_1,
    GroupLimit = 30,
    GroupNumber = T.RT_2,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 4,
    GroupSpawnId = 1,
    GroupThreshold = 20,
    GroupUnitSpawnCenterRange = {500, 510},
    GroupWeight = T.RT_3,
    MonsterGroupIds = {7010, 7020}
  },
  [2] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 2,
    GroupInitUnitSpawnCenterRange = T.RT_6,
    GroupLevel = T.RT_7,
    GroupLimit = 30,
    GroupNumber = T.RT_8,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 4,
    GroupSpawnId = 2,
    GroupThreshold = 20,
    GroupUnitSpawnCenterRange = T.RT_9,
    GroupWeight = T.RT_10,
    MonsterGroupIds = {
      7010,
      7011,
      7020,
      7021,
      7030
    }
  },
  [3] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 2,
    GroupInitUnitSpawnCenterRange = T.RT_6,
    GroupLevel = T.RT_7,
    GroupLimit = 30,
    GroupNumber = T.RT_8,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 4,
    GroupSpawnId = 3,
    GroupThreshold = 20,
    GroupUnitSpawnCenterRange = T.RT_9,
    GroupWeight = T.RT_10,
    MonsterGroupIds = T.RT_22
  },
  [4] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 2,
    GroupInitUnitSpawnCenterRange = T.RT_6,
    GroupLevel = T.RT_1,
    GroupLimit = 30,
    GroupNumber = T.RT_2,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 4,
    GroupSpawnId = 4,
    GroupThreshold = 20,
    GroupUnitSpawnCenterRange = T.RT_9,
    GroupWeight = T.RT_23,
    MonsterGroupIds = {8010, 8020}
  },
  [5] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 2,
    GroupInitUnitSpawnCenterRange = T.RT_6,
    GroupLevel = T.RT_1,
    GroupLimit = 30,
    GroupNumber = T.RT_2,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 4,
    GroupSpawnId = 5,
    GroupThreshold = 20,
    GroupUnitSpawnCenterRange = T.RT_9,
    GroupWeight = T.RT_23,
    MonsterGroupIds = {9010, 9020}
  },
  [11] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_4,
    GroupLevel = T.RT_5,
    GroupLimit = 30,
    GroupNumber = {
      3,
      3,
      3,
      3
    },
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 11,
    GroupThreshold = 25,
    GroupUnitSpawnCenterRange = T.RT_4,
    GroupWeight = T.RT_5,
    MonsterGroupIds = {
      11,
      12,
      13,
      14
    }
  },
  [60037] = {
    GroupDetectDelayTime = 0,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_9,
    GroupLevel = T.RT_28,
    GroupLimit = 35,
    GroupNumber = T.RT_29,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 60037,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_30,
    GroupWeight = T.RT_29,
    MonsterGroupIds = T.RT_31
  },
  [60055] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_28,
    GroupLimit = 50,
    GroupNumber = T.RT_32,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 60055,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_33,
    GroupWeight = T.RT_32,
    MonsterGroupIds = T.RT_31
  },
  [60073] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_28,
    GroupLimit = 50,
    GroupNumber = T.RT_32,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 60073,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_33,
    GroupWeight = {
      1,
      1,
      3,
      1
    },
    MonsterGroupIds = T.RT_31
  },
  [60137] = {
    GroupDetectDelayTime = 0,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_9,
    GroupLevel = T.RT_7,
    GroupLimit = 35,
    GroupNumber = {
      2,
      1,
      1,
      1,
      1
    },
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 60137,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_30,
    GroupWeight = {
      3,
      1,
      1,
      1,
      1
    },
    MonsterGroupIds = T.RT_22
  },
  [60155] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_7,
    GroupLimit = 50,
    GroupNumber = T.RT_34,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 60155,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_33,
    GroupWeight = T.RT_34,
    MonsterGroupIds = T.RT_22
  },
  [60173] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_7,
    GroupLimit = 50,
    GroupNumber = T.RT_34,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 60173,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_33,
    GroupWeight = {
      1,
      1,
      3,
      1,
      1
    },
    MonsterGroupIds = T.RT_22
  },
  [60200] = {
    GroupDetectDelayTime = 2,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_9,
    GroupLevel = T.RT_35,
    GroupLimit = 35,
    GroupNumber = T.RT_36,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 60200,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_30,
    GroupWeight = T.RT_37,
    MonsterGroupIds = {
      6040,
      6041,
      6042
    }
  },
  [60201] = {
    GroupDetectDelayTime = 2,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_28,
    GroupLimit = 40,
    GroupNumber = {
      2,
      1,
      1,
      0
    },
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 60201,
    GroupThreshold = 35,
    GroupUnitSpawnCenterRange = T.RT_24,
    GroupWeight = {
      3,
      2,
      2,
      1
    },
    MonsterGroupIds = {
      6040,
      6041,
      6042,
      6030
    }
  },
  [60501] = {
    GroupDetectDelayTime = 1,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_38,
    GroupLevel = T.RT_35,
    GroupLimit = 40,
    GroupNumber = T.RT_36,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 60501,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_39,
    GroupWeight = T.RT_37,
    MonsterGroupIds = T.RT_40
  },
  [60502] = {
    GroupDetectDelayTime = 1,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_38,
    GroupLevel = T.RT_35,
    GroupLimit = 30,
    GroupNumber = T.RT_36,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 60502,
    GroupThreshold = 25,
    GroupUnitSpawnCenterRange = T.RT_39,
    GroupWeight = T.RT_37,
    MonsterGroupIds = T.RT_40
  },
  [70037] = {
    GroupDetectDelayTime = 0,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_9,
    GroupLevel = T.RT_35,
    GroupLimit = 35,
    GroupNumber = T.RT_36,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 70037,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_30,
    GroupWeight = T.RT_36,
    MonsterGroupIds = T.RT_41
  },
  [70055] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_35,
    GroupLimit = 50,
    GroupNumber = T.RT_42,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 70055,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_33,
    GroupWeight = T.RT_42,
    MonsterGroupIds = T.RT_41
  },
  [70073] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_35,
    GroupLimit = 50,
    GroupNumber = T.RT_43,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 70073,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_33,
    GroupWeight = T.RT_43,
    MonsterGroupIds = T.RT_41
  },
  [70137] = {
    GroupDetectDelayTime = 0,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_9,
    GroupLevel = T.RT_28,
    GroupLimit = 35,
    GroupNumber = T.RT_29,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 70137,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_30,
    GroupWeight = T.RT_29,
    MonsterGroupIds = T.RT_44
  },
  [70155] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_28,
    GroupLimit = 50,
    GroupNumber = T.RT_45,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 70155,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_33,
    GroupWeight = T.RT_46,
    MonsterGroupIds = T.RT_44
  },
  [70173] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_28,
    GroupLimit = 50,
    GroupNumber = T.RT_45,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 70173,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_33,
    GroupWeight = T.RT_46,
    MonsterGroupIds = {
      7010,
      7020,
      7022,
      6020
    }
  },
  [70200] = {
    GroupDetectDelayTime = 2,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_9,
    GroupLevel = T.RT_1,
    GroupLimit = 35,
    GroupNumber = T.RT_3,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 70200,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_30,
    GroupWeight = {2, 1},
    MonsterGroupIds = {7040, 7041}
  },
  [70201] = {
    GroupDetectDelayTime = 2,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_28,
    GroupLimit = 40,
    GroupNumber = {
      2,
      2,
      0,
      0
    },
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 70201,
    GroupThreshold = 35,
    GroupUnitSpawnCenterRange = T.RT_24,
    GroupWeight = {
      3,
      2,
      1,
      1
    },
    MonsterGroupIds = {
      7040,
      7041,
      7042,
      7044
    }
  },
  [80037] = {
    GroupDetectDelayTime = 0,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_9,
    GroupLevel = T.RT_35,
    GroupLimit = 35,
    GroupNumber = T.RT_47,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 80037,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_30,
    GroupWeight = T.RT_47,
    MonsterGroupIds = {
      8010,
      8020,
      6010
    }
  },
  [80055] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_28,
    GroupLimit = 50,
    GroupNumber = T.RT_45,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 80055,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_33,
    GroupWeight = T.RT_45,
    MonsterGroupIds = {
      8010,
      8020,
      6010,
      6020
    }
  },
  [80073] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_35,
    GroupLimit = 50,
    GroupNumber = T.RT_48,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 80073,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_33,
    GroupWeight = T.RT_49,
    MonsterGroupIds = {
      8010,
      8020,
      6020
    }
  },
  [80200] = {
    GroupDetectDelayTime = 2,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_9,
    GroupLevel = T.RT_35,
    GroupLimit = 35,
    GroupNumber = T.RT_50,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 80200,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_30,
    GroupWeight = T.RT_50,
    MonsterGroupIds = T.RT_51
  },
  [80201] = {
    GroupDetectDelayTime = 2,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_35,
    GroupLimit = 40,
    GroupNumber = T.RT_50,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 80201,
    GroupThreshold = 35,
    GroupUnitSpawnCenterRange = T.RT_24,
    GroupWeight = T.RT_50,
    MonsterGroupIds = T.RT_51
  },
  [80501] = {
    GroupDetectDelayTime = 1,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_38,
    GroupLevel = T.RT_35,
    GroupLimit = 40,
    GroupNumber = T.RT_50,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 80501,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_39,
    GroupWeight = T.RT_50,
    MonsterGroupIds = T.RT_52
  },
  [80502] = {
    GroupDetectDelayTime = 1,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_38,
    GroupLevel = T.RT_35,
    GroupLimit = 30,
    GroupNumber = T.RT_50,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 80502,
    GroupThreshold = 25,
    GroupUnitSpawnCenterRange = T.RT_39,
    GroupWeight = T.RT_50,
    MonsterGroupIds = T.RT_52
  },
  [90037] = {
    GroupDetectDelayTime = 0,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_9,
    GroupLevel = T.RT_35,
    GroupLimit = 35,
    GroupNumber = T.RT_47,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 90037,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_30,
    GroupWeight = T.RT_47,
    MonsterGroupIds = {
      9010,
      9020,
      6010
    }
  },
  [90055] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_28,
    GroupLimit = 50,
    GroupNumber = T.RT_45,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 90055,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_33,
    GroupWeight = T.RT_45,
    MonsterGroupIds = {
      9010,
      9020,
      6010,
      6020
    }
  },
  [90073] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_35,
    GroupLimit = 50,
    GroupNumber = T.RT_48,
    GroupRadius = 500,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 90073,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_33,
    GroupWeight = T.RT_49,
    MonsterGroupIds = {
      9010,
      9020,
      6020
    }
  },
  [90200] = {
    GroupDetectDelayTime = 2,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_9,
    GroupLevel = T.RT_35,
    GroupLimit = 35,
    GroupNumber = T.RT_50,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 90200,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_30,
    GroupWeight = T.RT_50,
    MonsterGroupIds = T.RT_53
  },
  [90201] = {
    GroupDetectDelayTime = 2,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_14,
    GroupLevel = T.RT_35,
    GroupLimit = 40,
    GroupNumber = T.RT_50,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 90201,
    GroupThreshold = 35,
    GroupUnitSpawnCenterRange = T.RT_24,
    GroupWeight = T.RT_50,
    MonsterGroupIds = T.RT_53
  },
  [90501] = {
    GroupDetectDelayTime = 1,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_38,
    GroupLevel = T.RT_35,
    GroupLimit = 40,
    GroupNumber = T.RT_50,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 90501,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_54,
    GroupWeight = T.RT_50,
    MonsterGroupIds = T.RT_55
  },
  [90502] = {
    GroupDetectDelayTime = 1,
    GroupDetectTime = 0.5,
    GroupInitUnitSpawnCenterRange = T.RT_38,
    GroupLevel = T.RT_35,
    GroupLimit = 30,
    GroupNumber = T.RT_50,
    GroupRadius = 800,
    GroupRangeZ = 500,
    GroupReplenishInterval = 1,
    GroupSpawnId = 90502,
    GroupThreshold = 25,
    GroupUnitSpawnCenterRange = T.RT_54,
    GroupWeight = T.RT_50,
    MonsterGroupIds = T.RT_55
  },
  [2200101] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_11,
    GroupLevel = T.RT_12,
    GroupLimit = 50,
    GroupNumber = T.RT_13,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200101,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_14,
    GroupWeight = T.RT_15,
    MonsterGroupIds = T.RT_16
  },
  [2200102] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_17,
    GroupLevel = T.RT_12,
    GroupLimit = 50,
    GroupNumber = T.RT_13,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200102,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_17,
    GroupWeight = T.RT_15,
    MonsterGroupIds = T.RT_16
  },
  [2200201] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_11,
    GroupLevel = T.RT_12,
    GroupLimit = 50,
    GroupNumber = T.RT_13,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200201,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_14,
    GroupWeight = T.RT_15,
    MonsterGroupIds = T.RT_18
  },
  [2200202] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_17,
    GroupLevel = T.RT_12,
    GroupLimit = 50,
    GroupNumber = T.RT_13,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200202,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_17,
    GroupWeight = T.RT_15,
    MonsterGroupIds = T.RT_18
  },
  [2200301] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = {800, 1200},
    GroupLevel = T.RT_7,
    GroupLimit = 50,
    GroupNumber = T.RT_19,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200301,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_14,
    GroupWeight = T.RT_20,
    MonsterGroupIds = T.RT_21
  },
  [2200302] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_17,
    GroupLevel = T.RT_7,
    GroupLimit = 50,
    GroupNumber = T.RT_19,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200302,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_17,
    GroupWeight = T.RT_20,
    MonsterGroupIds = T.RT_21
  },
  [2200401] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_11,
    GroupLevel = T.RT_12,
    GroupLimit = 50,
    GroupNumber = T.RT_13,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200401,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_14,
    GroupWeight = T.RT_15,
    MonsterGroupIds = T.RT_18
  },
  [2200402] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_17,
    GroupLevel = T.RT_12,
    GroupLimit = 50,
    GroupNumber = T.RT_13,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200402,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_17,
    GroupWeight = T.RT_15,
    MonsterGroupIds = T.RT_18
  },
  [2200501] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_11,
    GroupLevel = T.RT_12,
    GroupLimit = 50,
    GroupNumber = T.RT_13,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200501,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_14,
    GroupWeight = T.RT_15,
    MonsterGroupIds = T.RT_16
  },
  [2200502] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_17,
    GroupLevel = T.RT_12,
    GroupLimit = 50,
    GroupNumber = T.RT_13,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200502,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_17,
    GroupWeight = T.RT_15,
    MonsterGroupIds = T.RT_16
  },
  [2200601] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_11,
    GroupLevel = T.RT_7,
    GroupLimit = 50,
    GroupNumber = T.RT_19,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200601,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_14,
    GroupWeight = T.RT_20,
    MonsterGroupIds = T.RT_21
  },
  [2200602] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_17,
    GroupLevel = T.RT_7,
    GroupLimit = 50,
    GroupNumber = T.RT_19,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200602,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_17,
    GroupWeight = T.RT_20,
    MonsterGroupIds = T.RT_21
  },
  [2200701] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_11,
    GroupLevel = T.RT_7,
    GroupLimit = 50,
    GroupNumber = T.RT_19,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200701,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_14,
    GroupWeight = T.RT_20,
    MonsterGroupIds = T.RT_21
  },
  [2200702] = {
    GroupDetectDelayTime = 3,
    GroupDetectTime = 1,
    GroupInitUnitSpawnCenterRange = T.RT_17,
    GroupLevel = T.RT_7,
    GroupLimit = 50,
    GroupNumber = T.RT_19,
    GroupRadius = 600,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0.5,
    GroupSpawnId = 2200702,
    GroupThreshold = 30,
    GroupUnitSpawnCenterRange = T.RT_17,
    GroupWeight = T.RT_20,
    MonsterGroupIds = T.RT_21
  },
  [6001012] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6001012,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6001012}
  },
  [6001013] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6001013,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6001013}
  },
  [6001014] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6001014,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6001014}
  },
  [6001016] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6001016,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6001016}
  },
  [6001018] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6001018,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6001018}
  },
  [6002011] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6002011,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6002011}
  },
  [6002015] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6002015,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6002015}
  },
  [6002016] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6002016,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6002016}
  },
  [6002017] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6002017,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6002017}
  },
  [6002018] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6002018,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6002018}
  },
  [6004013] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6004013,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6004013}
  },
  [6011019] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6011019,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6011019}
  },
  [6011020] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6011020,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6011020}
  },
  [6011021] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6011021,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6011021}
  },
  [6011023] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6011023,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6011023}
  },
  [6011024] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6011024,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6011024}
  },
  [6012019] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6012019,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6012019}
  },
  [6012021] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6012021,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6012021}
  },
  [6012022] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6012022,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6012022}
  },
  [6012023] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6012023,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6012023}
  },
  [6012024] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 6012024,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {6012024}
  },
  [7001011] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7001011,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7001011}
  },
  [7001015] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7001015,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7001015}
  },
  [7001016] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7001016,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7001016}
  },
  [7001017] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7001017,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7001017}
  },
  [7001018] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7001018,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7001018}
  },
  [7001019] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7001019,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7001019}
  },
  [7001021] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7001021,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7001021}
  },
  [7001022] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7001022,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7001022}
  },
  [7001023] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7001023,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7001023}
  },
  [7001024] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7001024,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7001024}
  },
  [7002011] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7002011,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7002011}
  },
  [7002012] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7002012,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7002012}
  },
  [7002013] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7002013,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7002013}
  },
  [7002014] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7002014,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7002014}
  },
  [7002016] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7002016,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7002016}
  },
  [7002017] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7002017,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7002017}
  },
  [7002018] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7002018,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7002018}
  },
  [7002019] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7002019,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7002019}
  },
  [7002020] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7002020,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7002020}
  },
  [7002021] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7002021,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7002021}
  },
  [7002023] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7002023,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7002023}
  },
  [7002024] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7002024,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7002024}
  },
  [7003011] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7003011,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7003011}
  },
  [7003015] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7003015,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7003015}
  },
  [7003016] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7003016,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7003016}
  },
  [7003017] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7003017,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7003017}
  },
  [7003018] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7003018,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7003018}
  },
  [7003019] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7003019,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7003019}
  },
  [7003021] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7003021,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7003021}
  },
  [7003022] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7003022,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7003022}
  },
  [7003023] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7003023,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7003023}
  },
  [7003024] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7003024,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7003024}
  },
  [7008601] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 7008601,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {7021}
  },
  [8001011] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001011,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001011}
  },
  [8001012] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001012,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001012}
  },
  [8001013] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001013,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001013}
  },
  [8001014] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001014,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001014}
  },
  [8001015] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001015,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001015}
  },
  [8001016] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001016,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001016}
  },
  [8001017] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001017,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001017}
  },
  [8001018] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001018,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001018}
  },
  [8001019] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001019,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001019}
  },
  [8001020] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001020,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001020}
  },
  [8001021] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001021,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001021}
  },
  [8001022] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001022,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001022}
  },
  [8001023] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001023,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001023}
  },
  [8001024] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8001024,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8001024}
  },
  [8002011] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002011,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002011}
  },
  [8002012] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002012,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002012}
  },
  [8002013] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002013,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002013}
  },
  [8002014] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002014,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002014}
  },
  [8002015] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002015,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002015}
  },
  [8002016] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002016,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002016}
  },
  [8002017] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002017,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002017}
  },
  [8002018] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002018,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002018}
  },
  [8002019] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002019,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002019}
  },
  [8002020] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002020,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002020}
  },
  [8002021] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002021,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002021}
  },
  [8002022] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002022,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002022}
  },
  [8002023] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002023,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002023}
  },
  [8002024] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002024,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002024}
  },
  [8002701] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002701,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002701}
  },
  [8002702] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002702,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002702}
  },
  [8002703] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002703,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002703}
  },
  [8002704] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8002704,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8002704}
  },
  [8003011] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003011,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003011}
  },
  [8003012] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003012,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003012}
  },
  [8003013] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003013,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003013}
  },
  [8003014] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003014,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003014}
  },
  [8003015] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003015,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003015}
  },
  [8003016] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003016,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003016}
  },
  [8003017] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003017,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003017}
  },
  [8003018] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003018,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003018}
  },
  [8003019] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003019,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003019}
  },
  [8003020] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003020,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003020}
  },
  [8003021] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003021,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003021}
  },
  [8003022] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003022,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003022}
  },
  [8003023] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003023,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003023}
  },
  [8003024] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003024,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003024}
  },
  [8003701] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003701,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003701}
  },
  [8003702] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003702,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003702}
  },
  [8003703] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003703,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003703}
  },
  [8003704] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 8003704,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {8003704}
  },
  [9001011] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001011,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001011}
  },
  [9001012] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001012,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001012}
  },
  [9001013] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001013,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001013}
  },
  [9001014] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001014,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001014}
  },
  [9001015] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001015,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001015}
  },
  [9001016] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001016,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001016}
  },
  [9001017] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001017,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001017}
  },
  [9001018] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001018,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001018}
  },
  [9001019] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001019,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001019}
  },
  [9001020] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001020,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001020}
  },
  [9001021] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001021,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001021}
  },
  [9001022] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001022,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001022}
  },
  [9001023] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001023,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001023}
  },
  [9001024] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9001024,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9001024}
  },
  [9002011] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002011,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002011}
  },
  [9002012] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002012,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002012}
  },
  [9002013] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002013,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002013}
  },
  [9002014] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002014,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002014}
  },
  [9002015] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002015,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002015}
  },
  [9002016] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002016,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002016}
  },
  [9002017] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002017,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002017}
  },
  [9002018] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002018,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002018}
  },
  [9002019] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002019,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002019}
  },
  [9002020] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002020,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002020}
  },
  [9002021] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002021,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002021}
  },
  [9002022] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002022,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002022}
  },
  [9002023] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002023,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002023}
  },
  [9002024] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9002024,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9002024}
  },
  [9007011] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007011,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007011}
  },
  [9007012] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007012,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007012}
  },
  [9007013] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007013,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007013}
  },
  [9007014] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007014,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007014}
  },
  [9007015] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007015,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007015}
  },
  [9007016] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007016,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007016}
  },
  [9007017] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007017,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007017}
  },
  [9007018] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007018,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007018}
  },
  [9007019] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007019,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007019}
  },
  [9007020] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007020,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007020}
  },
  [9007021] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007021,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007021}
  },
  [9007022] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007022,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007022}
  },
  [9007023] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007023,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007023}
  },
  [9007024] = {
    CloseGroupReplenish = true,
    GroupDetectDelayTime = 0,
    GroupDetectTime = 0,
    GroupInitUnitSpawnCenterRange = T.RT_24,
    GroupLevel = T.RT_25,
    GroupLimit = 60,
    GroupNumber = T.RT_26,
    GroupRadius = 300,
    GroupRangeZ = 500,
    GroupReplenishInterval = 0,
    GroupSpawnId = 9007024,
    GroupThreshold = 10,
    GroupUnitSpawnCenterRange = T.RT_27,
    GroupWeight = T.RT_26,
    MonsterGroupIds = {9007024}
  }
})
