local T = {}
T.RT_1 = {
  "UI_OPTION_Swicth_Close",
  "UI_OPTION_Swicth_Open"
}
T.RT_2 = {
  "UI_EffectQuality_ExtremelyLow",
  "UI_EffectQuality_Low",
  "UI_EffectQuality_Middle",
  "UI_EffectQuality_High",
  "UI_EffectQuality_ExtremelyHigh"
}
T.RT_3 = {0}
T.RT_4 = {0, 10}
T.RT_5 = {0, 100}
T.RT_6 = {1, 20}
T.RT_7 = {
  "90%",
  "95%",
  "100%"
}
T.RT_8 = {
  "UI_Setting_Hide",
  "UI_Setting_Display"
}
T.RT_9 = {
  "UI_OPTION_Swicth_Close",
  "UI_EffectQuality_Low",
  "UI_EffectQuality_Middle",
  "UI_EffectQuality_High"
}
T.RT_10 = {
  1,
  2,
  4,
  5,
  7
}
T.RT_11 = {
  3,
  2,
  4,
  5
}
T.RT_12 = {
  1,
  2,
  4,
  5
}
T.RT_13 = {
  0,
  1,
  2,
  2
}
local LocalTimeProxy = (DataMgr or {}).LocalTimeProxy or function(x)
  return x
end
local ReadOnly = (DataMgr or {}).ReadOnly or function(n, x)
  return x
end
return ReadOnly("Option", {
  AimAssist = {
    Cache = "AimAssist",
    CacheText = "UI_OPTION_AimAssist",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "True",
    EMCacheName = "IsOpenHelperAim",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 18,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  AmbientOcclusion = {
    Cache = "AmbientOcclusion",
    CacheText = "UI_OPTION_AmbientOcclusion",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "ConsoleVariable",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 82,
    SpecialHide = 99,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true
  },
  AntiAliasing = {
    Cache = "AntiAliasing",
    CacheText = "UI_OPTION_AntiAliasing",
    ControlType = "UnFold",
    DefaultValue = "2",
    DefaultValueM = "2",
    EMCacheName = "AntiAliasing",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 64,
    SubOptionList = {
      "AntiAliasingQuality"
    },
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_OPTION_Swicth_Close",
      "UI_Option_Dropdown_23",
      "UI_Option_Dropdown_24"
    },
    UnFoldTextM = {
      "UI_OPTION_Swicth_Close",
      "UI_Option_Dropdown_23"
    }
  },
  AntiAliasingMobile = {
    Cache = "AntiAliasingMobile",
    CacheText = "UI_Option_Dropdown_23",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "AntiAliasingMobile",
    GameHide = 2,
    HideOnPC = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 66,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true
  },
  AntiAliasingQuality = {
    Cache = "AntiAliasingQuality",
    CacheText = "UI_OPTION_AntiAliasingQuality",
    ControlType = "UnFold",
    DefaultValue = "2",
    DefaultValueM = "2",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 65,
    SubOptionDefaultValue = {
      0,
      4,
      4
    },
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = T.RT_2
  },
  AutoApprove = {
    Cache = "AutoApprove",
    CacheText = "UI_OPTION_AutoApprove",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    EMCacheName = "AutoAcceptOnlineAction",
    Region = 1,
    SortId = 107,
    SwitchText = T.RT_1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  AutoBackground = {
    Cache = "AutoBackground",
    CacheText = "UI_OPTION_AutoBackground",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    GameHide = 2,
    HideOnPC = true,
    Region = 1,
    SortId = 104,
    SwitchText = T.RT_1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other",
    UCloudHide = true
  },
  AutoBulletJumpCam = {
    Cache = "AutoBulletJumpCam",
    CacheText = "UI_OPTION_AutoBulletJump",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "False",
    EMCacheName = "AutoBulletJump",
    GameHide = 2,
    HideOnPC = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 15,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  AutoFashion = {
    Cache = "AutoFashion",
    CacheText = "UI_OPTION_AutoFashion",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "False",
    EMCacheName = "AutoFashion",
    Region = 1,
    SortId = 99,
    SwitchText = T.RT_1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  AutoJoin = {
    Cache = "AutoJoin",
    CacheText = "UI_OPTION_AutoJoin",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "AutoJoin",
    Region = 1,
    SortId = 105,
    SwitchText = T.RT_1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  AutoRepair = {
    Cache = "AutoRepair",
    CacheText = "UI_OPTION_AutoRepair",
    ControlType = "Click",
    DefaultValue = "UI_GameEvent_Goto",
    DefaultValueM = "UI_GameEvent_Goto",
    GameHide = 2,
    Region = 1,
    SortId = 119,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  BulletJumpCamAdjust = {
    Cache = "BulletJumpCamAdjust",
    CacheText = "UI_OPTION_BulletJumpCamAdjust",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "False",
    EMCacheName = "BulletJumpCamRotate",
    GameHide = 2,
    HideOnPC = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 14,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  BulletJumpCamReset = {
    Cache = "BulletJumpCamReset",
    CacheText = "UI_OPTION_BulletJumpCamReset",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "True",
    EMCacheName = "BulletJumpCamReset",
    GameHide = 2,
    HideOnPC = true,
    MobileSubOptionDefaultValue = {2, 0},
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 22,
    SubOptionDefaultValue = T.RT_3,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  CameraShakeRange = {
    Cache = "CameraShakeRange",
    CacheText = "UI_OPTION_CameraShakeRate",
    ControlType = "Scroll",
    DefaultValue = "10",
    DefaultValueM = "5",
    EMCacheName = "CameraShakeRange",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_4,
    SortId = 11,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  CameraYawFollow = {
    Cache = "CameraYawFollow",
    CacheText = "UI_OPTION_CameraYawFollow",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "True",
    EMCacheName = "CameraYawFollow",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 16,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  ChildPrivacy = {
    Cache = "ChildPrivacy",
    CacheText = "UI_OPTION_ChildPrivacy",
    CheckText = {"49"},
    ControlType = "Click",
    DefaultValue = "UI_Opition_View",
    DefaultValueM = "UI_Opition_View",
    GameHide = 2,
    Region = 1,
    SortId = 114,
    SpecialHide = 1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  ContentPerformance = {
    Cache = "ContentPerformance",
    CacheText = "UI_OPTION_CrowdDensity",
    ControlType = "UnFold",
    DefaultValue = "4",
    DefaultValueM = "4",
    EMCacheName = "ContentPerformance",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 62,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = T.RT_2
  },
  CustomerService = {
    Cache = "CustomerService",
    CacheText = "UI_OPTION_CustomerService",
    ControlType = "Click",
    DefaultValue = "UI_GameEvent_Goto",
    DefaultValueM = "UI_GameEvent_Goto",
    GameHide = 2,
    Region = 1,
    SortId = 110,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other",
    UCloudHide = true
  },
  DLSS = {
    Cache = "DLSS",
    CacheText = "UI_OPTION_DLSS",
    ControlType = "UnFold",
    DefaultValue = "2",
    DefaultValueM = "2",
    EMCacheName = "DLSS",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 47,
    SpecialHide = 99,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_OPTION_Swicth_Close",
      "UI_OPTION_DLSSQuality_1",
      "UI_OPTION_DLSSQuality_3",
      "UI_OPTION_DLSSQuality_2",
      "UI_OPTION_DLSSQuality_5",
      "UI_OPTION_DLSSQuality_6",
      "UI_Option_Dropdown_20"
    }
  },
  DLSSOption = {
    Cache = "DLSSOption",
    CacheText = "UI_OPTION_DLSSOption",
    ControlType = "UnFold",
    DefaultValue = "0",
    DefaultValueM = "0",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 71,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_OPTION_Swicth_Close",
      "UI_OPTION_DLSSQuality_1",
      "UI_OPTION_DLSSOption_Dynamic",
      "UI_OPTION_DLSSOption_2X",
      "UI_OPTION_DLSSOption_3X",
      "UI_OPTION_DLSSOption_4X",
      "UI_OPTION_DLSSOption_5X",
      "UI_OPTION_DLSSOption_6X"
    }
  },
  DamageTextAmount = {
    Cache = "DamageTextAmount",
    CacheText = "UI_OPTION_DamageTextAmount",
    ControlType = "Scroll",
    DefaultValue = "6",
    DefaultValueM = "6",
    EMCacheName = "DamageTextAmount",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_4,
    SortId = 25,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  DamageTextScale = {
    Cache = "DamageTextScale",
    CacheText = "UI_OPTION_DamageTextScale",
    ControlType = "Scroll",
    DefaultValue = "60",
    DefaultValueM = "60",
    EMCacheName = "DamageTextScale",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    ScrollMappingScale = 1,
    ScrollNum = T.RT_5,
    SortId = 26,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  DepthEffect = {
    Cache = "DepthEffect",
    CacheText = "UI_OPTION_DepthEffect",
    ControlType = "UnFold",
    DefaultValue = "2",
    DefaultValueM = "2",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 87,
    SpecialHide = 99,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_OPTION_Swicth_Close",
      "UI_Option_Dropdown_33",
      "UI_Option_Dropdown_34"
    }
  },
  DepthQuality = {
    Cache = "DepthQuality",
    CacheText = "UI_OPTION_DepthQuality",
    ControlType = "UnFold",
    DefaultValue = "4",
    DefaultValueM = "4",
    EMCacheName = "ConsoleVariable",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 88,
    SpecialHide = 99,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = T.RT_2
  },
  DynamicReflection = {
    Cache = "DynamicReflection",
    CacheText = "UI_OPTION_DynamicReflection",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "ConsoleVariable",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 74,
    SpecialHide = 99,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true
  },
  EffectQuality = {
    Cache = "EffectQuality",
    CacheText = "UI_OPTION_EffectQuality",
    ControlType = "UnFold",
    DefaultValue = "4",
    DefaultValueM = "4",
    EMCacheName = "GameUserSettings",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 52,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = T.RT_2,
    UnFoldTextM = {
      "UI_EffectQuality_ExtremelyLow",
      "UI_EffectQuality_Low",
      "UI_EffectQuality_Middle",
      "UI_EffectQuality_High"
    }
  },
  EnableMobileRotation = {
    Cache = "EnableMobileRotation",
    CacheText = "UI_OPTION_EnableMobileRotation",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    EMCacheName = "EnableMobileRotation",
    GameHide = 2,
    HideOnPC = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 21,
    SubOptionList = {
      "BulletJumpCamReset"
    },
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  ExchangeCode = {
    Cache = "ExchangeCode",
    CacheText = "UI_OPTION_ExchangeCode",
    ControlType = "Click",
    DefaultValue = "UI_ActionPoint_Use",
    DefaultValueM = "UI_ActionPoint_Use",
    GameHide = 2,
    Region = 1,
    SortId = 111,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  FSR = {
    Cache = "FSR",
    CacheText = "UI_OPTION_FSR",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    EMCacheName = "FSR",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 48,
    SpecialHide = 99,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true
  },
  FallAttackDirection = {
    Cache = "FallAttackDirection",
    CacheText = "UI_OPTION_FallAtkDirection",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "EnableFallAtkDir",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 20,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  ForceFeedback = {
    Cache = "ForceFeedback",
    CacheText = "UI_OPTION_ForceFeedback",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "ForceFeedback",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_OPTION_Gamepad",
    SortId = 34,
    SubOptionList = {
      "ForceFeedbackScale"
    },
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  ForceFeedbackScale = {
    Cache = "ForceFeedbackScale",
    CacheText = "UI_OPTION_ForceFeedbackScale",
    ControlType = "UnFold",
    DefaultValue = "0",
    DefaultValueM = "0",
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_OPTION_Gamepad",
    SortId = 35,
    SubOptionDefaultValue = {0, 2},
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER",
    UnFoldText = {
      "UI_OPTION_Strong",
      "UI_OPTION_Medium",
      "UI_OPTION_Weak"
    }
  },
  Fps = {
    Cache = "Fps",
    CacheText = "UI_OPTION_Fps",
    ControlType = "UnFold",
    DefaultValue = "3",
    DefaultValueM = "1",
    EMCacheName = "Fps",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 49,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_Option_Dropdown_15",
      "UI_Option_Dropdown_16",
      "UI_Option_Dropdown_17",
      "UI_Option_Dropdown_44",
      "UI_Option_Dropdown_45",
      "UI_Option_Dropdown_46"
    },
    UnFoldTextM = {
      "UI_Option_Dropdown_15",
      "UI_Option_Dropdown_16",
      "UI_Option_Dropdown_17"
    }
  },
  GamePadHorizontalSensitivity = {
    Cache = "GamePadHorizontalSensitivity",
    CacheText = "UI_OPTION_HorizontalSensitivity",
    ControlType = "Scroll",
    DefaultValue = "8",
    DefaultValueM = "10",
    EMCacheName = "GamepadCameraYaw",
    GameHide = 2,
    HideOnKeyboard = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_6,
    SortId = 5,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  GamePadHorizontalSensitivityOnShooting = {
    Cache = "GamePadHorizontalSensitivityOnShooting",
    CacheText = "UI_OPTION_HorizontalSensitivityOnShooting",
    ControlType = "Scroll",
    DefaultValue = "6",
    DefaultValueM = "8",
    EMCacheName = "GamepadCameraYawOnShoot",
    GameHide = 2,
    HideOnKeyboard = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_6,
    SortId = 7,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  GamePadVerticalSensitivity = {
    Cache = "GamePadVerticalSensitivity",
    CacheText = "UI_OPTION_VerticalSensitivity",
    ControlType = "Scroll",
    DefaultValue = "6",
    DefaultValueM = "8",
    EMCacheName = "GamepadCameraPitch",
    GameHide = 2,
    HideOnKeyboard = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_6,
    SortId = 6,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  GamePadVerticalSensitivityOnShooting = {
    Cache = "GamePadVerticalSensitivityOnShooting",
    CacheText = "UI_OPTION_VerticalSensitivityOnShooting",
    ControlType = "Scroll",
    DefaultValue = "4",
    DefaultValueM = "6",
    EMCacheName = "GamepadCameraPitchOnShoot",
    GameHide = 2,
    HideOnKeyboard = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_6,
    SortId = 8,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  GamepadPreset = {
    Cache = "GamepadPreset",
    CacheText = "UI_OPTION_GamepadPreset",
    ControlType = "UnFold",
    DefaultValue = "1",
    DefaultValueM = "1",
    EMCacheName = "GamepadLayout",
    GameHide = 2,
    HideOnPC = true,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_OPTION_Gamepad",
    SortId = 33,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER",
    UnFoldText = {
      "UI_OPTION_Gamepad_Preset1",
      "UI_OPTION_Gamepad_Preset2",
      "UI_OPTION_Gamepad_Preset3",
      "UI_OPTION_Gamepad_Preset4"
    }
  },
  HUDSize = {
    Cache = "HUDSize",
    CacheText = "UI_OPTION_HUDSize",
    ControlType = "UnFold",
    DefaultValue = "3",
    DefaultValueM = "3",
    EMCacheName = "HUDScale",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 55,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = T.RT_7,
    UnFoldTextM = T.RT_7
  },
  HideBackWeapons = {
    Cache = "HideBackWeapons",
    CacheText = "UI_OPTION_HideBackWeapons",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    EMCacheName = "HideBackWeapons",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 27,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  HidePlayer = {
    Cache = "HidePlayer",
    CacheText = "UI_OPTION_HidePlayer",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    EMCacheName = "HidePlayer",
    Region = 1,
    SortId = 106,
    SwitchText = T.RT_1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  HorizontalSensitivity = {
    Cache = "HorizontalSensitivity",
    CacheText = "UI_OPTION_HorizontalSensitivity",
    ControlType = "Scroll",
    DefaultValue = "10",
    DefaultValueM = "10",
    EMCacheName = "CameraYaw",
    GameHide = 2,
    HideOnGamePad = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_6,
    SortId = 1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  HorizontalSensitivityOnShooting = {
    Cache = "HorizontalSensitivityOnShooting",
    CacheText = "UI_OPTION_HorizontalSensitivityOnShooting",
    ControlType = "Scroll",
    DefaultValue = "8",
    DefaultValueM = "8",
    EMCacheName = "CameraYawOnShoot",
    GameHide = 2,
    HideOnGamePad = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_6,
    SortId = 3,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  ImmersionModel = {
    Cache = "ImmersionModel",
    CacheText = "UI_OPTION_ImmersionModel",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "False",
    GameHide = 2,
    HideOnPhone = true,
    Region = 1,
    SortId = 100,
    SwitchText = T.RT_1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  InterfaceMode = {
    Cache = "InterfaceMode",
    CacheText = "UI_OPTION_InterfaceMode",
    ControlType = "UnFold",
    DefaultValue = "3",
    DefaultValueM = "3",
    GameHide = 2,
    HideOnPhone = true,
    Region = 1,
    RegionName = "UI_Option_Area_12",
    SortId = 40,
    SubOptionList = {
      "InterfaceModeResolution"
    },
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_OPTION_InterfaceMode_NoFrame",
      "UI_OPTION_InterfaceMode_Window4:3",
      "UI_OPTION_InterfaceMode_Window16:9",
      "UI_OPTION_InterfaceMode_Window21:9",
      "UI_OPTION_InterfaceMode_Window23:9"
    }
  },
  InterfaceModeResolution = {
    Cache = "InterfaceModeResolution",
    CacheText = "UI_OPTION_Resolution",
    ControlType = "UnFold",
    DefaultValue = "1",
    DefaultValueM = "1",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_12",
    SortId = 41,
    SubOptionDefaultValue = {
      1,
      2,
      2,
      2,
      2
    },
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UnFoldText = {
      "Dynamic_Resolution"
    }
  },
  LeftBulletJumpShow = {
    Cache = "LeftBulletJumpShow",
    CacheText = "UI_OPTION_LeftBulletJumpShow",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    EMCacheName = "HasLeftBulletJump",
    GameHide = 2,
    HideOnGamePad = true,
    HideOnKeyboard = true,
    HideOnPC = true,
    SortId = 37,
    SubOptionDefaultValue = T.RT_3,
    SwitchText = T.RT_8,
    Tag = "Control",
    TagID = 2
  },
  LeftShootShow = {
    Cache = "LeftShootShow",
    CacheText = "UI_OPTION_LeftShootShow\t",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    EMCacheName = "HasLeftShoot",
    GameHide = 2,
    HideOnGamePad = true,
    HideOnKeyboard = true,
    HideOnPC = true,
    SortId = 36,
    SubOptionDefaultValue = T.RT_3,
    SwitchText = T.RT_8,
    Tag = "Control",
    TagID = 2
  },
  LocalWindDetail = {
    Cache = "LocalWindDetail",
    CacheText = "UI_OPTION_LocalWindDetail",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "ConsoleVariable",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 85,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = T.RT_9
  },
  LogOffAccount = {
    Cache = "LogOffAccount",
    CacheText = "UI_OPTION_LogOffAccount",
    CheckText = {"51"},
    ControlType = "Click",
    DefaultValue = "UI_OPTION_Logoff",
    DefaultValueM = "UI_OPTION_Logoff",
    GameHide = 2,
    Region = 1,
    SortId = 117,
    SpecialHide = 1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other",
    UCloudHide = true
  },
  LongPressLockShooting = {
    Cache = "LongPressLockShooting",
    CacheText = "UI_OPTION_LongPressLockShooting",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "True",
    EMCacheName = "LongPressLockShooting",
    GameHide = 2,
    HideOnPC = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 23,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  MaterialFilter = {
    Cache = "MaterialFilter",
    CacheText = "UI_OPTION_MaterialFilter",
    ControlType = "UnFold",
    DefaultValue = "4",
    DefaultValueM = "4",
    EMCacheName = "ConsoleVariable",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 73,
    SpecialHide = 99,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = T.RT_2
  },
  MaterialQuality = {
    Cache = "MaterialQuality",
    CacheText = "UI_OPTION_MaterialQuality",
    ControlType = "UnFold",
    DefaultValue = "4",
    DefaultValueM = "4",
    EMCacheName = "GameUserSettings",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 72,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = T.RT_2
  },
  MobileResolution = {
    Cache = "MobileResolution",
    CacheText = "UI_OPTION_MobileResolution",
    ControlType = "UnFold",
    DefaultValue = "3",
    DefaultValueM = "3",
    GameHide = 2,
    HideOnPC = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 50,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_EffectQuality_ExtremelyLow",
      "UI_EffectQuality_Low",
      "UI_EffectQuality_Middle",
      "UI_EffectQuality_High",
      "UI_EffectQuality_High"
    },
    UnFoldTextM = T.RT_2
  },
  MoveLock = {
    Cache = "MoveLock",
    CacheText = "UI_OPTION_MoveLock",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "VirtualJoystickMoveLock",
    GameHide = 2,
    HideOnPC = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 13,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  MoveModel = {
    Cache = "MoveModel",
    CacheText = "UI_OPTION_MoveModel",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "MoveModel",
    GameHide = 2,
    HideOnPC = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 12,
    SwitchText = {
      "UI_Opition_Fixed",
      "UI_Opition_dynamic"
    },
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  MusicVolume = {
    Cache = "MusicVolume",
    CacheText = "UI_OPTION_MusicVolume",
    ControlType = "Scroll",
    DefaultValue = "10",
    DefaultValueM = "10",
    EMCacheKey = 2,
    EMCacheName = "FMODVolume",
    Region = 2,
    RegionName = "UI_Option_Area_5",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_4,
    SortId = 93,
    Tag = "Voice",
    TagID = 4,
    TagName = "UI_OPTION_AUDIO"
  },
  MuteBackstage = {
    Cache = "MuteBackstage",
    CacheText = "UI_OPTION_MuteBackstage",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "MuteBackstage",
    HideOnPhone = true,
    Region = 1,
    RegionName = "UI_Option_Area_4",
    SortId = 92,
    SwitchText = T.RT_1,
    Tag = "Voice",
    TagID = 4,
    TagName = "UI_OPTION_AUDIO"
  },
  OverallPreset = {
    Cache = "OverallPreset",
    CacheText = "UI_OPTION_OverallPreset",
    ControlType = "UnFold",
    DefaultValue = "4",
    DefaultValueM = "3",
    EMCacheName = "OverallPreset",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_12",
    SortId = 38,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_EffectQuality_ExtremelyLow",
      "UI_EffectQuality_Low",
      "UI_EffectQuality_Middle",
      "UI_EffectQuality_High",
      "UI_EffectQuality_ExtremelyHigh",
      "UI_Option_Area_11"
    }
  },
  PasswordVerifyPerLogin = {
    Cache = "PasswordVerifyPerLogin",
    CacheText = "UI_OPTION_PasswordVerifyPerLogin",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    GameHide = 2,
    MobileSubOptionDefaultValue = T.RT_3,
    Region = 1,
    SortId = 102,
    SubOptionDefaultValue = T.RT_3,
    SwitchText = T.RT_1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  PatchManage = {
    Cache = "PatchManage",
    CacheText = "UI_OPTION_PatchManage",
    ControlType = "Click",
    DefaultValue = "UI_OPTION_Goto",
    DefaultValueM = "UI_OPTION_Goto",
    GameHide = 2,
    HideOnPC = true,
    Region = 1,
    SortId = 103,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other",
    UCloudHide = true
  },
  PlantEnhance = {
    Cache = "PlantEnhance",
    CacheText = "UI_OPTION_PlantEnhance",
    ControlType = "UnFold",
    DefaultValue = "3",
    DefaultValueM = "3",
    EMCacheName = "FoliageQuality",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 79,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UnFoldText = T.RT_2
  },
  PostEffect = {
    Cache = "PostEffect",
    CacheText = "UI_OPTION_PostEffect",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "ConsoleVariable",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 89,
    SpecialHide = 99,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true
  },
  PrivacyPolicy = {
    Cache = "PrivacyPolicy",
    CacheText = "UI_OPTION_PrivacyPolicy",
    ControlType = "Click",
    DefaultValue = "UI_Opition_View",
    DefaultValueM = "UI_Opition_View",
    GameHide = 2,
    Region = 1,
    SortId = 113,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  ProjectionEdgeStaining = {
    Cache = "ProjectionEdgeStaining",
    CacheText = "UI_OPTION_ProjectionEdgeStaining",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "ConsoleVariable",
    GameHide = 2,
    HideOnPC = true,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 75,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true
  },
  QualityMode = {
    Cache = "QualityMode",
    CacheText = "UI_OPTION_QualityMode",
    ControlType = "UnFold",
    DefaultValue = "1",
    DefaultValueM = "1",
    GameHide = 2,
    MobileSubOptionDefaultValue = {
      0,
      2,
      2
    },
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 69,
    SubOptionDefaultValue = {
      0,
      2,
      2,
      2
    },
    SubOptionMultiList = {
      [1] = T.RT_10,
      [2] = T.RT_10,
      [3] = T.RT_11,
      [4] = T.RT_11
    },
    SubOptionMultiListM = {
      [1] = T.RT_12,
      [2] = T.RT_12,
      [3] = T.RT_12
    },
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_OPTION_DLSSQuality_1",
      "UI_OPTION_DLSSQuality_3",
      "UI_OPTION_DLSSQuality_4",
      "UI_OPTION_DLSSQuality_2",
      "UI_OPTION_DLSSQuality_5",
      "UI_OPTION_DLSSQuality_6",
      "UI_Option_Dropdown_20"
    },
    UnFoldTextM = {
      "UI_OPTION_DLSSQuality_4",
      "UI_OPTION_DLSSQuality_3",
      "UI_OPTION_DLSSQuality_2",
      "UI_OPTION_DLSSQuality_5"
    }
  },
  RayTracing = {
    Cache = "RayTracing",
    CacheText = "UI_OPTION_RayTracing",
    ControlType = "UnFold",
    DefaultValue = "1",
    DefaultValueM = "1",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 43,
    SpecialHide = 99,
    SubOptionList = {
      "RayTracingReflect",
      "RayTracingGlobalLight",
      "RayTracingShadow"
    },
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = T.RT_9
  },
  RayTracingGlobalLight = {
    Cache = "RayTracingGlobalLight",
    CacheText = "UI_OPTION_RayTracingGlobalLight",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 45,
    SubOptionDefaultValue = T.RT_13,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true
  },
  RayTracingReflect = {
    Cache = "RayTracingReflect",
    CacheText = "UI_OPTION_RayTracingReflect",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 44,
    SubOptionDefaultValue = T.RT_13,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true
  },
  RayTracingShadow = {
    Cache = "RayTracingShadow",
    CacheText = "UI_OPTION_RayTracingShadow",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 46,
    SubOptionDefaultValue = T.RT_13,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true
  },
  RealtimeSunlight = {
    Cache = "RealtimeSunlight",
    CacheText = "UI_OPTION_RealtimeSunlight",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "RealtimeSunlight",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 78,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY"
  },
  RecordButton = {
    Cache = "RecordButton",
    CacheText = "UI_OPTION_RecordButton",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    EMCacheName = "RecordButton",
    GameHide = 2,
    HideOnPC = true,
    Region = 1,
    SortId = 108,
    SwitchText = T.RT_1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other",
    UCloudHide = true
  },
  RefractiveQuality = {
    Cache = "RefractiveQuality",
    CacheText = "UI_OPTION_RefractiveQuality",
    ControlType = "UnFold",
    DefaultValue = "3",
    DefaultValueM = "3",
    EMCacheName = "ConsoleVariable",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 81,
    SpecialHide = 99,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = T.RT_9
  },
  ReleaseStuck = {
    Cache = "ReleaseStuck",
    CacheText = "UI_OPTION_ReleaseStuck",
    ControlType = "Click",
    DefaultValue = "UI_OPTION_ReleaseStuck_Default",
    DefaultValueM = "UI_OPTION_ReleaseStuck_Default",
    GameHide = 2,
    Region = 1,
    SortId = 109,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  Rendering = {
    Cache = "Rendering",
    CacheText = "UI_OPTION_Rendering",
    ControlType = "UnFold",
    DefaultValue = "2",
    DefaultValueM = "2",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 67,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_Option_Dropdown_8",
      "UI_Option_Dropdown_9",
      "UI_Option_Dropdown_10",
      "UI_Option_Dropdown_11"
    }
  },
  ScreenFilter = {
    Cache = "ScreenFilter",
    CacheText = "UI_OPTION_ScreenFilter",
    ControlType = "UnFold",
    DefaultValue = "3",
    DefaultValueM = "1",
    EMCacheName = "ScreenFilter",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_11",
    SortId = 39,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_Option_Dropdown_41",
      "UI_Option_Dropdown_43",
      "UI_Option_Dropdown_42"
    }
  },
  ScreenQuality = {
    Cache = "ScreenQuality",
    CacheText = "UI_OPTION_ScreenQuality",
    ControlType = "UnFold",
    DefaultValue = "1",
    DefaultValueM = "1",
    EMCacheName = "ScreenQuality",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 90,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_Option_Dropdown_35",
      "UI_Option_Dropdown_36",
      "UI_Option_Dropdown_37"
    }
  },
  SecondaryPassword = {
    Cache = "SecondaryPassword",
    CacheText = "UI_OPTION_SecondaryPassword",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    GameHide = 2,
    Region = 1,
    SortId = 101,
    SubOptionList = {
      "PasswordVerifyPerLogin"
    },
    SwitchText = T.RT_1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  ShadowQuality = {
    Cache = "ShadowQuality",
    CacheText = "UI_OPTION_ShadowQuality",
    ControlType = "UnFold",
    DefaultValue = "4",
    DefaultValueM = "3",
    EMCacheName = "GameUserSettings",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 51,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = T.RT_2
  },
  Sharpen = {
    Cache = "Sharpen",
    CacheText = "UI_OPTION_Sharpen",
    ControlType = "Scroll",
    DefaultValue = "50",
    DefaultValueM = "50",
    EMCacheName = "Sharpen",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    ScrollMappingScale = 100,
    ScrollNum = T.RT_5,
    SortId = 70,
    SubOptionDefaultValue = {
      0,
      50,
      50,
      0
    },
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true
  },
  ShootCameraDistance = {
    Cache = "ShootCameraDistance",
    CacheText = "UI_OPTION_ShootCamDis",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "True",
    EMCacheName = "ShootCameraDistance",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 9,
    SwitchText = {
      "UI_OPTION_Switch_Fixed",
      "UI_OPTION_Switch_Dynamic"
    },
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  ShowBuffEnemy = {
    Cache = "ShowBuffEnemy",
    CacheText = "UI_OPTION_ShowBuffEnemy",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "ShowBuffEnemy",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 31,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  ShowBuffFriend = {
    Cache = "ShowBuffFriend",
    CacheText = "UI_OPTION_ShowBuffFriend",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "ShowBuffFriend",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 32,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  ShowMonsterName = {
    Cache = "ShowMonsterName",
    CacheText = "UI_OPTION_ShowMonsterName",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    EMCacheName = "ShowMonsterName",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 29,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  ShowPlayerName = {
    Cache = "ShowPlayerName",
    CacheText = "UI_OPTION_ShowPlayerName",
    ControlType = "UnFold",
    DefaultValue = "2",
    DefaultValueM = "2",
    EMCacheName = "ShowPlayerName",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 30,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER",
    UnFoldText = {
      "UI_OPTION_Hide",
      "UI_OPTION_RegionOnly",
      "UI_OPTION_Always"
    }
  },
  SkillFaceTo = {
    Cache = "SkillFaceTo",
    CacheText = "UI_OPTION_SkillFaceTo",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "SkillFaceTo",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 17,
    SwitchText = {
      "UI_Opition_ToCharacter",
      "UI_Opition_ToCamera"
    },
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  SkipMVP = {
    Cache = "SkipMVP",
    CacheText = "UI_OPTION_SkipMVP",
    ControlType = "Switch",
    DefaultValue = "False",
    DefaultValueM = "False",
    EMCacheName = "SkipMVP",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 28,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  SoundVolume = {
    Cache = "SoundVolume",
    CacheText = "UI_OPTION_SoundVolume",
    ControlType = "Scroll",
    DefaultValue = "10",
    DefaultValueM = "10",
    EMCacheKey = 1,
    EMCacheName = "FMODVolume",
    Region = 2,
    RegionName = "UI_Option_Area_5",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_4,
    SortId = 95,
    Tag = "Voice",
    TagID = 4,
    TagName = "UI_OPTION_AUDIO"
  },
  SpringArmRate = {
    Cache = "SpringArmRate",
    CacheText = "UI_OPTION_CameraDistance",
    ControlType = "Scroll",
    DefaultValue = "11",
    DefaultValueM = "8",
    EMCacheName = "SpringArmRate",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    ScrollMappingScale = 10,
    ScrollNum = {7, 13},
    SortId = 10,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  SystemLanguage = {
    Cache = "SystemLanguage",
    CacheText = "UI_OPTION_SystemLanguage",
    ControlType = "UnFold",
    DefaultValue = "1",
    DefaultValueM = "1",
    EMCacheName = "SystemLanguage",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_2",
    SortId = 96,
    Tag = "Language",
    TagID = 5,
    TagName = "UI_OPTION_LANGUAGE",
    UCloudHide = true,
    UnFoldText = {
      "UI_Language_Text_CN",
      "UI_Language_Text_EN",
      "UI_Language_Text_JP",
      "UI_Language_Text_KR",
      "UI_Language_Text_TC",
      "UI_Language_Text_FR"
    }
  },
  SystemVoice = {
    Cache = "SystemVoice",
    CacheText = "UI_OPTION_SystemVoice",
    ControlType = "UnFold",
    DefaultValue = "1",
    DefaultValueM = "1",
    EMCacheName = "SystemVoice",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_13",
    SortId = 97,
    Tag = "Language",
    TagID = 5,
    TagName = "UI_OPTION_LANGUAGE",
    UnFoldText = {
      "UI_Language_Voice_CN",
      "UI_Language_Voice_EN",
      "UI_Language_Voice_JP",
      "UI_Language_Voice_KR"
    }
  },
  TeammateEffects = {
    Cache = "TeammateEffects",
    CacheText = "UI_OPTION_TeammateEffects",
    ControlType = "UnFold",
    DefaultValue = "2",
    DefaultValueM = "2",
    EMCacheName = "TeammateEffects",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 61,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_Option_Dropdown_30",
      "UI_Option_Dropdown_31",
      "UI_Option_Dropdown_32"
    }
  },
  TermsOfService = {
    Cache = "TermsOfService",
    CacheText = "UI_OPTION_TermsOfService",
    ControlType = "Click",
    DefaultValue = "UI_Opition_View",
    DefaultValueM = "UI_Opition_View",
    GameHide = 2,
    Region = 1,
    SortId = 112,
    SpecialHide = 2,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  ThirdPartySDK = {
    Cache = "ThirdPartySDK",
    CacheText = "UI_OPTION_ThirdPartySDK",
    CheckText = {"50"},
    ControlType = "Click",
    DefaultValue = "UI_Opition_View",
    DefaultValueM = "UI_Opition_View",
    GameHide = 2,
    Region = 1,
    SortId = 115,
    SpecialHide = 1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  TotalVolume = {
    Cache = "TotalVolume",
    CacheText = "UI_OPTION_TotalVolume",
    ControlType = "Scroll",
    DefaultValue = "10",
    DefaultValueM = "10",
    EMCacheKey = 0,
    EMCacheName = "FMODVolume",
    Region = 1,
    RegionName = "UI_Option_Area_4",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_4,
    SortId = 91,
    Tag = "Voice",
    TagID = 4,
    TagName = "UI_OPTION_AUDIO"
  },
  UpdateOpenLockAim = {
    Cache = "UpdateOpenLockAim",
    CacheText = "UI_OPTION_OpenLockAim",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "IsOpenLockAim",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 19,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  UpscalingMethod = {
    Cache = "UpscalingMethod",
    CacheText = "UI_OPTION_UpscalingMethod",
    ControlType = "UnFold",
    DefaultValue = "2",
    DefaultValueM = "1",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 68,
    SubOptionList = {
      "QualityMode",
      "Sharpen"
    },
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = {
      "UI_OPTION_Swicth_Close",
      "UI_OPTION_DLSS",
      "UI_OPTION_FSR",
      "UI_OPTION_XeSS"
    },
    UnFoldTextM = {
      "UI_OPTION_Swicth_Close",
      "UI_OPTION_MFSR",
      "UI_OPTION_GSR"
    }
  },
  UserCentre = {
    Cache = "UserCentre",
    CacheText = "UI_OPTION_UserCentre",
    CheckText = {"52"},
    ControlType = "Click",
    DefaultValue = "UI_OPTION_Goto",
    DefaultValueM = "UI_OPTION_Goto",
    GameHide = 2,
    Region = 1,
    SortId = 118,
    SpecialHide = 2,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  UserPolicy = {
    Cache = "UserPolicy",
    CacheText = "UI_OPTION_UserPolicy",
    ControlType = "Click",
    DefaultValue = "UI_Opition_View",
    DefaultValueM = "UI_Opition_View",
    GameHide = 2,
    Region = 1,
    SortId = 116,
    SpecialHide = 1,
    Tag = "Other",
    TagID = 6,
    TagName = "UI_OPTION_Other"
  },
  VerticalSensitivity = {
    Cache = "VerticalSensitivity",
    CacheText = "UI_OPTION_VerticalSensitivity",
    ControlType = "Scroll",
    DefaultValue = "8",
    DefaultValueM = "8",
    EMCacheName = "CameraPitch",
    GameHide = 2,
    HideOnGamePad = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_6,
    SortId = 2,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  VerticalSensitivityOnShooting = {
    Cache = "VerticalSensitivityOnShooting",
    CacheText = "UI_OPTION_VerticalSensitivityOnShooting",
    ControlType = "Scroll",
    DefaultValue = "6",
    DefaultValueM = "6",
    EMCacheName = "CameraPitchOnShoot",
    GameHide = 2,
    HideOnGamePad = true,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_6,
    SortId = 4,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  VerticalSync = {
    Cache = "VerticalSync",
    CacheText = "UI_OPTION_VerticalSync",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 56,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true
  },
  VoiceGuide = {
    Cache = "VoiceGuide",
    CacheText = "UI_OPTION_VoiceGuide",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "VoiceGuide",
    GameHide = 2,
    Region = 1,
    RegionName = "UI_Option_Area_1",
    SortId = 24,
    SwitchText = T.RT_1,
    Tag = "Control",
    TagID = 2,
    TagName = "UI_OPTION_CONTROLLER"
  },
  VoiceResource = {
    Cache = "VoiceResource",
    CacheText = "UI_OPTION_VoiceResource",
    ControlType = "Click",
    DefaultValue = "UI_Opition_View",
    DefaultValueM = "UI_Opition_View",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_13",
    SortId = 98,
    Tag = "Language",
    TagID = 5,
    TagName = "UI_OPTION_LANGUAGE"
  },
  VoiceVolume = {
    Cache = "VoiceVolume",
    CacheText = "UI_OPTION_VoiceVolume",
    ControlType = "Scroll",
    DefaultValue = "10",
    DefaultValueM = "10",
    EMCacheKey = 3,
    EMCacheName = "FMODVolume",
    Region = 2,
    RegionName = "UI_Option_Area_5",
    ScrollMappingScale = 10,
    ScrollNum = T.RT_4,
    SortId = 94,
    Tag = "Voice",
    TagID = 4,
    TagName = "UI_OPTION_AUDIO"
  },
  VolumetricLight = {
    Cache = "VolumetricLight",
    CacheText = "UI_OPTION_VolumetricLight",
    ControlType = "Switch",
    DefaultValue = "True",
    DefaultValueM = "True",
    EMCacheName = "ConsoleVariable",
    GameHide = 2,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 83,
    SpecialHide = 99,
    SwitchText = T.RT_1,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UCloudHide = true,
    UnFoldText = T.RT_9
  },
  WaterQuality = {
    Cache = "WaterQuality",
    CacheText = "UI_OPTION_WaterQuality",
    ControlType = "UnFold",
    DefaultValue = "3",
    DefaultValueM = "3",
    EMCacheName = "WaterQuality",
    GameHide = 2,
    HideOnPhone = true,
    Region = 2,
    RegionName = "UI_Option_Area_11",
    SortId = 80,
    Tag = "View",
    TagID = 3,
    TagName = "UI_OPTION_DISPLAY",
    UnFoldText = T.RT_2
  }
})
