return {
  storyName = "Home",
  storyDescription = "",
  lineData = {
    {
      startStory = "170122471968836190",
      startPort = "StoryStart",
      endStory = "170122472249236373",
      endPort = "In"
    },
    {
      startStory = "170122472249236373",
      startPort = "Success",
      endStory = "170122471968836193",
      endPort = "StoryEnd"
    }
  },
  storyNodeData = {
    ["170122471968836190"] = {
      isStoryNode = true,
      key = "170122471968836190",
      type = "StoryStartNode",
      name = "StoryStart",
      pos = {x = 800, y = 300},
      propsData = {QuestChainId = 0},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["170122471968836193"] = {
      isStoryNode = true,
      key = "170122471968836193",
      type = "StoryEndNode",
      name = "StoryEnd",
      pos = {x = 2800, y = 300},
      propsData = {},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["170122472249236373"] = {
      isStoryNode = true,
      key = "170122472249236373",
      type = "StoryNode",
      name = "任务节点",
      pos = {x = 1146.6806895460923, y = 311.3695286481666},
      propsData = {
        QuestId = 0,
        QuestDescriptionComment = "",
        QuestDescription = "",
        QuestDeatil = "",
        TaskRegionReName = "",
        TaskSubRegionReName = "",
        RecommendLevel = -1,
        bIsStartQuest = false,
        bIsEndQuest = false,
        bIsNotifyGameMode = true,
        bIsStartChapter = false,
        bIsEndChapter = false,
        bIsShowOnComplete = true,
        bIsPlayBlackScreenOnComplete = false,
        bIsPlayBlackScreenOnFail = false,
        bIsDynamicEvent = false,
        ResurgencePoint = "",
        bUseQuestCoordinate = false,
        bDeadTriggerQuestFail = false,
        IsFairyLand = false,
        SubRegionId = 0,
        SubRegionIdList = {},
        StoryGuideType = "Point",
        StoryGuidePointName = "",
        JumpId = 0
      },
      questNodeData = {
        lineData = {
          {
            startQuest = "170122472789036886",
            startPort = "Out",
            endQuest = "170123937762239131",
            endPort = "In"
          },
          {
            startQuest = "170298365927930286",
            startPort = "Out",
            endQuest = "1715860845944829",
            endPort = "In"
          },
          {
            startQuest = "1715860845944829",
            startPort = "Out",
            endQuest = "17158615106222631",
            endPort = "In"
          },
          {
            startQuest = "1753691161995337094",
            startPort = "Out",
            endQuest = "1753691161995337095",
            endPort = "In"
          },
          {
            startQuest = "1753691161995337095",
            startPort = "Out",
            endQuest = "17466059408653639",
            endPort = "In"
          },
          {
            startQuest = "1753696537679334897",
            startPort = "Out",
            endQuest = "1753691161995337094",
            endPort = "In"
          },
          {
            startQuest = "17158615106222631",
            startPort = "Out",
            endQuest = "1754467797178332009",
            endPort = "In"
          },
          {
            startQuest = "1754467797178332009",
            startPort = "Out",
            endQuest = "17544679954711647272",
            endPort = "In"
          },
          {
            startQuest = "17466059408653639",
            startPort = "Out",
            endQuest = "170122472249236376",
            endPort = "Success"
          },
          {
            startQuest = "17544679954711647272",
            startPort = "Out",
            endQuest = "1753696537679334897",
            endPort = "In"
          },
          {
            startQuest = "170123937762239131",
            startPort = "Out",
            endQuest = "175447988391310190294",
            endPort = "In"
          },
          {
            startQuest = "175447988391310190294",
            startPort = "Out",
            endQuest = "170298365927930286",
            endPort = "In"
          },
          {
            startQuest = "170122472249236374",
            startPort = "QuestStart",
            endQuest = "17581023911991472",
            endPort = "In"
          },
          {
            startQuest = "17581023911991472",
            startPort = "Out",
            endQuest = "170122472789036886",
            endPort = "In"
          }
        },
        nodeData = {
          ["170122472249236374"] = {
            key = "170122472249236374",
            type = "QuestStartNode",
            name = "QuestStart",
            pos = {x = 525.8620713695476, y = 286.20689667268164},
            propsData = {ModeType = 0}
          },
          ["170122472249236376"] = {
            key = "170122472249236376",
            type = "QuestSuccessNode",
            name = "QuestSuccess",
            pos = {x = 2394.401261204468, y = 785.1874750372942},
            propsData = {ModeType = 0}
          },
          ["170122472249236378"] = {
            key = "170122472249236378",
            type = "QuestFailNode",
            name = "QuestFail",
            pos = {x = 3255.999997680664, y = 801.9999994812011},
            propsData = {}
          },
          ["170122472789036883"] = {
            key = "170122472789036883",
            type = "ShowGuideButtonNode",
            name = "物品列表",
            pos = {x = 1059.7655557940839, y = 92.68795315149694},
            propsData = {
              ShowEnable = true,
              MessageId = 300006,
              MessageNote = "点击刚才获得的新武器。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMainNew.TileView_Select_Role:2",
              UICompName = "Bg01",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Right",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["170122472789036884"] = {
            key = "170122472789036884",
            type = "ShowGuideButtonNode",
            name = "动态界面按钮",
            pos = {x = 1627.2661736170407, y = 107.60277595987304},
            propsData = {
              ShowEnable = true,
              MessageId = 300009,
              MessageNote = "点击“+”号，打开升级弹窗。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMainNew.SubUI_Panel:2.Btn_Lvup",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Left",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["170122472789036885"] = {
            key = "170122472789036885",
            type = "ShowGuideButtonNode",
            name = "界面内弹窗",
            pos = {x = 1904.1814996702974, y = 106.41913201760883},
            propsData = {
              ShowEnable = true,
              MessageId = 300010,
              MessageNote = "点击“+”号，可以提升升级的目标等级",
              DelayTime = 0,
              IsForceClick = false,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "CommonDialog.VB_Node:1.Btn_Add",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Right",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["170122472789036886"] = {
            key = "170122472789036886",
            type = "ShowGuideTextNode",
            name = "Text显示信息",
            pos = {x = 1120.2584508504588, y = 298.3390285892075},
            propsData = {
              MessageId = 300501,
              MessageNote = "这里是铸造台，消耗一定的材料可以锻造各种武器、合成各种有用的道具。",
              IsTimePause = false,
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = true,
              GuideManPosEnum = "DownLeft",
              GuidemanHead = "Tiejiang_Idle"
            }
          },
          ["170122472789036887"] = {
            key = "170122472789036887",
            type = "ShowGuideButtonNode",
            name = "区域右上角UI",
            pos = {x = 1314.217425209433, y = -75.14943294925408},
            propsData = {
              ShowEnable = true,
              MessageId = 300002,
              MessageNote = "点击<H>“整备”</>进入整备系统。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "BattleMain.ListView:1",
              UICompName = "Btn_top",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["170122472789036888"] = {
            key = "170122472789036888",
            type = "ShowGuideButtonNode",
            name = "UI内ListView",
            pos = {x = 1617.8071687991767, y = -62.713535513357016},
            propsData = {
              ShowEnable = true,
              MessageId = 300003,
              MessageNote = "点击“近战武器”页签，进行近战武器配置。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMainNew.ListView_Tab:3",
              UICompName = "Text_1",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Right",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["170122472789036889"] = {
            key = "170122472789036889",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1371.5194588080178, y = 113.34375891635115},
            propsData = {
              ShowEnable = true,
              MessageId = 300005,
              MessageNote = "点击“替换”，进行近战武器的替换。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMainNew.Btn_Confirm_1",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Up",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["170123937762239131"] = {
            key = "170123937762239131",
            type = "ShowGuideButtonNode",
            name = "普通页签",
            pos = {x = 1425.4442746452037, y = 296.9123205054322},
            propsData = {
              ShowEnable = true,
              MessageId = 300502,
              MessageNote = "铸造前需要先获得设计稿，并收集齐铸造所需要的材料。",
              DelayTime = 0,
              IsForceClick = false,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ForgeMain.ForgeContent:1",
              UICompName = "Switch",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["170123953021240549"] = {
            key = "170123953021240549",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1936.9964113973404, y = -49.04879060567902},
            propsData = {
              ShowEnable = true,
              MessageId = 300503,
              MessageNote = "点击“开始铸造”，消耗一张设计稿及对应的铸造材料，即可开始铸造。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ForgeMain.ForgeContent:1.BtnStart",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Up",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["170298365927930286"] = {
            key = "170298365927930286",
            type = "ShowGuideTextNode",
            name = "Text显示信息",
            pos = {x = 2089.429751724259, y = 302.62115539452554},
            propsData = {
              MessageId = 300503,
              MessageNote = "铸造需要一定的时间，当倒计时结束后，铸造就完成了，可以来铸造台领取刚刚铸造好的武器或者道具。",
              IsTimePause = false,
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              GuideManPosEnum = "DownLeft",
              GuidemanHead = "Tiejiang_Idle"
            }
          },
          ["1715860845944829"] = {
            key = "1715860845944829",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1181.291666310628, y = 557.1096487667687},
            propsData = {
              ShowEnable = true,
              MessageId = 300504,
              MessageNote = "点击“开始铸造”。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "ForgeMain.ForgeContent:1.BtnStart",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17158610702141724"] = {
            key = "17158610702141724",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 2616.7916632283527, y = 1152.1096486446986},
            propsData = {
              ShowEnable = true,
              MessageId = 300505,
              MessageNote = "点击铸造中",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "ForgeMain.Tab.EMScrollBox_TabItem:2",
              UICompName = "Btn",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17158615106222631"] = {
            key = "17158615106222631",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1525.263888380262, y = 588.6929819780318},
            propsData = {
              ShowEnable = true,
              MessageId = 300506,
              MessageNote = "点击“确定”。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "CommonDialog.Pos_Btn:1.Btn_Yes",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["1742378369114779"] = {
            key = "1742378369114779",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 2813.9595856535657, y = 1213.1111062253187},
            propsData = {
              ShowEnable = true,
              MessageId = 300506,
              MessageNote = "点击“确定”。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "ForgeMain.Forging_Path_PC.ItemDetails.Forging.BtnStart",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Up",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17466059408653639"] = {
            key = "17466059408653639",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 2105.4972386962772, y = 779.4294000832009},
            propsData = {
              ShowEnable = true,
              MessageId = 300507,
              MessageNote = "领取",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "ForgeMain.Btn_Receive",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Up",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17535176744841065"] = {
            key = "17535176744841065",
            type = "ShowGuideButtonNode",
            name = "Button显示/隐藏信息",
            pos = {x = 1472.8484826925453, y = 1097.757574580309},
            propsData = {
              ShowEnable = true,
              MessageId = 300509,
              MessageNote = "打开锻造图鉴",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "ForgeMain.Entrance_Compendium",
              UICompName = "Btn_Click",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Right",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17535177522971447"] = {
            key = "17535177522971447",
            type = "ShowGuideButtonNode",
            name = "Button显示/隐藏信息",
            pos = {x = 1116.9090938065708, y = 1109.030298893233},
            propsData = {
              ShowEnable = true,
              MessageId = 300508,
              MessageNote = "关闭获得物品界面",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "GetItemPage",
              UICompName = "Button_Close",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Up",
              MessageLocOffset = {X = 0, Y = 150}
            }
          },
          ["1753691161995337094"] = {
            key = "1753691161995337094",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1458.250528062712, y = 766.8610603646175},
            propsData = {
              ShowEnable = true,
              MessageId = 300504,
              MessageNote = "点击“开始铸造”。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "ForgeMain.ForgeContent:2.BtnStart",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["1753691161995337095"] = {
            key = "1753691161995337095",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1804.2227422995015, y = 781.0158235262052},
            propsData = {
              ShowEnable = true,
              MessageId = 300504,
              MessageNote = "点击“确定”。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "CommonDialog.Pos_Btn:1.Btn_Yes",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["1753696537679334897"] = {
            key = "1753696537679334897",
            type = "ShowGuideTextNode",
            name = "Text显示信息",
            pos = {x = 1120.1616242719576, y = 762.2087644498687},
            propsData = {
              MessageId = 300510,
              MessageNote = "",
              IsTimePause = true,
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              GuideManPosEnum = "DownLeft",
              GuidemanHead = "Bai_Idle"
            }
          },
          ["1754467797178332009"] = {
            key = "1754467797178332009",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1786.2260000818565, y = 576.8998613983943},
            propsData = {
              ShowEnable = true,
              MessageId = 300511,
              MessageNote = "点击加速铸造",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "ForgeMain.ForgeContent:1.BtnStart",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17544679954711647272"] = {
            key = "17544679954711647272",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 2190.6877010375865, y = 596.0006457957368},
            propsData = {
              ShowEnable = true,
              MessageId = 300506,
              MessageNote = "点击“确定”。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "CommonDialog.Pos_Btn:1.Btn_Yes",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["175447268088010188152"] = {
            key = "175447268088010188152",
            type = "ShowGuideToastNode",
            name = "Toast显示/隐藏信息",
            pos = {x = 2888.6876979654835, y = 810.0006454702159},
            propsData = {
              ShowEnable = true,
              MessageId = 0,
              MessageNote = "",
              LastTime = 10,
              Style = "Normal"
            }
          },
          ["175447988391310190294"] = {
            key = "175447988391310190294",
            type = "ShowGuideButtonNode",
            name = "Button显示/隐藏信息",
            pos = {x = 1746.6877032755426, y = 310.00064725040806},
            propsData = {
              ShowEnable = true,
              MessageId = 300509,
              MessageNote = "打开锻造图鉴",
              DelayTime = 0,
              IsForceClick = false,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = true,
              HighLightUIPath = "ForgeMain.Entrance_Compendium",
              UICompName = "Btn_Click",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Right",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17581023911991472"] = {
            key = "17581023911991472",
            type = "MSDKUploadNode",
            name = "海外市场SDK埋点上报",
            pos = {x = 830.5517285528799, y = 303.17241637857},
            propsData = {
              EventName = "forge_training"
            }
          }
        },
        commentData = {}
      }
    }
  },
  commentData = {}
}
