return {
  storyName = "Home",
  storyDescription = "",
  lineData = {
    {
      startStory = "17164494178129363",
      startPort = "StoryStart",
      endStory = "17164494215989477",
      endPort = "In"
    },
    {
      startStory = "17164494215989477",
      startPort = "Success",
      endStory = "17164494178129366",
      endPort = "StoryEnd"
    }
  },
  storyNodeData = {
    ["17164494178129363"] = {
      isStoryNode = true,
      key = "17164494178129363",
      type = "StoryStartNode",
      name = "StoryStart",
      pos = {x = 800, y = 300},
      propsData = {QuestChainId = 0},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["17164494178129366"] = {
      isStoryNode = true,
      key = "17164494178129366",
      type = "StoryEndNode",
      name = "StoryEnd",
      pos = {x = 1793.3333333333333, y = 338.3333333333333},
      propsData = {},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["17164494215989477"] = {
      isStoryNode = true,
      key = "17164494215989477",
      type = "StoryNode",
      name = "任务节点",
      pos = {x = 1334.5474481658691, y = 315.31889258719883},
      propsData = {
        QuestId = 0,
        QuestDescriptionComment = "",
        QuestDescription = "",
        QuestDeatil = "",
        TaskRegionReName = "",
        TaskSubRegionReName = "",
        RecommendLevel = -1,
        bIsStartQuest = false,
        bIsEndQuest = false,
        bIsNotifyGameMode = true,
        bIsStartChapter = false,
        bIsEndChapter = false,
        bIsShowOnComplete = true,
        bIsPlayBlackScreenOnComplete = false,
        bIsPlayBlackScreenOnFail = false,
        bIsDynamicEvent = false,
        ResurgencePoint = "",
        bUseQuestCoordinate = false,
        bDeadTriggerQuestFail = false,
        IsFairyLand = false,
        SubRegionId = 0,
        SubRegionIdList = {},
        StoryGuideType = "Point",
        StoryGuidePointName = "",
        JumpId = 0
      },
      questNodeData = {
        lineData = {
          {
            startQuest = "171644946440311112",
            startPort = "Out",
            endQuest = "171644946440211110",
            endPort = "In"
          },
          {
            startQuest = "1716450887463113859",
            startPort = "Out",
            endQuest = "1716452598504117487",
            endPort = "In"
          },
          {
            startQuest = "1716452598504117487",
            startPort = "Out",
            endQuest = "1716452798027118936",
            endPort = "In"
          },
          {
            startQuest = "1716452798027118936",
            startPort = "Out",
            endQuest = "17164494215989481",
            endPort = "Success"
          },
          {
            startQuest = "1720337760857436980",
            startPort = "PC",
            endQuest = "171644946440311112",
            endPort = "In"
          },
          {
            startQuest = "1720337760857436980",
            startPort = "Mobile",
            endQuest = "1720337768097437238",
            endPort = "In"
          },
          {
            startQuest = "1720337768097437238",
            startPort = "Out",
            endQuest = "171644946440211110",
            endPort = "In"
          },
          {
            startQuest = "172839390165411378",
            startPort = "PC",
            endQuest = "1716450887463113859",
            endPort = "In"
          },
          {
            startQuest = "172839390165411378",
            startPort = "Mobile",
            endQuest = "172839392357012200",
            endPort = "In"
          },
          {
            startQuest = "172839392357012200",
            startPort = "Out",
            endQuest = "1716452598504117487",
            endPort = "In"
          },
          {
            startQuest = "17478832681491728375",
            startPort = "Out",
            endQuest = "17478832681491728376",
            endPort = "In"
          },
          {
            startQuest = "17164494215989478",
            startPort = "QuestStart",
            endQuest = "171644946440211111",
            endPort = "In"
          },
          {
            startQuest = "17567297128609251266",
            startPort = "Out",
            endQuest = "172839390165411378",
            endPort = "Input"
          },
          {
            startQuest = "171644946440211111",
            startPort = "Out",
            endQuest = "175678051427918188869",
            endPort = "In"
          },
          {
            startQuest = "175678051427918188869",
            startPort = "Out",
            endQuest = "17567297128609251266",
            endPort = "In"
          }
        },
        nodeData = {
          ["17164494215989478"] = {
            key = "17164494215989478",
            type = "QuestStartNode",
            name = "QuestStart",
            pos = {x = 539.0909084756353, y = 91.96481150785098},
            propsData = {ModeType = 0}
          },
          ["17164494215989481"] = {
            key = "17164494215989481",
            type = "QuestSuccessNode",
            name = "QuestSuccess",
            pos = {x = 2249.090909090909, y = 467.72727272727275},
            propsData = {ModeType = 0}
          },
          ["17164494215989484"] = {
            key = "17164494215989484",
            type = "QuestFailNode",
            name = "QuestFail",
            pos = {x = 2800, y = 700},
            propsData = {}
          },
          ["17164494261649729"] = {
            key = "17164494261649729",
            type = "ShowGuideButtonNode",
            name = "物品列表",
            pos = {x = 995.5030179712796, y = -536.7793356116712},
            propsData = {
              ShowEnable = true,
              MessageId = 300006,
              MessageNote = "点击刚才获得的新武器。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMainNew.TileView_Select_Role:2",
              UICompName = "Bg01",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Right",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17164494261649730"] = {
            key = "17164494261649730",
            type = "ShowGuideButtonNode",
            name = "动态界面按钮",
            pos = {x = 1561.6992879681495, y = -520.560164977208},
            propsData = {
              ShowEnable = true,
              MessageId = 300009,
              MessageNote = "点击“+”号，打开升级弹窗。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMainNew.SubUI_Panel:2.Btn_Lvup",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Left",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17164494261649731"] = {
            key = "17164494261649731",
            type = "ShowGuideButtonNode",
            name = "界面内弹窗",
            pos = {x = 1838.6146140214064, y = -523.0481567455593},
            propsData = {
              ShowEnable = true,
              MessageId = 300010,
              MessageNote = "点击“+”号，可以提升升级的目标等级",
              DelayTime = 0,
              IsForceClick = false,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "CommonDialog.VB_Node:1.Btn_Add",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Right",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17164494261649732"] = {
            key = "17164494261649732",
            type = "ShowGuideTextNode",
            name = "Text显示信息",
            pos = {x = 974.2915652015674, y = -701.7739123478736},
            propsData = {
              MessageId = 300004,
              MessageNote = "在近战武器配置界面中，可以查看近战武器的属性、为近战武器升级、替换其他近战武器等。",
              IsTimePause = false,
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              GuideManPosEnum = "DownLeft",
              GuidemanHead = "Bai_Idle"
            }
          },
          ["17164494261649733"] = {
            key = "17164494261649733",
            type = "ShowGuideButtonNode",
            name = "区域右上角UI",
            pos = {x = 1248.650539560542, y = -703.3123738863352},
            propsData = {
              ShowEnable = true,
              MessageId = 300002,
              MessageNote = "点击<H>“整备”</>进入整备系统。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "BattleMain.ListView:1",
              UICompName = "Btn_top",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17164494261649734"] = {
            key = "17164494261649734",
            type = "ShowGuideButtonNode",
            name = "UI内ListView",
            pos = {x = 1552.2402831502857, y = -690.8764764504381},
            propsData = {
              ShowEnable = true,
              MessageId = 300003,
              MessageNote = "点击“近战武器”页签，进行近战武器配置。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMainNew.ListView_Tab:3",
              UICompName = "Text_1",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Right",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17164494261649735"] = {
            key = "17164494261649735",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1290.352573159127, y = -531.6191820207299},
            propsData = {
              ShowEnable = true,
              MessageId = 300005,
              MessageNote = "点击“替换”，进行近战武器的替换。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMainNew.Btn_Confirm_1",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Up",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["171644946440211110"] = {
            key = "171644946440211110",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1785.6775282908804, y = -356.17843363675047},
            propsData = {
              ShowEnable = true,
              MessageId = 301303,
              MessageNote = "点击“魔之楔”，进行魔之楔配置。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMain.Panel_SubUI:1",
              UICompName = "Btn_Mod",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Up",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["171644946440211111"] = {
            key = "171644946440211111",
            type = "ShowGuideTextNode",
            name = "Text显示信息",
            pos = {x = 947.5079654758666, y = 76.53378136669058},
            propsData = {
              MessageId = 301301,
              MessageNote = "提升魔之楔的等级，可以进一步增强骸和武器的力量。",
              IsTimePause = true,
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = true,
              GuideManPosEnum = "DownLeft",
              GuidemanHead = "Bai_Idle"
            }
          },
          ["171644946440311112"] = {
            key = "171644946440311112",
            type = "ShowGuideButtonNode",
            name = "区域右上角UI",
            pos = {x = 1465.3023604527061, y = -393.697658895197},
            propsData = {
              ShowEnable = true,
              MessageId = 301302,
              MessageNote = "点击<H>“整备”</>进入整备系统。",
              DelayTime = 0.5,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = false,
              HighLightUIPath = "BattleMain.ListView:1",
              UICompName = "Btn_top",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Left",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["1716450887463113859"] = {
            key = "1716450887463113859",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1118.7570022475393, y = 464.3578811449688},
            propsData = {
              ShowEnable = true,
              MessageId = 301305,
              MessageNote = "点击“魔之楔升级”。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMod.Tip_Mod.Btn02_Mod",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "UpLeft",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["1716452598504117487"] = {
            key = "1716452598504117487",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1432.160834689607, y = 465.7462692274743},
            propsData = {
              ShowEnable = true,
              MessageId = 301306,
              MessageNote = "升级魔之楔，可以带来极大的能力提升。",
              DelayTime = 0,
              IsForceClick = false,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryModIntensify.VB_Node:1",
              UICompName = "Btn_Add",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Up",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["1716452798027118936"] = {
            key = "1716452798027118936",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1774.107804386577, y = 460.29172377292895},
            propsData = {
              ShowEnable = true,
              MessageId = 301307,
              MessageNote = "但是魔之楔的升级，也会造成耐受值消耗增加。需要注意装配魔之楔的耐受值不能超过角色和武器的耐受值上限。",
              DelayTime = 0,
              IsForceClick = false,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryModIntensify.VB_Node:1",
              UICompName = "List_Atrr",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Up",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["1716453378083120642"] = {
            key = "1716453378083120642",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 2100.3588598326787, y = 750.5056275162447},
            propsData = {
              ShowEnable = true,
              MessageId = 300608,
              MessageNote = "点击配置武器。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryBattleMenu.List:1.ItemDetails_MenuAnchor.CommonItemDetails.Btn01",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Up",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["1720337760857436980"] = {
            key = "1720337760857436980",
            type = "PlatformJudgmentNode",
            name = "PC/手机平台判断",
            pos = {x = 1171.8433257576903, y = -358.43094532765963},
            propsData = {}
          },
          ["1720337768097437238"] = {
            key = "1720337768097437238",
            type = "ShowGuideButtonNode",
            name = "区域右上角UI",
            pos = {x = 1494.3437115006209, y = -234.0236298204869},
            propsData = {
              ShowEnable = true,
              MessageId = 301302,
              MessageNote = "点击<H>“整备”</>进入整备系统。",
              DelayTime = 0.5,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = true,
              IsShowCursor = false,
              HighLightUIPath = "BattleMain.ListView:1",
              UICompName = "Btn_top",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = false,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Right",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["172839390165411378"] = {
            key = "172839390165411378",
            type = "PlatformJudgmentNode",
            name = "PC/手机平台判断",
            pos = {x = 736.6396171637696, y = 523.3192825816502},
            propsData = {}
          },
          ["172839392357012200"] = {
            key = "172839392357012200",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1109.8869899988292, y = 602.6951357992749},
            propsData = {
              ShowEnable = true,
              MessageId = 301305,
              MessageNote = "点击“魔之楔升级”。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMod.Tip_Mod.Btn02_Mod",
              UICompName = "Button_Area",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "UpLeft",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17478832681491728375"] = {
            key = "17478832681491728375",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 869.9878908501199, y = 726.8075871496923},
            propsData = {
              ShowEnable = true,
              MessageId = 301306,
              MessageNote = "升级魔之楔，可以带来极大的能力提升。",
              DelayTime = 0,
              IsForceClick = false,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryModIntensify.VB_Node:1",
              UICompName = "Btn_Add",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Up",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17478832681491728376"] = {
            key = "17478832681491728376",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1206.4803150925445, y = 721.353041695147},
            propsData = {
              ShowEnable = true,
              MessageId = 301307,
              MessageNote = "但是魔之楔的升级，也会造成耐受值消耗增加。需要注意装配魔之楔的耐受值不能超过角色和武器的耐受值上限。",
              DelayTime = 0,
              IsForceClick = false,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryModIntensify.VB_Node:1",
              UICompName = "List_Atrr",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = false,
              UICompSizeOffset = {X = 0, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Up",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["17567297128609251266"] = {
            key = "17567297128609251266",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 2145.161297765408, y = 112.25806658027328},
            propsData = {
              ShowEnable = true,
              MessageId = 301304,
              MessageNote = "点击魔之楔。",
              DelayTime = 0,
              IsForceClick = true,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMod.Mod_1",
              UICompName = "ItemDetails_MenuAnchor",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = true,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 80, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["175673003420011166865"] = {
            key = "175673003420011166865",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 2607.8064445273317, y = -592.9032188796602},
            propsData = {
              ShowEnable = true,
              MessageId = 301304,
              MessageNote = "点击魔之楔（自动）",
              DelayTime = 0,
              IsForceClick = false,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMod.Mod_1",
              UICompName = "ItemDetails_MenuAnchor",
              GamePadWidgetName = "",
              IsAutoClick = true,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 80, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["175677934831514998912"] = {
            key = "175677934831514998912",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 2214, y = -540},
            propsData = {
              ShowEnable = true,
              MessageId = 301304,
              MessageNote = "点击魔之楔（自动）",
              DelayTime = 0,
              IsForceClick = false,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMod.Mod_1",
              UICompName = "ItemDetails_MenuAnchor",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = true,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 80, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          },
          ["175678051427918188869"] = {
            key = "175678051427918188869",
            type = "ShowGuideButtonNode",
            name = "普通按钮",
            pos = {x = 1462, y = 80},
            propsData = {
              ShowEnable = true,
              MessageId = 301304,
              MessageNote = "点击魔之楔。",
              DelayTime = 0,
              IsForceClick = false,
              IsControlPlayer = false,
              IsTimePause = false,
              IsShowCursor = true,
              HighLightUIPath = "ArmoryMod.Mod_1",
              UICompName = "ItemDetails_MenuAnchor",
              GamePadWidgetName = "",
              IsAutoClick = false,
              IsAutoClickByGamepad = false,
              UIShape = "Square",
              IsResetPlayer = false,
              IsForbidInAnim = true,
              IsForbidOutAnim = true,
              UICompSizeOffset = {X = 80, Y = 0},
              UICompLocOffset = {X = 0, Y = 0},
              MessageParentLoc = "HighLightUI",
              MessageLoc = "Down",
              MessageLocOffset = {X = 0, Y = 0}
            }
          }
        },
        commentData = {}
      }
    }
  },
  commentData = {}
}
