local T = {}
T.RT_1 = {
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NS_Zhangyu_Skill02_Brust_xuli.NS_Zhangyu_Skill02_Brust_xuli",
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NS_Zhangyu_Skill02_Eyes.NS_Zhangyu_Skill02_Eyes",
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NS_Zhangyu_Skill02_Brust_baofa.NS_Zhangyu_Skill02_Brust_baofa",
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NS_Zhangyu_Skill01_Pre.NS_Zhangyu_Skill01_Pre",
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NS_Zhangyu_Replication.NS_Zhangyu_Replication",
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NS_Zhangyu_Tentacle_Water_Batch.NS_Zhangyu_Tentacle_Water_Batch",
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NS_Zhangyu_Skill01_Buff_Batch.NS_Zhangyu_Skill01_Buff_Batch",
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NDC_Zhangyu_Tentacle_Birth.NDC_Zhangyu_Tentacle_Birth",
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NS_Zhangyu_Skill02__new_Background.NS_Zhangyu_Skill02__new_Background",
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NS_zhangyu_skill02_pingmu_rongjie.NS_zhangyu_skill02_pingmu_rongjie",
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NS_Zhangyu_Hit.NS_Zhangyu_Hit",
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NS_Zhangyu_Skill02__new_xingxing.NS_Zhangyu_Skill02__new_xingxing"
}
T.RT_2 = {
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Nvzhu_Skill02_LingYu.NS_Nvzhu_Skill02_LingYu",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_nanzhu_skill01_chaungsheng.NS_nanzhu_skill01_chaungsheng",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_nanzhu_skill01_hit.NS_nanzhu_skill01_hit",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Nvzhu_skill01_bao.NS_Nvzhu_skill01_bao",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Nvzhu_Skill02_DebuffLingYu.NS_Nvzhu_Skill02_DebuffLingYu",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_NVzhu_Skill02_BuffSpawn.NS_NVzhu_Skill02_BuffSpawn",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_NVzhu_Skill02_BuffLoop.NS_NVzhu_Skill02_BuffLoop"
}
T.RT_3 = {
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_LinenSkill01_Trail_R.NS_LinenSkill01_Trail_R",
  "/Game/Asset/Effect/Niagara/Player/Kami/NS_Bishou.NS_Bishou",
  "/Game/Asset/Effect/Niagara/Player/Kami/NS_Kamila_Skill02_Hand.NS_Kamila_Skill02_Hand",
  "/Game/Asset/Effect/Niagara/Weapon/Dualblade/NS_Dualblade_SlideAttack_Knife.NS_Dualblade_SlideAttack_Knife",
  "/Game/Asset/Effect/Niagara/Player/Kami/NS_Kami_Skill02Creature_Attack.NS_Kami_Skill02Creature_Attack",
  "/Game/Asset/Effect/Niagara/Player/Kami/NS_Kamila_Light.NS_Kamila_Light",
  "/Game/Asset/Effect/Niagara/Player/Kami/NS_Kamila_Skill02_Blackground.NS_Kamila_Skill02_Blackground",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_LinenSkill01_Trail_L.NS_LinenSkill01_Trail_L",
  "/Game/Asset/Effect/Niagara/Player/Kami/NS_Kamila_Skill02_Blackground_Fire.NS_Kamila_Skill02_Blackground_Fire",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_Wave.NS_Linen_Skill01_Wave"
}
T.RT_4 = {
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_fuji.NS_lise_fuji",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_junei_BF.NS_lise_skill02_junei_BF",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_Lise_skill01_itensity.NS_Lise_skill01_itensity",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill01_xl.NS_lise_skill01_xl",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_zheng.NS_lise_zheng",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_Lise_skill01_baoqi_02.NS_Lise_skill01_baoqi_02",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_Lise_skill01.NS_Lise_skill01",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_junei_JQ.NS_lise_skill02_junei_JQ",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_BUff_duiyou.NS_lise_BUff_duiyou",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_Cam_bf.NS_lise_skill02_Cam_bf",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_Cam_wenli.NS_lise_skill02_Cam_wenli",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_Cam_deng.NS_lise_skill02_Cam_deng",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_buff_tuowei.NS_lise_buff_tuowei",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_Cam.NS_lise_skill02_Cam",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_Cam_shandian.NS_lise_skill02_Cam_shandian",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_shandian_MonToMon.NS_lise_shandian_MonToMon",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_BUff.NS_lise_Buff",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_shandian_CharToMon.NS_lise_shandian_CharToMon",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_Lise_skill01_baoqi.NS_Lise_skill01_baoqi",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_Buff_Over.NS_lise_Buff_Over",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_junei_KS.NS_lise_skill02_junei_KS",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill01_tuowei.NS_lise_skill01_tuowei"
}
T.RT_5 = {
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_04_Boom_Spawn.NS_Zhiliu_Skill02_04_Boom_Spawn",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill01_Fuzhou_Spawn.NS_Zhiliu_Skill01_Fuzhou_Spawn",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_CamFuwen.NS_Zhiliu_Skill02_01_CamFuwen",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_CamSword.NS_Zhiliu_Skill02_01_CamSword",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Cam_Wind.NS_Zhiliu_Skill02_02_Cam_Wind",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_BJ.NS_Zhiliu_Skill02_02_BJ",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_03_Xuli.NS_Zhiliu_Skill02_03_Xuli",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Fazhen.NS_Zhiliu_Skill02_02_Fazhen",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_Fuwen.NS_Zhiliu_Skill02_01_Fuwen",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_03_Br.NS_Zhiliu_Skill02_03_Br",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_Zadi.NS_Zhiliu_Skill02_01_Zadi",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Cam_Fu05.NS_Zhiliu_Skill02_02_Cam_Fu05",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Cam_Fu04.NS_Zhiliu_Skill02_02_Cam_Fu04",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_Dian.NS_Zhiliu_Skill02_01_Dian",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_CamLight.NS_Zhiliu_Skill02_01_CamLight",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_Fazhen.NS_Zhiliu_Skill02_01_Fazhen",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_CamHandLight.NS_Zhiliu_Skill02_01_CamHandLight",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Cam_Lightning02.NS_Zhiliu_Skill02_02_Cam_Lightning02",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Burst.NS_Zhiliu_Skill02_02_Burst",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_Luoxuan2.NS_Zhiliu_Skill02_01_Luoxuan2",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Cam_Fu.NS_Zhiliu_Skill02_02_Cam_Fu",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Hand03.NS_Zhiliu_Skill02_02_Hand03",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill01_02_Xuli.NS_Zhiliu_Skill01_02_Xuli",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Cam_Fu02.NS_Zhiliu_Skill02_02_Cam_Fu02",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Hand02.NS_Zhiliu_Skill02_02_Hand02",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill01_02_Hand.NS_Zhiliu_Skill01_02_Hand",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_03_HandTrail.NS_Zhiliu_Skill02_03_HandTrail",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_03_Liuguang.NS_Zhiliu_Skill02_03_Liuguang",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_BJ2.NS_Zhiliu_Skill02_02_BJ2",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_Background.NS_Zhiliu_Skill02_01_Background",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Fenwei.NS_Zhiliu_Skill02_02_Fenwei",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Cam_Liuguang.NS_Zhiliu_Skill02_02_Cam_Liuguang",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_03_Wave.NS_Zhiliu_Skill02_03_Wave",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Cam_Wind02.NS_Zhiliu_Skill02_02_Cam_Wind02",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_Stone.NS_Zhiliu_Skill02_01_Stone",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_04_Boom_Spawn_Range.NS_Zhiliu_Skill02_04_Boom_Spawn_Range",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Lightning.NS_Zhiliu_Skill02_02_Lightning",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_Dilie.NS_Zhiliu_Skill02_01_Dilie",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_Baoqi.NS_Zhiliu_Skill02_01_Baoqi",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_04_Hand.NS_Zhiliu_Skill02_04_Hand",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_CloudLightning.NS_Zhiliu_Skill02_01_CloudLightning",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill01_Hand.NS_Zhiliu_Skill01_Hand",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_Cloud.NS_Zhiliu_Skill02_01_Cloud",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Hand.NS_Zhiliu_Skill02_02_Hand",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_CamWind.NS_Zhiliu_Skill02_01_CamWind",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Eye.NS_Zhiliu_Skill02_02_Eye",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill01_Burst.NS_Zhiliu_Skill01_Burst",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill01_02_Dun.NS_Zhiliu_Skill01_02_Dun",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_03_Fu01.NS_Zhiliu_Skill02_03_Fu01",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Cam_Lightning.NS_Zhiliu_Skill02_02_Cam_Lightning",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_Zadi_Range.NS_Zhiliu_Skill02_01_Zadi_Range",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill01_Ring.NS_Zhiliu_Skill01_Ring",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_04_Fuzhou_Spawn.NS_Zhiliu_Skill02_04_Fuzhou_Spawn",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_HandTrail.NS_Zhiliu_Skill02_01_HandTrail",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Huahen.NS_Zhiliu_Skill02_02_Huahen",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_JG02_Range.NS_Zhiliu_Skill02_02_JG02_Range",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_03_Fu.NS_Zhiliu_Skill02_03_Fu",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Cam_Fu03.NS_Zhiliu_Skill02_02_Cam_Fu03",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Ground02_Range.NS_Zhiliu_Skill02_02_Ground02_Range",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Cam_Wind03.NS_Zhiliu_Skill02_02_Cam_Wind03",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_JG02.NS_Zhiliu_Skill02_02_JG02",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_04_Ring.NS_Zhiliu_Skill02_04_Ring",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_03_FaceLight.NS_Zhiliu_Skill02_03_FaceLight",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_HandLight.NS_Zhiliu_Skill02_01_HandLight",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill02_01_Luoxuan.NS_Zhiliu_Skill02_01_Luoxuan",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Ground02.NS_Zhiliu_Skill02_02_Ground02",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/Zhiliu_Skill02_2/NS_Zhiliu_Skill02_02_Cam_Lightning03.NS_Zhiliu_Skill02_02_Cam_Lightning03",
  "/Game/Asset/Effect/Niagara/Player/Zhiliu/NS_Zhiliu_Skill01_Hit.NS_Zhiliu_Skill01_Hit"
}
T.RT_6 = {
  "/Game/Asset/Effect/Niagara/NPC/Awaer/NS_Awa_Skill01_Bullet.NS_Awa_Skill01_Bullet",
  "/Game/Asset/Effect/Niagara/NPC/Awaer/NS_Awa_Skill01_xvli.NS_Awa_Skill01_xvli",
  "/Game/Asset/Effect/Niagara/NPC/Awaer/NS_Awa_Skill01_Hit.NS_Awa_Skill01_Hit",
  "/Game/Asset/Effect/Niagara/NPC/Awaer/NS_Awa_Skill02_Aura.NS_Awa_Skill02_Aura",
  "/Game/Asset/Effect/Niagara/NPC/Awaer/NS_Awa_Skill01_Gunfire.NS_Awa_Skill01_Gunfire",
  "/Game/Asset/Effect/Niagara/NPC/Awaer/NS_Awa_Skill01_Gunfire_Small.NS_Awa_Skill01_Gunfire_Small",
  "/Game/Asset/Effect/Niagara/NPC/Awaer/NS_Awa_Skill02_Absor.NS_Awa_Skill02_Absor"
}
T.RT_7 = {
  "/Game/Asset/Effect/Niagara/Player/A_Common/NS_Common_Buff.NS_Common_Buff"
}
T.RT_8 = {
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_WeaponFX_Out.NS_WeaponFX_Out",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_BlackGround.NS_BlackGround",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_nvzhu_Prism.NS_nvzhu_Prism",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Weapon_Trail.NS_Weapon_Trail",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_WeaponFX_Start.NS_WeaponFX_Start",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_PostStar.NS_PostStar",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Nvzhu_PostEye.NS_Nvzhu_PostEye",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_nanzhu_skill01.NS_nanzhu_skill01",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Body.NS_Body"
}
T.RT_9 = {
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_WeaponFX_Out.NS_WeaponFX_Out",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_nvzhu_Prism.NS_nvzhu_Prism",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_WeaponFX_Start.NS_WeaponFX_Start",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Nvzhu_PostEye.NS_Nvzhu_PostEye",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_nanzhu_skill01.NS_nanzhu_skill01",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Body.NS_Body"
}
T.RT_10 = {
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_junei_BF.NS_lise_skill02_junei_BF",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill01_xl.NS_lise_skill01_xl",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_Lise_skill01_baoqi_02.NS_Lise_skill01_baoqi_02",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_junei_JQ.NS_lise_skill02_junei_JQ",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_Cam_bf.NS_lise_skill02_Cam_bf",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_Cam_wenli.NS_lise_skill02_Cam_wenli",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_Cam_deng.NS_lise_skill02_Cam_deng",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_Cam.NS_lise_skill02_Cam",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill02_Cam_shandian.NS_lise_skill02_Cam_shandian",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_Lise_skill01_baoqi.NS_Lise_skill01_baoqi",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_skill01_tuowei.NS_lise_skill01_tuowei"
}
T.RT_11 = {
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_Dx.NS_Yuming_Skill02_Dx",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_Sequencer_03.NS_Yuming_Skill02_Sequencer_03",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_ShocKwave.NS_Yuming_Skill02_ShocKwave",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill01_HandLightnin_003.NS_Yuming_Skill01_HandLightnin_003",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_Absort02.NS_Yuming_Skill02_Absort02",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_Sequencer_01.NS_Yuming_Skill02_Sequencer_01",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Light01.NS_Yuming_Light01",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Light02.NS_Yuming_Light02",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_Sequencer_02.NS_Yuming_Skill02_Sequencer_02",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill01_HandLightnin_002.NS_Yuming_Skill01_HandLightnin_002"
}
T.RT_12 = {
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_E_001.NS_Baiheng_E_001",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_Skill02_Burst_new.NS_Baiheng_Skill02_Burst_new",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_Skill2_Summon.NS_Baiheng_Skill2_Summon",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_SeqNew.NS_Baiheng_SeqNew",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_seq.NS_Baiheng_seq",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_Eye.NS_Baiheng_Eye",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_Skill2_Fan.NS_Baiheng_Skill2_Fan"
}
T.RT_13 = {
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Cam_004.NS_Kezhou_Skill02_Cam_004",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_NoShow_003.NS_Kezhou_Skill02_NoShow_003",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Claymore_04_Hand.NS_Kezhou_Claymore_04_Hand",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Polearm_KnifeLight_Mod04JumpGround.NS_Kezhou_Polearm_KnifeLight_Mod04JumpGround",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Polearm_KnifeLight_Mod02.NS_Kezhou_Polearm_KnifeLight_Mod02",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Claymore_Smoke_001.NS_Kezhou_Claymore_Smoke_001",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Cam_002.NS_Kezhou_Skill02_Cam_002",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Common_Jump.NS_Kezhou_Common_Jump",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Polearm_KnifeLight_Mod04Jump.NS_Kezhou_Polearm_KnifeLight_Mod04Jump",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Sword_Smoke.NS_Kezhou_Sword_Smoke",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_NoShow.NS_Kezhou_Skill02_NoShow",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Common_FootSmoke.NS_Kezhou_Common_FootSmoke",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Body_CamScene.NS_Kezhou_Skill02_Body_CamScene",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Claymore_03_Smoke.NS_Kezhou_Claymore_03_Smoke",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Cam_001.NS_Kezhou_Skill02_Cam_001",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Polearm_KnifeLight_Mod04Rush.NS_Kezhou_Polearm_KnifeLight_Mod04Rush",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Dualblade_Mod01_RunAttack03_Smoke.NS_Kezhou_Dualblade_Mod01_RunAttack03_Smoke",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Common_Burst.NS_Kezhou_Common_Burst",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Cam_005.NS_Kezhou_Skill02_Cam_005",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Dualblade_Smoke.NS_Kezhou_Dualblade_Smoke",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill_Body.NS_Kezhou_Skill_Body",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_NoShow_002.NS_Kezhou_Skill02_NoShow_002",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Stencil_Cam.NS_Kezhou_Stencil_Cam",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Cam_003.NS_Kezhou_Skill02_Cam_003"
}
T.RT_14 = {
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Butterfly.NS_Dafu_Skill02_Butterfly",
  "/Game/Asset/Effect/Niagara/Player/A_Common/NS_Common_Buff_Loop.NS_Common_Buff_Loop",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill01_Potion.NS_Dafu_Skill01_Potion",
  "/Game/Asset/Effect/Niagara/Player/A_Common/NS_Common_DeBuff_Loop.NS_Common_DeBuff_Loop",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_BreakWave.NS_Dafu_Skill02_BreakWave",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Background.NS_Dafu_Skill02_Background",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Buff.NS_Dafu_Skill02_Buff",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Glow02.NS_Dafu_Skill02_Glow02",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Fall.NS_Dafu_Skill02_Fall",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Glow.NS_Dafu_Skill02_Glow",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Sparks.NS_Dafu_Skill02_Sparks",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Line.NS_Dafu_Skill02_Line",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill01_Cast.NS_Dafu_Skill01_Cast",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill01_Smoke.NS_Dafu_Skill01_Smoke",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Cast.NS_Dafu_Skill02_Cast",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Leave.NS_Dafu_Skill02_Leave",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Break.NS_Dafu_Skill02_Break",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Lamp.NS_Dafu_Skill02_Lamp",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill01_Hand.NS_Dafu_Skill01_Hand"
}
T.RT_15 = {
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Butterfly.NS_Dafu_Skill02_Butterfly",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_BreakWave.NS_Dafu_Skill02_BreakWave",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Background.NS_Dafu_Skill02_Background",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Glow02.NS_Dafu_Skill02_Glow02",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Fall.NS_Dafu_Skill02_Fall",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Glow.NS_Dafu_Skill02_Glow",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Sparks.NS_Dafu_Skill02_Sparks",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Line.NS_Dafu_Skill02_Line",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill01_Cast.NS_Dafu_Skill01_Cast",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Cast.NS_Dafu_Skill02_Cast",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Leave.NS_Dafu_Skill02_Leave",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Break.NS_Dafu_Skill02_Break",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill02_Lamp.NS_Dafu_Skill02_Lamp",
  "/Game/Asset/Effect/Niagara/NPC/Dafu/NS_Dafu_Skill01_Hand.NS_Dafu_Skill01_Hand"
}
T.RT_16 = {}
T.RT_17 = {
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Hit.NS_Baonu_Skill02_Hit",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Attack_04_03.NS_Baonu_Skill02_Attack_04_03",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Attack_03.NS_Baonu_Skill02_Attack_03",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Attack_04_3.NS_Baonu_Skill02_Attack_04_3",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Attack_01.NS_Baonu_Skill02_Attack_01",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Trail.NS_Baonu_Trail",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Heavy_Burst.NS_Baonu_Skill02_Heavy_Burst",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_On02.NS_Baonu_Skill02_On02",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Knife.NS_Baonu_Skill02_Knife",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Ground02.NS_Baonu_Skill02_Ground02",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Ground01.NS_Baonu_Skill02_Ground01",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_ShowWeapon.NS_Baonu_Skill02_ShowWeapon",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_WP.NS_Baonu_WP",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_on.NS_Baonu_Skill02_on",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Passive_buff.NS_Baonu_Passive_Buff",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_ShowBG01.NS_Baonu_Skill02_ShowBG01",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_ShowWeapon_002.NS_Baonu_Skill02_ShowWeapon_002",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Show_Burst.NS_Baonu_Skill02_Show_Burst",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_WP01.NS_Baonu_Skill02_WP01",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Attack_02.NS_Baonu_Skill02_Attack_02",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Off.NS_Baonu_Skill02_Off",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Attack_04_2.NS_Baonu_Skill02_Attack_04_2",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_ShowBG02.NS_Baonu_Skill02_ShowBG02",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_Attack_04_1.NS_Baonu_Skill02_Attack_04_1",
  "/Game/Asset/Effect/Niagara/Player/Baonu/NS_Baonu_Skill02_ShowBG.NS_Baonu_Skill02_ShowBG"
}
T.RT_18 = {
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill01_2.NS_Nifu_Skill01_2",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill01_1.NS_Nifu_Skill01_1",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill02_JN.NS_Nifu_Skill02_JN",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill01_3.NS_Nifu_Skill01_3",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill02_fire.NS_Nifu_Skill02_fire",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill02_5.NS_Nifu_Skill02_5",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill02_fire_02.NS_Nifu_Skill02_fire_02",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill02_end.NS_Nifu_Skill02_end",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill02_fire_01.NS_Nifu_Skill02_fire_01",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill02_6.NS_Nifu_Skill02_6",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill02_fire_03.NS_Nifu_Skill02_fire_03",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_GbufferOutline_2.NS_GbufferOutline_2",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill01_4.NS_Nifu_Skill01_4",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill02_trail01.NS_Nifu_Skill02_trail01",
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill02_ShowBG.NS_Nifu_Skill02_ShowBG"
}
T.RT_19 = {
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Loop.NS_Kezhou_Skill02_Loop",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Stencil_Arm.NS_Kezhou_Stencil_Arm",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Stencil_spine_03.NS_Kezhou_Stencil_spine_03",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_WeaponDecal_Batch.NS_Kezhou_WeaponDecal_Batch",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_WeaponDecal_Dualblade_Batch.NS_Kezhou_WeaponDecal_Dualblade_Batch",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Sword_Attack.NS_Kezhou_Sword_Attack",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_ShadowSword_Bullet.NS_Kezhou_Skill02_ShadowSword_Bullet",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Cam_004.NS_Kezhou_Skill02_Cam_004",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_WeaponTrail_Batch.NS_Kezhou_WeaponTrail_Batch",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_NoShow_003.NS_Kezhou_Skill02_NoShow_003",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Claymore_04_Hand.NS_Kezhou_Claymore_04_Hand",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Polearm_KnifeLight_Mod04JumpGround.NS_Kezhou_Polearm_KnifeLight_Mod04JumpGround",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Polearm_KnifeLight_Mod02.NS_Kezhou_Polearm_KnifeLight_Mod02",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Claymore_Smoke_001.NS_Kezhou_Claymore_Smoke_001",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Bullet.NS_Kezhou_Skill02_Bullet",
  "/Game/Asset/Effect/Niagara/Weapon/Shotgun/Banzi/NS_Banzi_Explode.NS_Banzi_Explode",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill01_Hit_Pose.NS_Kezhou_Skill01_Hit_Pose",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Cam_002.NS_Kezhou_Skill02_Cam_002",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Common_Jump.NS_Kezhou_Common_Jump",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Polearm_KnifeLight_Mod04Jump.NS_Kezhou_Polearm_KnifeLight_Mod04Jump",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill01_Appear.NS_Kezhou_Skill01_Appear",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill01_ShootBurst.NS_Kezhou_Skill01_ShootBurst",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Sword_Smoke.NS_Kezhou_Sword_Smoke",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_NoShow.NS_Kezhou_Skill02_NoShow",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Common_FootSmoke.NS_Kezhou_Common_FootSmoke",
  "/Game/Asset/Effect/Niagara/Weapon/Polearm/NS_Polearm_HeavyAttack_Bullet.NS_Polearm_HeavyAttack_Bullet",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_ShadowSword_Hit.NS_Kezhou_Skill02_ShadowSword_Hit",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Body_CamScene.NS_Kezhou_Skill02_Body_CamScene",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Claymore_03_Smoke.NS_Kezhou_Claymore_03_Smoke",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Cam_001.NS_Kezhou_Skill02_Cam_001",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Polearm_Bullet.NS_Kezhou_Polearm_Bullet",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Polearm_KnifeLight_Mod04Rush.NS_Kezhou_Polearm_KnifeLight_Mod04Rush",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill01_Hit.NS_Kezhou_Skill01_Hit",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Dualblade_Mod01_RunAttack03_Smoke.NS_Kezhou_Dualblade_Mod01_RunAttack03_Smoke",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Common_Burst.NS_Kezhou_Common_Burst",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Cam_005.NS_Kezhou_Skill02_Cam_005",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Dualblade_Smoke.NS_Kezhou_Dualblade_Smoke",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill_Body.NS_Kezhou_Skill_Body",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_NoShow_002.NS_Kezhou_Skill02_NoShow_002",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Stencil_Cam.NS_Kezhou_Stencil_Cam",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Cam_003.NS_Kezhou_Skill02_Cam_003",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill01_Burst.NS_Kezhou_Skill01_Burst",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill02_Explode.NS_Kezhou_Skill02_Explode",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_Skill01_Buff.NS_Kezhou_Skill01_Buff",
  "/Game/Asset/Effect/Niagara/Player/Kezhou/NS_Kezhou_WeaponFX.NS_Kezhou_WeaponFX"
}
T.RT_20 = {
  "/Game/Asset/Effect/Niagara/Weapon/Bow/NS_Bow_Bullet_01.NS_Bow_Bullet_01",
  "/Game/Asset/Effect/Niagara/Weapon/Cannon/NS_Jishu_Explode_Small.NS_Jishu_Explode_Small",
  "/Game/Asset/Effect/Niagara/Player/Suyi/NS_Suyi_Creature_Yinxin.NS_Suyi_Creature_Yinxin",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_SwordWave.NS_Heitao_SwordWave"
}
T.RT_21 = {
  "/Game/Asset/Effect/Niagara/Player/Feina/NS_Feina_Part_Burst.NS_Feina_Part_Burst",
  "/Game/Asset/Effect/Niagara/Player/Feina/NS_Feina_Part_Bullet.NS_Feina_Part_Bullet",
  "/Game/Asset/Effect/Niagara/Player/Feina/NS_Feina_Sum02_AddBuff.NS_Feina_Sum02_AddBuff",
  "/Game/Asset/Effect/Niagara/Player/Feina/NS_Feina_Part_Hit.NS_Feina_Part_Hit"
}
T.RT_22 = {
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi01_Skill02_Seq.NS_Tuosi01_Skill02_Seq",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Skill02Wutai.NS_Tuosi_Skill02Wutai",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Condemned_Stab.NS_Tuosi02_Condemned_Stab",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Condemn01.NS_Tuosi02_Condemn01",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Skill02_Background.NS_Tuosi_Skill02_Background",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi01_Skill01_wave.NS_Tuosi01_Skill01_wave",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Seq_Hand.NS_Tuosi_Seq_Hand",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_GbufferOutline.NS_Tuosi02_GbufferOutline",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_FootSteps.NS_Tuosi_FootSteps",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Skill02_Seqqiliu.NS_Tuosi_Skill02_Seqqiliu",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi01_Skill01_xishou.NS_Tuosi01_Skill01_xishou",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Condemned_Weapon.NS_Tuosi02_Condemned_Weapon",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi01_Skill01_wave1.NS_Tuosi01_Skill01_wave1",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi01_Skill02_Cam.NS_Tuosi01_Skill02_Cam",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Condemned_Wind.NS_Heitao_Condemned_Wind",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Change04.NS_Tuosi02_Change04",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Change03.NS_Tuosi02_Change03",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Skill02_Lighting.NS_Tuosi_Skill02_Lighting",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Skill02_eye.NS_Tuosi_Skill02_eye",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Change02.NS_Tuosi02_Change02"
}
T.RT_23 = {
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill02_Explode_Small.NS_Maer_Skill02_Explode_Small",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill02_Explode.NS_Maer_Skill02_Explode",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill02_Daoguang.NS_Maer_Skill02_Daoguang",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill01_Smoke02.NS_Maer_Skill01_Smoke02",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill02_Bullet.NS_Maer_Skill02_Bullet",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill02_Power02.NS_Maer_Skill02_Power02",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill01_Hit.NS_Maer_Skill01_Hit",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill02_Background03.NS_Maer_Skill02_Background03",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill02_Wind.NS_Maer_Skill02_Wind",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill02_Hit.NS_Maer_Skill02_Hit",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill02_Glow.NS_Maer_Skill02_Glow",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill01_Loop_L.NS_Maer_Skill01_Loop_L",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill01_Smoke01.NS_Maer_Skill01_Smoke01",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill02_Background01.NS_Maer_Skill02_Background01",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill01_Loop_R.NS_Maer_Skill01_Loop_R",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill02_Background02.NS_Maer_Skill02_Background02",
  "/Game/Asset/Effect/Niagara/Player/Maer/NS_Maer_Skill02_Power.NS_Maer_Skill02_Power"
}
T.RT_24 = {
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill02_Body_CamScene.NS_Saiqi_Skill02_Body_CamScene",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill02_LittleButterfly.NS_Saiqi_Skill02_LittleButterfly",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill1_Rune.NS_Saiqi_Skill1_Rune",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Wing.NS_Saiqi_Wing",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Butterfly_Bullet.NS_Saiqi_Butterfly_Bullet",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill01_Ghost.NS_Saiqi_Skill01_Ghost",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill02_HitWall.NS_Saiqi_Skill02_HitWall",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill02_Appera.NS_Saiqi_Skill02_Appera",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill01_InBuff_Wind.NS_Saiqi_Skill01_InBuff_Wind",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill02Wings_Loop.NS_Saiqi_Skill02Wings_Loop",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Butterfly_Destroy.NS_Saiqi_Butterfly_Destroy",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill01_Dash.NS_Saiqi_Skill01_Dash",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Wing_End.NS_Saiqi_Wing_End",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill02_Pre.NS_Saiqi_Skill02_Pre",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill02_HitWall02.NS_Saiqi_Skill02_HitWall02",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill02_Vanish.NS_Saiqi_Skill02_Vanish",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Butterfly_Hit.NS_Saiqi_Butterfly_Hit",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill02_RedButterfly.NS_Saiqi_Skill02_RedButterfly",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill02_Body_Scene.NS_Saiqi_Skill02_Body_Scene",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill02_Wind.NS_Saiqi_Skill02_Wind",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill01_InBuff.NS_Saiqi_Skill01_InBuff",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill01_Explode.NS_Saiqi_Skill01_Explode",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Skill01_appear.NS_Saiqi_Skill01_appear",
  "/Game/Asset/Effect/Niagara/Player/Saiqi/NS_Saiqi_Passive.NS_Saiqi_Passive"
}
T.RT_25 = {
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Explosion_Orange.NS_Yeer_Explosion_Orange",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Skill01_On.NS_Yeer_Skill01_On",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Explosion_Blue.NS_Yeer_Explosion_Blue",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Skill02_AbsorbSpark.NS_Yeer_Skill02_AbsorbSpark",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Skill02_Bomb_Burst.NS_Yeer_Skill02_Bomb_Burst",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Skill02_Star.NS_Yeer_Skill02_Star",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Skill02_Star02.NS_Yeer_Skill02_Star02",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Skill02_Background.NS_Yeer_Skill02_Background",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Grade1_Burst.NS_Yeer_Grade1_Burst",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Skill02_Hand_02.NS_Yeer_Skill02_Hand_02",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Skill02_Hand.NS_Yeer_Skill02_Hand",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Skill02_End.NS_Yeer_Skill02_End",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_Skill02_Domain.NS_Yeer_Skill02_Domain",
  "/Game/Asset/Effect/Niagara/Player/Yeer/NS_Yeer_bomb.NS_Yeer_bomb"
}
T.RT_26 = {
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_Dx.NS_Yuming_Skill02_Dx",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_Sequencer_03.NS_Yuming_Skill02_Sequencer_03",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_Lightening_L.NS_Yuming_Skill02_Lightening_L",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_ShocKwave.NS_Yuming_Skill02_ShocKwave",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill01_HandLightnin_003.NS_Yuming_Skill01_HandLightnin_003",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_Absort02.NS_Yuming_Skill02_Absort02",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_Sequencer_01.NS_Yuming_Skill02_Sequencer_01",
  "/Game/Asset/Effect/Niagara/Player/Lise/NS_lise_shouji.NS_lise_shouji",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Light01.NS_Yuming_Light01",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Light02.NS_Yuming_Light02",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_Lightening_S.NS_Yuming_Skill02_Lightening_S",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill02_Sequencer_02.NS_Yuming_Skill02_Sequencer_02",
  "/Game/Asset/Effect/Niagara/Player/Yuming/NS_Yuming_Skill01_HandLightnin_002.NS_Yuming_Skill01_HandLightnin_002"
}
T.RT_27 = {
  "/Game/Asset/Effect/Niagara/Player/Landi/NS_Landi_Skill02_Hand.NS_Landi_Skill02_Hand",
  "/Game/Asset/Effect/Niagara/Player/Landi/NS_Landi_Skill02_Ground02.NS_Landi_Skill02_Ground02",
  "/Game/Asset/Effect/Niagara/Player/Landi/NS_Landi_Skill02_Ground01.NS_Landi_Skill02_Ground01",
  "/Game/Asset/Effect/Niagara/Player/Landi/NS_Landi_Skill02_Hand02.NS_Landi_Skill02_Hand02",
  "/Game/Asset/Effect/Niagara/Player/Landi/NS_Landi_Skill01_03.NS_Landi_Skill01_03",
  "/Game/Asset/Effect/Niagara/Player/Landi/NS_Landi_Skill02_Show_L.NS_Landi_Skill02_Show_L",
  "/Game/Asset/Effect/Niagara/Player/Landi/NS_Landi_body.NS_Landi_body",
  "/Game/Asset/Effect/Niagara/Player/Landi/NS_Landi_Skill02_Shield_01.NS_Landi_Skill02_Shield_01",
  "/Game/Asset/Effect/Niagara/Player/Landi/NS_Landi_Skill02_Show_01.NS_Landi_Skill02_Show_01",
  "/Game/Asset/Effect/Niagara/Player/Landi/NS_Landi_Skill02_Hand01.NS_Landi_Skill02_Hand01",
  "/Game/Asset/Effect/Niagara/Player/Landi/NS_Landi_Skill02_Show_Light.NS_Landi_Skill02_Show_Light"
}
T.RT_28 = {
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Buff_Arm.NS_Haier_Buff_Arm",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Skill02.NS_Haier_Skill02",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Skill02_Foot.NS_Haier_Skill02_Foot",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Sequence_FireGlow.NS_Haier_Sequence_FireGlow",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Sequence_Suo.NS_Haier_Sequence_Suo",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_AuraRange.NS_Haier_AuraRange",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Sequence_EyeTrail.NS_Haier_Sequence_EyeTrail",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Skill02_Pre.NS_Haier_Skill02_Pre",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Body_Scene.NS_Haier_Body_Scene",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Fire.NS_Haier_Fire",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Passive.NS_Haier_Passive",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Skill01_Burst.NS_Haier_Skill01_Burst",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Buff_Leg.NS_Haier_Buff_Leg",
  "/Game/Asset/Effect/Niagara/Player/Haier/NS_Haier_Body_Buff.NS_Haier_Body_Buff"
}
T.RT_29 = {
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_Line.NS_Xibi_Skill02_Line",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_Background.NS_Xibi_Skill02_Background",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_hand.NS_Xibi_Skill02_hand",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_hand02.NS_Xibi_Skill02_hand02",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_Ball_Hit.NS_Xibi_Skill02_Ball_Hit",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_Explosion.NS_Xibi_Skill02_Explosion",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_Background2.NS_Xibi_Skill02_Background2",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_Ball_Appear02.NS_Xibi_Skill02_Ball_Appear02",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_Ball.NS_Xibi_Skill02_Ball",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_Cam.NS_Xibi_Skill02_Cam",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill01_Hit.NS_Xibi_Skill01_Hit",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_Explosion_2.NS_Xibi_Skill02_Explosion_2",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_BlackHole02.NS_Xibi_Skill02_BlackHole02",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill01_Wind2.NS_Xibi_Skill01_Wind2",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_hand04.NS_Xibi_Skill02_hand04",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill01_Foot02.NS_Xibi_Skill01_Foot02",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_Ball_EX.NS_Xibi_Skill02_Ball_EX",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_Light.NS_Xibi_Skill02_Light",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill01_Cloud.NS_Xibi_Skill01_Cloud",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_BlackHole.NS_Xibi_Skill02_BlackHole",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill01_Hit02.NS_Xibi_Skill01_Hit02",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill01_Foot01.NS_Xibi_Skill01_Foot01",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_hand03.NS_Xibi_Skill02_hand03",
  "/Game/Asset/Effect/Niagara/Player/Xibi/NS_Xibi_Skill02_Ball_DisAppear.NS_Xibi_Skill02_Ball_DisAppear"
}
T.RT_30 = {
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Hit.NS_Songlu_Hit",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Show_BodyEnd.NS_Songlu_Show_BodyEnd",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Buff_Zhenzi_Spark.NS_Songlu_Buff_Zhenzi_Spark",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Buff_Loop.NS_Songlu_Buff_Loop",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Show_smoke_02.NS_Songlu_Show_smoke_02",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Show_Whistle.NS_Songlu_Show_Whistle",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Skill01_BodyCast.NS_Songlu_Skill01_BodyCast",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Skill01_Jump.NS_Songlu_Skill01_Jump",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Skill01_Hand.NS_Songlu_Skill01_Hand",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Buff_Zhenzi_Piaodai_Spark2.NS_Songlu_Buff_Zhenzi_Piaodai_Spark2",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Buff_Zhenzi_Hudiejie_Spark1.NS_Songlu_Buff_Zhenzi_Hudiejie_Spark1",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Skill02_Explo.NS_Songlu_Skill02_Explo",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Skill02_Trail01.NS_Songlu_Skill02_Trail01",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Skill01_Explo.NS_Songlu_Skill01_Explo",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Skill01_BodyCast_Trail.NS_Songlu_Skill01_BodyCast_Trail",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Skill02_Running.NS_Songlu_Skill02_Running",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Skill02_Trail02.NS_Songlu_Skill02_Trail02",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Skill01_PPRun.NS_Songlu_Skill01_PPRun",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Show_Lines.NS_Songlu_Show_Lines",
  "/Game/Asset/Effect/Niagara/Player/Songlu/NS_Songlu_Show_smoke_01.NS_Songlu_Show_smoke_01"
}
T.RT_31 = {
  "/Game/Asset/Effect/Niagara/Player/Aote/NS_Aote_skill02_SeqNew.NS_Aote_skill02_SeqNew",
  "/Game/Asset/Effect/Niagara/Player/Aote/NS_Aote_skill02_xishou2.NS_Aote_skill02_xishou2",
  "/Game/Asset/Effect/Niagara/Player/Aote/NS_Aote_skill02_saoguang.NS_Aote_skill02_saoguang",
  "/Game/Asset/Effect/Niagara/Player/Aote/NS_Aote_hIT.NS_Aote_Hit",
  "/Game/Asset/Effect/Niagara/Player/Aote/NS_Aote_skill01_shan.NS_Aote_skill01_shan",
  "/Game/Asset/Effect/Niagara/Player/Aote/NS_Aote_Sudu.NS_Aote_Sudu",
  "/Game/Asset/Effect/Niagara/Player/Aote/NS_Aote_skill01_sprint.NS_Aote_skill01_sprint",
  "/Game/Asset/Effect/Niagara/Player/Aote/NS_Aote_BuffSelf.NS_Aote_BuffSelf",
  "/Game/Asset/Effect/Niagara/Player/Aote/NS_Aote_skill02_eyes.NS_Aote_skill02_eyes",
  "/Game/Asset/Effect/Niagara/Player/Aote/NS_Aote_skill02_xishou1.NS_Aote_skill02_xishou1"
}
T.RT_32 = {
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Nvzhu_Skill02_LingYu.NS_Nvzhu_Skill02_LingYu",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_WeaponFX_Out.NS_WeaponFX_Out",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_nvzhu_Prism.NS_nvzhu_Prism",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Nvzhu_PostEye_02.NS_Nvzhu_PostEye_02",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_WeaponFX_Start.NS_WeaponFX_Start",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Body.NS_Body"
}
T.RT_33 = {
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Projectile.NS_Xier_Projectile",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_OpenFire.NS_Xier_OpenFire",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Skill01_laser_Batch.NS_Xier_Skill01_laser_Batch",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Skill01_Disappear.NS_Xier_Skill01_Disappear",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Skill02_GroundChain.NS_Xier_Skill02_GroundChain",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Skill02_Background.NS_Xier_Skill02_Background",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Skill01_Weapon_Disappear.NS_Xier_Skill01_Weapon_Disappear",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Skill02_Drop.NS_Xier_Skill02_Drop",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_xier_chain.NS_xier_chain",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Skill02_GroundChainDetial.NS_Xier_Skill02_GroundChainDetial",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Skill02_eyes.NS_Xier_Skill02_eyes",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Skill02_Particle.NS_Xier_Skill02_Particle",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_xier_Wave.NS_xier_Wave",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Buff.NS_Xier_Buff",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Skill02_Buff.NS_Xier_Skill02_Buff",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Skill02_Flower.NS_Xier_Skill02_Flower",
  "/Game/Asset/Effect/Niagara/Player/Xier/NS_Xier_Skill01_Weapon.NS_Xier_Skill01_Weapon"
}
T.RT_34 = {
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill02_Shoot.NS_Linen_Skill02_Shoot",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill02_CrzShoot.NS_Linen_Skill02_CrzShoot",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_Buff.NS_Linen_Skill01_Buff",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Buff_Body_Arm.NS_Linen_Buff_Body_Arm",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_LinenSkill01_Trail_R.NS_LinenSkill01_Trail_R",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_ShowBG.NS_Linen_ShowBG",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_BuffExpo.NS_Linen_Skill01_BuffExpo",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_Shoot.NS_Linen_Skill01_Shoot",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_L_Shoot.NS_Linen_Skill01_L_Shoot",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Show_End.NS_Linen_Show_End",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_B_Shoot.NS_Linen_Skill01_B_Shoot",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_R_Shoot.NS_Linen_Skill01_R_Shoot",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Buff_Body_Spine.NS_Linen_Buff_Body_Spine",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_Explo.NS_Linen_Skill01_Explo",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill02_Qilang.NS_Linen_Skill02_Qilang",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill02_Fenwei.NS_Linen_Skill02_Fenwei",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill02_Hit.NS_Linen_Skill02_Hit",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_GunCross.NS_Linen_GunCross",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Show_GunTrail.NS_Linen_Show_GunTrail",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Show_GunFire.NS_Linen_Show_GunFire",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Buff_Body_Leg.NS_Linen_Buff_Body_Leg",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Show_GunShadow.NS_Linen_Show_GunShadow",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill02_GunShadow.NS_Linen_Skill02_GunShadow",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_B_Smoke.NS_Linen_Skill01_B_Smoke",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_LinenSkill01_Trail_L.NS_LinenSkill01_Trail_L",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_Projectile.NS_Linen_Skill01_Projectile",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_M_Shoot.NS_Linen_Skill01_M_Shoot",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Buff_Gun.NS_Linen_Buff_Gun",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Show_GunCross.NS_Linen_Show_GunCross",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Show_GunRibbon.NS_Linen_Show_GunRibbon",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_F_Shoot.NS_Linen_Skill01_F_Shoot",
  "/Game/Asset/Effect/Niagara/Player/Linen/NS_Linen_Skill01_Wave.NS_Linen_Skill01_Wave"
}
T.RT_35 = {
  "/Game/Asset/Effect/Niagara/Player/Shuimu/NS_Shuimu_Debuff_Spread.NS_Shuimu_Debuff_Spread",
  "/Game/Asset/Effect/Niagara/Player/Shuimu/NDC_Shuimu_Skill02_Shuizhu.NDC_Shuimu_Skill02_Shuizhu",
  "/Game/Asset/Effect/Niagara/Player/Shuimu/NS_Shuimu_Skill02_fazhen.NS_Shuimu_Skill02_fazhen",
  "/Game/Asset/Effect/Niagara/Player/Shuimu/NS_Shuimu_skill02_sequence_05.NS_Shuimu_skill02_sequence_05",
  "/Game/Asset/Effect/Niagara/Player/Shuimu/NS_Shuimu_skill02_sequence_01.NS_Shuimu_skill02_sequence_01",
  "/Game/Asset/Effect/Niagara/Player/Shuimu/NS_Shuimu_Debuff_Weak.NS_Shuimu_Debuff_Weak",
  "/Game/Asset/Effect/Niagara/Player/Shuimu/NS_Shuimu_skill02_sequence_04.NS_Shuimu_skill02_sequence_04",
  "/Game/Asset/Effect/Niagara/Player/Shuimu/NS_Shuimu_skill02_sequence_02.NS_Shuimu_skill02_sequence_02",
  "/Game/Asset/Effect/Niagara/Player/Shuimu/NS_Shuimu_skill02_sequence_03.NS_Shuimu_skill02_sequence_03",
  "/Game/Asset/Effect/Niagara/Player/Shuimu/NS_Shuimu_Skill02_Trail.NS_Shuimu_Skill02_Trail",
  "/Game/Asset/Effect/Niagara/Player/Shuimu/NS_Shuimu_Skill02_Ripple.NS_Shuimu_Skill02_Ripple"
}
T.RT_36 = {
  "/Game/Asset/Effect/Niagara/Player/Feina/NS_Feina_Skill02_WaterCircle.NS_Feina_Skill02_WaterCircle",
  "/Game/Asset/Effect/Niagara/Player/Shuimu/NS_Shuimu_skill02_sequence_02.NS_Shuimu_skill02_sequence_02"
}
T.RT_37 = {
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_E_001.NS_Baiheng_E_001",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_BFSelfRoot.NS_Baiheng_BFSelfRoot",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_Skill02_Burst_new.NS_Baiheng_Skill02_Burst_new",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_BuffSelf.NS_Baiheng_BuffSelf",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_shouji.NS_Baiheng_shouji",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_Skill2_Summon.NS_Baiheng_Skill2_Summon",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_E_003.NS_Baiheng_E_003",
  "/Game/Asset/Effect/Niagara/Scene/East01/NS_Baiheng_Debuff.NS_Baiheng_Debuff",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_E_004_Back.NS_Baiheng_E_004_Back",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_SeqNew.NS_Baiheng_SeqNew",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_Buff.NS_Baiheng_Buff",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_seq.NS_Baiheng_seq",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_Eye.NS_Baiheng_Eye",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_E_005_Begin.NS_Baiheng_E_005_Begin",
  "/Game/Asset/Effect/Niagara/Player/Baiheng/NS_Baiheng_Skill2_Fan.NS_Baiheng_Skill2_Fan"
}
T.RT_38 = {
  "/Game/Asset/Effect/Niagara/Player/Feina/NS_Feina_Skill02_Body_Scene.NS_Feina_Skill02_Body_Scene",
  "/Game/Asset/Effect/Niagara/Player/Feina/NS_Feina_Skill02_CamEnd.NS_Feina_Skill02_CamEnd",
  "/Game/Asset/Effect/Niagara/Player/Feina/NS_Feina_AddBuff.NS_Feina_AddBuff",
  "/Game/Asset/Effect/Niagara/Player/Feina/NS_Feina_Skill02_Hand.NS_Feina_Skill02_Hand",
  "/Game/Asset/Effect/Niagara/Player/Feina/NS_Feina_Skill01_Hand.NS_Feina_Skill01_Hand"
}
T.RT_39 = {
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Knife002.NS_Heitao_Knife002",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_KnifeWave.NS_Heitao_KnifeWave",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02_Eyes.NS_Heitao_Skill02_Eyes",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Condemned_Weapon.NS_Heitao_Condemned_Weapon",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02Off_WP.NS_Heitao_Skill02Off_WP",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Absorb06.NS_Heitao_Skill02On_Absorb06",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill01_Rush.NS_Heitao_Skill01_Rush",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Absorb05.NS_Heitao_Skill02On_Absorb05",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02Off_Trail.NS_Heitao_Skill02Off_Trail",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Replication02.NS_Heitao_Replication02",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Condemned_Stab.NS_Heitao_Condemned_Stab",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Absorb07.NS_Heitao_Skill02On_Absorb07",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill01_End.NS_Heitao_Skill01_End",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Replication03.NS_Heitao_Replication03",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02Off_Wave.NS_Heitao_Skill02Off_Wave",
  "/Game/Asset/Effect/Niagara/Player/Zhangyu/zhangyu_skill_new/NS_zhangyu_idle_shuiquan.NS_zhangyu_idle_shuiquan",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill2_Hit.NS_Heitao_Skill2_Hit",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill01.NS_Heitao_Skill01",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02Off.NS_Heitao_Skill02Off",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Body.NS_Heitao_Skill02On_Body",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Absorb03.NS_Heitao_Skill02On_Absorb03",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Knife001.NS_Heitao_Knife001",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Condemned_Absorb.NS_Heitao_Condemned_Absorb",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Replication.NS_Heitao_Replication",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Back.NS_Heitao_Skill02On_Back",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Absorb04.NS_Heitao_Skill02On_Absorb04",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Replication04.NS_Heitao_Replication04",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill01_Rush_End.NS_Heitao_Skill01_Rush_End"
}
T.RT_40 = {
  "/Game/Asset/Effect/Niagara/Player/Nifu/NS_Nifu_Skill01_3.NS_Nifu_Skill01_3",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_WeaponFX_Out.NS_WeaponFX_Out",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_BlackGround.NS_BlackGround",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_nvzhu_Prism.NS_nvzhu_Prism",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Weapon_Trail.NS_Weapon_Trail",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_WeaponFX_Start.NS_WeaponFX_Start",
  "/Game/Asset/Effect/Niagara/Roguelike/Rou_Contract_Bomb_Burst.Rou_Contract_Bomb_Burst",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_PostStar.NS_PostStar",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Nvzhu_PostEye.NS_Nvzhu_PostEye",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_nanzhu_skill01.NS_nanzhu_skill01",
  "/Game/Asset/Effect/Niagara/Player/Nvzhu/NS_Body.NS_Body"
}
T.RT_41 = {
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi01_Debuff.NS_Tuosi01_Debuff",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_BuffLoop.NS_Tuosi02_BuffLoop",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Stencil_Arm.NS_Tuosi_Stencil_Arm",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi01_Skill02_Seq.NS_Tuosi01_Skill02_Seq",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Skill02Wutai.NS_Tuosi_Skill02Wutai",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Condemned_Stab.NS_Tuosi02_Condemned_Stab",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Condemn01.NS_Tuosi02_Condemn01",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Skill02_Background.NS_Tuosi_Skill02_Background",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi01_Skill01_wave.NS_Tuosi01_Skill01_wave",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Seq_Hand.NS_Tuosi_Seq_Hand",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_GbufferOutline.NS_Tuosi02_GbufferOutline",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_FootSteps.NS_Tuosi_FootSteps",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Skill02_Seqqiliu.NS_Tuosi_Skill02_Seqqiliu",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi01_Skill01_xishou.NS_Tuosi01_Skill01_xishou",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi01_Debuff02.NS_Tuosi01_Debuff02",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Condemned_Weapon.NS_Tuosi02_Condemned_Weapon",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Shoothit.NS_Tuosi02_Shoothit",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_knifehit_char_dir1.NS_knifehit_char_dir1",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_knifehit_char_normal1.NS_knifehit_char_normal1",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Shoot.NS_Tuosi02_Shoot",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi01_Skill01_wave1.NS_Tuosi01_Skill01_wave1",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi01_Skill02_Cam.NS_Tuosi01_Skill02_Cam",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Condemned_Wind.NS_Heitao_Condemned_Wind",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Change04.NS_Tuosi02_Change04",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_ShootPro.NS_Tuosi02_ShootPro",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_InBuff.NS_Tuosi02_InBuff",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Change03.NS_Tuosi02_Change03",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Skill02_Lighting.NS_Tuosi_Skill02_Lighting",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi_Skill02_eye.NS_Tuosi_Skill02_eye",
  "/Game/Asset/Effect/Niagara/Player/Tuosi/NS_Tuosi02_Change02.NS_Tuosi02_Change02"
}
T.RT_42 = {
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Knife002.NS_Heitao_Knife002",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_KnifeWave.NS_Heitao_KnifeWave",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02_Eyes.NS_Heitao_Skill02_Eyes",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Condemned_Weapon.NS_Heitao_Condemned_Weapon",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02Off_WP.NS_Heitao_Skill02Off_WP",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Absorb06.NS_Heitao_Skill02On_Absorb06",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill01_Rush.NS_Heitao_Skill01_Rush",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_BodyBuff.NS_Heitao_BodyBuff",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Absorb05.NS_Heitao_Skill02On_Absorb05",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02Off_Trail.NS_Heitao_Skill02Off_Trail",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Replication02.NS_Heitao_Replication02",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Condemned_Stab.NS_Heitao_Condemned_Stab",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Absorb07.NS_Heitao_Skill02On_Absorb07",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill01_End.NS_Heitao_Skill01_End",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_SwordWave.NS_Heitao_SwordWave",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Replication03.NS_Heitao_Replication03",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02Off_Wave.NS_Heitao_Skill02Off_Wave",
  "/Game/Asset/Effect/Common/NPC/NDC_Heitao_Hit.NDC_Heitao_Hit",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Buff_Body_Spine.NS_Heitao_Buff_Body_Spine",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill2_Hit.NS_Heitao_Skill2_Hit",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill01.NS_Heitao_Skill01",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02Off.NS_Heitao_Skill02Off",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Body.NS_Heitao_Skill02On_Body",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Absorb03.NS_Heitao_Skill02On_Absorb03",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Knife001.NS_Heitao_Knife001",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Condemned_Absorb.NS_Heitao_Condemned_Absorb",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Replication.NS_Heitao_Replication",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Back.NS_Heitao_Skill02On_Back",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill02On_Absorb04.NS_Heitao_Skill02On_Absorb04",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Replication04.NS_Heitao_Replication04",
  "/Game/Asset/Effect/Niagara/Player/Heitao/NS_Heitao_Skill01_Rush_End.NS_Heitao_Skill01_Rush_End"
}
PlayerEffectsPath = {
  [2301] = T.RT_1,
  [1601] = T.RT_2,
  [3202] = T.RT_3,
  [4101] = T.RT_4,
  [4102] = T.RT_5,
  [201] = T.RT_6,
  [10] = T.RT_7,
  [205] = T.RT_8,
  [206] = T.RT_9,
  [207] = T.RT_10,
  [210] = T.RT_11,
  [211] = T.RT_12,
  [212] = T.RT_13,
  [5401] = T.RT_14,
  [5402] = T.RT_15,
  [160101] = T.RT_16,
  [120101] = T.RT_8,
  [1501] = T.RT_17,
  [1502] = T.RT_18,
  [1503] = T.RT_19,
  [1504] = T.RT_20,
  [1505] = T.RT_16,
  [103010] = T.RT_21,
  [110303] = T.RT_22,
  [110302] = T.RT_22,
  [3301] = T.RT_23,
  [110301] = T.RT_22,
  [5301] = T.RT_24,
  [3103] = T.RT_25,
  [4201] = T.RT_26,
  [4202] = T.RT_27,
  [3201] = T.RT_28,
  [4301] = T.RT_29,
  [5101] = T.RT_30,
  [5102] = T.RT_31,
  [111] = T.RT_8,
  [112] = T.RT_9,
  [113] = T.RT_32,
  [114] = T.RT_32,
  [3102] = T.RT_33,
  [3101] = T.RT_34,
  [2101] = T.RT_35,
  [2102] = T.RT_36,
  [2401] = T.RT_37,
  [1102] = T.RT_16,
  [1801] = T.RT_38,
  [1202] = T.RT_39,
  [1201] = T.RT_40,
  [1103] = T.RT_41,
  [1101] = T.RT_42,
  [202] = T.RT_15
}
return PlayerEffectsPath
