return {
  storyName = "Home",
  storyDescription = "",
  lineData = {
    {
      startStory = "173684738567125566343",
      startPort = "StoryStart",
      endStory = "173684738867425566483",
      endPort = "In"
    },
    {
      startStory = "173684738867425566483",
      startPort = "Success",
      endStory = "173684738567125566346",
      endPort = "StoryEnd"
    }
  },
  storyNodeData = {
    ["173684738567125566343"] = {
      isStoryNode = true,
      key = "173684738567125566343",
      type = "StoryStartNode",
      name = "StoryStart",
      pos = {x = 965, y = 270},
      propsData = {QuestChainId = 0},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["173684738567125566346"] = {
      isStoryNode = true,
      key = "173684738567125566346",
      type = "StoryEndNode",
      name = "StoryEnd",
      pos = {x = 1506, y = 284},
      propsData = {},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["173684738867425566483"] = {
      isStoryNode = true,
      key = "173684738867425566483",
      type = "StoryNode",
      name = "任务节点",
      pos = {x = 1248, y = 260.42105263157896},
      propsData = {
        QuestId = 0,
        QuestDescriptionComment = "",
        QuestDescription = "",
        QuestDeatil = "",
        TaskRegionReName = "",
        TaskSubRegionReName = "",
        RecommendLevel = -1,
        bIsStartQuest = false,
        bIsEndQuest = false,
        bIsNotifyGameMode = true,
        bIsStartChapter = false,
        bIsEndChapter = false,
        bIsShowOnComplete = true,
        bIsPlayBlackScreenOnComplete = false,
        bIsPlayBlackScreenOnFail = false,
        bIsDynamicEvent = false,
        ResurgencePoint = "",
        bUseQuestCoordinate = false,
        bDeadTriggerQuestFail = false,
        IsFairyLand = false,
        SubRegionId = 0,
        SubRegionIdList = {},
        StoryGuideType = "Point",
        StoryGuidePointName = "",
        JumpId = 0
      },
      questNodeData = {
        lineData = {
          {
            startQuest = "173684738867425566484",
            startPort = "QuestStart",
            endQuest = "173684758142426278198",
            endPort = "In"
          },
          {
            startQuest = "173684758142426278198",
            startPort = "Branch_1",
            endQuest = "173684739801725566903",
            endPort = "In"
          },
          {
            startQuest = "173684758142426278198",
            startPort = "Branch_2",
            endQuest = "173684788678026278534",
            endPort = "In"
          },
          {
            startQuest = "173684758142426278198",
            startPort = "Branch_3",
            endQuest = "173684788655826278527",
            endPort = "In"
          },
          {
            startQuest = "173684739801725566903",
            startPort = "Out",
            endQuest = "173684738867425566487",
            endPort = "Success"
          },
          {
            startQuest = "173684788678026278534",
            startPort = "Out",
            endQuest = "173684738867425566487",
            endPort = "Success"
          },
          {
            startQuest = "173684788655826278527",
            startPort = "Out",
            endQuest = "173684738867425566487",
            endPort = "Success"
          },
          {
            startQuest = "173684758142426278198",
            startPort = "Branch_4",
            endQuest = "17369381345893896",
            endPort = "In"
          },
          {
            startQuest = "17369381345893896",
            startPort = "Out",
            endQuest = "173684738867425566487",
            endPort = "Success"
          },
          {
            startQuest = "173684758142426278198",
            startPort = "Branch_5",
            endQuest = "1737189644604628",
            endPort = "In"
          },
          {
            startQuest = "1737189644604628",
            startPort = "Out",
            endQuest = "173684738867425566487",
            endPort = "Success"
          },
          {
            startQuest = "173684758142426278198",
            startPort = "Branch_6",
            endQuest = "17373688963473293",
            endPort = "In"
          },
          {
            startQuest = "173684758142426278198",
            startPort = "Branch_7",
            endQuest = "17373689153333588",
            endPort = "In"
          },
          {
            startQuest = "17373688963473293",
            startPort = "Out",
            endQuest = "173684738867425566487",
            endPort = "Success"
          },
          {
            startQuest = "17373689153333588",
            startPort = "Out",
            endQuest = "173684738867425566487",
            endPort = "Success"
          },
          {
            startQuest = "173684758142426278198",
            startPort = "Branch_8",
            endQuest = "17543752616331599",
            endPort = "In"
          },
          {
            startQuest = "17543752616331599",
            startPort = "Out",
            endQuest = "173684738867425566487",
            endPort = "Success"
          }
        },
        nodeData = {
          ["173684738867425566484"] = {
            key = "173684738867425566484",
            type = "QuestStartNode",
            name = "QuestStart",
            pos = {x = 79.42857142857143, y = 260.2857142857143},
            propsData = {ModeType = 0}
          },
          ["173684738867425566487"] = {
            key = "173684738867425566487",
            type = "QuestSuccessNode",
            name = "QuestSuccess",
            pos = {x = 1396, y = 220},
            propsData = {ModeType = 0}
          },
          ["173684738867425566490"] = {
            key = "173684738867425566490",
            type = "QuestFailNode",
            name = "QuestFail",
            pos = {x = 1744, y = 528},
            propsData = {}
          },
          ["173684739801725566903"] = {
            key = "173684739801725566903",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 816, y = 114},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70016101,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "FIXsimple_OB_Tuiche",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["173684758142426278198"] = {
            key = "173684758142426278198",
            type = "BranchTriggerNode",
            name = "触发分支节点",
            pos = {x = 402.1867007672634, y = 246},
            propsData = {
              Branches = {
                700172,
                700173,
                700174,
                700175,
                700176,
                700177,
                700178,
                700180
              }
            }
          },
          ["173684788655826278527"] = {
            key = "173684788655826278527",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 828, y = 472},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70016105,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "FIXsimple_OB_Tuiche",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["173684788678026278534"] = {
            key = "173684788678026278534",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 828, y = 278.75},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70016104,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "FIXsimple_OB_Tuiche",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17369381345893896"] = {
            key = "17369381345893896",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 837, y = 632.3333333333334},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11019044,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Fixsimple_jail_ob",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1737189644604628"] = {
            key = "1737189644604628",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 850.4022988505747, y = 824.1456582633053},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70016107,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Fix_ob_SX",
              BlendInTime = 1,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17373688963473293"] = {
            key = "17373688963473293",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 842.0322128851543, y = 1032.1792717086837},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11018101,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17373689153333588"] = {
            key = "17373689153333588",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 844.3851540616249, y = 1185.0764995653435},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70016109,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17543752616331599"] = {
            key = "17543752616331599",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 830.3550093646311, y = 1400.1840521372274},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70016110,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Fix_ob_SX",
              BlendInTime = 1,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {},
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          }
        },
        commentData = {}
      }
    }
  },
  commentData = {}
}
