return {
  storyName = "Home",
  storyDescription = "",
  lineData = {
    {
      startStory = "17815144863741",
      startPort = "StoryStart",
      endStory = "1781514499325100",
      endPort = "In"
    },
    {
      startStory = "1781514499325100",
      startPort = "Success",
      endStory = "17815144863745",
      endPort = "StoryEnd"
    }
  },
  storyNodeData = {
    ["17815144863741"] = {
      isStoryNode = true,
      key = "17815144863741",
      type = "StoryStartNode",
      name = "StoryStart",
      pos = {x = 800, y = 300},
      propsData = {QuestChainId = 0},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["17815144863745"] = {
      isStoryNode = true,
      key = "17815144863745",
      type = "StoryEndNode",
      name = "StoryEnd",
      pos = {x = 2800, y = 300},
      propsData = {},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["1781514499325100"] = {
      isStoryNode = true,
      key = "1781514499325100",
      type = "StoryNode",
      name = "任务节点",
      pos = {x = 1574, y = 408},
      propsData = {
        QuestId = 0,
        QuestDescriptionComment = "",
        QuestDescription = "",
        QuestDeatil = "",
        TaskRegionReName = "",
        TaskSubRegionReName = "",
        RecommendLevel = -1,
        bIsStartQuest = false,
        bIsEndQuest = false,
        bIsNotifyGameMode = true,
        bIsStartChapter = false,
        bIsEndChapter = false,
        bIsPlayBlackScreenOnComplete = false,
        bIsPlayBlackScreenOnFail = false,
        bIsDynamicEvent = false,
        ResurgencePoint = "",
        bUseQuestCoordinate = false,
        bDeadTriggerQuestFail = false,
        IsFairyLand = false,
        SubRegionId = 0,
        SubRegionIdList = {},
        StoryGuideType = "Point",
        StoryGuidePointName = "",
        JumpId = 0,
        IsBacktrack = false
      },
      questNodeData = {
        lineData = {
          {
            startQuest = "1781514525613554",
            startPort = "Branch_1",
            endQuest = "1781515610204920",
            endPort = "In"
          },
          {
            startQuest = "1781514499325101",
            startPort = "QuestStart",
            endQuest = "1781514525613554",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_2",
            endQuest = "17815189608932099883",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_3",
            endQuest = "17815192627912100874",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_4",
            endQuest = "17815193862102102236",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_5",
            endQuest = "17815204620242103629",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_6",
            endQuest = "17815205614493153102",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_7",
            endQuest = "17815206015804201994",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_8",
            endQuest = "17815216184566303735",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_9",
            endQuest = "17815218365926304584",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_10",
            endQuest = "17815228685896305739",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_11",
            endQuest = "17815229494046306280",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_12",
            endQuest = "17815234941056309180",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_13",
            endQuest = "17815236454166309657",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_14",
            endQuest = "17815240450506311713",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_15",
            endQuest = "17815242304376312093",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_16",
            endQuest = "17815250193956313059",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_17",
            endQuest = "17815250582386313379",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_18",
            endQuest = "17815238257516311145",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_19",
            endQuest = "17815254311346315893",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_20",
            endQuest = "17815255152866316280",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_21",
            endQuest = "17815255910106316621",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_22",
            endQuest = "17815256195136316840",
            endPort = "In"
          },
          {
            startQuest = "1781514525613554",
            startPort = "Branch_23",
            endQuest = "17815256467206317201",
            endPort = "In"
          },
          {
            startQuest = "1781515610204920",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815189608932099883",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815192627912100874",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815193862102102236",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815204620242103629",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815205614493153102",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815206015804201994",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815216184566303735",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815218365926304584",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815228685896305739",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815229494046306280",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815234941056309180",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815236454166309657",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815240450506311713",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815242304376312093",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815250193956313059",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815250582386313379",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815238257516311145",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815254311346315893",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815255152866316280",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815255910106316621",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815256195136316840",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          },
          {
            startQuest = "17815256467206317201",
            startPort = "Out",
            endQuest = "1781514499326109",
            endPort = "Success"
          }
        },
        nodeData = {
          ["1781514499325101"] = {
            key = "1781514499325101",
            type = "QuestStartNode",
            name = "QuestStart",
            pos = {x = 800, y = 300},
            propsData = {ModeType = 0}
          },
          ["1781514499326109"] = {
            key = "1781514499326109",
            type = "QuestSuccessNode",
            name = "QuestSuccess",
            pos = {x = 3891.2610900929253, y = 501.7522388834094},
            propsData = {ModeType = 0}
          },
          ["1781514499326117"] = {
            key = "1781514499326117",
            type = "QuestFailNode",
            name = "QuestFail",
            pos = {x = 4344.005544241506, y = 671.5397548314902},
            propsData = {}
          },
          ["1781514525613554"] = {
            key = "1781514525613554",
            type = "BranchTriggerNode",
            name = "触发分支节点",
            pos = {x = 1183.9134308503246, y = 301.58730821456504},
            propsData = {
              Branches = {
                7001761,
                7001771,
                7001781,
                7001791,
                7001801,
                7001811,
                7001821,
                7001831,
                7001841,
                7001851,
                7001861,
                7001871,
                7001881,
                7001891,
                7001901,
                7001911,
                7001921,
                7001931,
                7001941,
                7001951,
                7001961,
                7001971,
                7001981
              }
            }
          },
          ["1781515610204920"] = {
            key = "1781515610204920",
            type = "TalkNode",
            name = "7001761-流程-游乐园废墟",
            pos = {x = 1591.0157568251022, y = 249.53395819236994},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11121801,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815189608932099883"] = {
            key = "17815189608932099883",
            type = "TalkNode",
            name = "7001771-流程-潜行",
            pos = {x = 1593.9785039903381, y = 440.8645799965212},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11122001,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815192627912100874"] = {
            key = "17815192627912100874",
            type = "TalkNode",
            name = "7001781-流程-休整点",
            pos = {x = 1593.9785039903386, y = 633.4177657554906},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11122101,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815193862102102236"] = {
            key = "17815193862102102236",
            type = "TalkNode",
            name = "7001791-流程-仓库",
            pos = {x = 1601.4253122793596, y = 816.39648371429},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11122301,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815204620242103629"] = {
            key = "17815204620242103629",
            type = "TalkNode",
            name = "7001801-流程-主角家衣柜",
            pos = {x = 1933.3401960185777, y = 240.86458594853093},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11111101,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815205614493153102"] = {
            key = "17815205614493153102",
            type = "TalkNode",
            name = "7001811-流程-主角家照片",
            pos = {x = 1931.2125365074287, y = 439.8007502409468},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11111102,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815206015804201994"] = {
            key = "17815206015804201994",
            type = "TalkNode",
            name = "7001821-流程-主角家书桌",
            pos = {x = 1922.701898462833, y = 618.5241491774486},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11111103,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815216184566303735"] = {
            key = "17815216184566303735",
            type = "TalkNode",
            name = "7001831-流程-战死者飞艇攻击",
            pos = {x = 2266.8826199646696, y = 268.2340230297114},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11111701,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815218365926304584"] = {
            key = "17815218365926304584",
            type = "TalkNode",
            name = "7001841-流程-战死者飞艇空降背包",
            pos = {x = 2268.4295198344616, y = 458.5681869813592},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11111702,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815228685896305739"] = {
            key = "17815228685896305739",
            type = "TalkNode",
            name = "7001851-流程-战死者飞艇通道",
            pos = {x = 2282.9982840931784, y = 616.3770408854108},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11111801,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815229494046306280"] = {
            key = "17815229494046306280",
            type = "TalkNode",
            name = "7001861-流程-战死者军团弹壳",
            pos = {x = 2583.7999180493293, y = 273.9528022569138},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11112001,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815234941056309180"] = {
            key = "17815234941056309180",
            type = "TalkNode",
            name = "7001871-流程-战死者武器",
            pos = {x = 2602.220139714368, y = 453.4823986549094},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11112201,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815236454166309657"] = {
            key = "17815236454166309657",
            type = "TalkNode",
            name = "7001881-流程-战死者墓碑",
            pos = {x = 2595.85004616994, y = 646.8663966084553},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11112701,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815238257516311145"] = {
            key = "17815238257516311145",
            type = "TalkNode",
            name = "7001931-流程-净化室笼子",
            pos = {x = 3374.718955860182, y = 263.9862434481917},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11115901,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815240450506311713"] = {
            key = "17815240450506311713",
            type = "TalkNode",
            name = "7001891-流程-复仇者榴弹",
            pos = {x = 2967.4674675920432, y = 287.2136480129866},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11122501,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815242304376312093"] = {
            key = "17815242304376312093",
            type = "TalkNode",
            name = "7001901-流程-复仇者武器碎片",
            pos = {x = 2995.516247383929, y = 460.3843754237579},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11122601,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815250193956313059"] = {
            key = "17815250193956313059",
            type = "TalkNode",
            name = "7001911-流程-闪光手雷",
            pos = {x = 2983.3211257352827, y = 644.5307123183106},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11122701,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815250582386313379"] = {
            key = "17815250582386313379",
            type = "TalkNode",
            name = "7001921-流程-急救箱",
            pos = {x = 2961.3699067677203, y = 821.3599762236759},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11122801,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815254311346315893"] = {
            key = "17815254311346315893",
            type = "TalkNode",
            name = "7001941-流程-墓地维克托棺材",
            pos = {x = 3367.863536191621, y = 489.98998855563553},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11117001,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815255152866316280"] = {
            key = "17815255152866316280",
            type = "TalkNode",
            name = "7001951-流程-墓地伯纳德棺材",
            pos = {x = 3379.56566347128, y = 668.7133870086087},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11122802,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815255910106316621"] = {
            key = "17815255910106316621",
            type = "TalkNode",
            name = "7001961-流程-墓地加斯图斯棺材",
            pos = {x = 3379.56566347128, y = 851.692104472367},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11122803,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815256195136316840"] = {
            key = "17815256195136316840",
            type = "TalkNode",
            name = "7001971-流程-墓地莫甘娜棺材",
            pos = {x = 3374.2465147077983, y = 1020.8410351510736},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11122804,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17815256467206317201"] = {
            key = "17815256467206317201",
            type = "TalkNode",
            name = "7001981-流程-墓地特蕾莎棺材",
            pos = {x = 3375.310344460495, y = 1205.9474121202243},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 11122805,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = false,
              ShowSkipButton = true,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              CloseMotionBlur = false,
              PauseTimeElapse = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              bLockNpcSpawn = false,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              bLockHighestLOD = false,
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = false,
              bNpcActionKeepOut = false,
              bForceWaitNavLoaded = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          }
        },
        commentData = {}
      }
    }
  },
  commentData = {}
}
