return {
  storyName = "Home",
  storyDescription = "",
  lineData = {
    {
      startStory = "1704175979455219186",
      startPort = "StoryStart",
      endStory = "1704175979455219188",
      endPort = "In"
    },
    {
      startStory = "1704175979455219188",
      startPort = "Success",
      endStory = "1704175979455219187",
      endPort = "StoryEnd"
    }
  },
  storyNodeData = {
    ["1704175979455219186"] = {
      isStoryNode = true,
      key = "1704175979455219186",
      type = "StoryStartNode",
      name = "StoryStart",
      pos = {x = 800, y = 300},
      propsData = {QuestChainId = 0},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["1704175979455219187"] = {
      isStoryNode = true,
      key = "1704175979455219187",
      type = "StoryEndNode",
      name = "StoryEnd",
      pos = {x = 1628, y = 352},
      propsData = {},
      questNodeData = {
        lineData = {},
        nodeData = {},
        commentData = {}
      }
    },
    ["1704175979455219188"] = {
      isStoryNode = true,
      key = "1704175979455219188",
      type = "StoryNode",
      name = "任务节点",
      pos = {x = 1249.3636363636363, y = 346.5},
      propsData = {
        QuestId = 0,
        QuestDescriptionComment = "",
        QuestDescription = "",
        QuestDeatil = "",
        TaskRegionReName = "",
        TaskSubRegionReName = "",
        RecommendLevel = -1,
        bIsStartQuest = false,
        bIsEndQuest = false,
        bIsNotifyGameMode = false,
        bIsStartChapter = false,
        bIsEndChapter = false,
        bIsShowOnComplete = true,
        bIsPlayBlackScreenOnComplete = false,
        bIsPlayBlackScreenOnFail = false,
        bIsDynamicEvent = false,
        ResurgencePoint = "",
        bUseQuestCoordinate = false,
        bDeadTriggerQuestFail = false,
        IsFairyLand = false,
        SubRegionId = 0,
        SubRegionIdList = {},
        StoryGuideType = "Point",
        StoryGuidePointName = "",
        JumpId = 0
      },
      questNodeData = {
        lineData = {
          {
            startQuest = "1704175979455219189",
            startPort = "QuestStart",
            endQuest = "1704175979455219193",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_1",
            endQuest = "1704175979455219192",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219192",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_2",
            endQuest = "1704175979455219194",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219194",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_3",
            endQuest = "1704175979455219201",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_4",
            endQuest = "1704175979455219200",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_5",
            endQuest = "1704175979455219199",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_6",
            endQuest = "1704175979455219198",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_7",
            endQuest = "1704175979455219197",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_8",
            endQuest = "1704175979455219196",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_9",
            endQuest = "1704175979455219195",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219201",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219200",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219199",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219198",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219197",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219196",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219195",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_10",
            endQuest = "1704175979455219202",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_11",
            endQuest = "1704175979455219203",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_12",
            endQuest = "1704175979455219204",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_13",
            endQuest = "1704175979455219205",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_14",
            endQuest = "1704175979455219206",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_15",
            endQuest = "1704175979455219207",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_16",
            endQuest = "1704175979455219208",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_17",
            endQuest = "1704175979455219209",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_18",
            endQuest = "1704175979455219210",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_19",
            endQuest = "1704175979455219211",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_20",
            endQuest = "1704175979455219212",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219202",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219203",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219204",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219205",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219206",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219207",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219208",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219209",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219210",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219211",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219212",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_21",
            endQuest = "17129843082235147",
            endPort = "In"
          },
          {
            startQuest = "17129843082235147",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_23",
            endQuest = "1722254726660642415",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_22",
            endQuest = "1722254702094641871",
            endPort = "In"
          },
          {
            startQuest = "1722254702094641871",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1722254726660642415",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_24",
            endQuest = "17225029985382094313",
            endPort = "In"
          },
          {
            startQuest = "17225029985382094313",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_25",
            endQuest = "17234509240164952",
            endPort = "In"
          },
          {
            startQuest = "17234509240164952",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_27",
            endQuest = "17234626099686766",
            endPort = "In"
          },
          {
            startQuest = "17234626099686766",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_26",
            endQuest = "17234625758366435",
            endPort = "In"
          },
          {
            startQuest = "17234625758366435",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_28",
            endQuest = "17314158718306368",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_29",
            endQuest = "17314158724016422",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_30",
            endQuest = "17314158736686489",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_31",
            endQuest = "17314158744976543",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_32",
            endQuest = "17314158750836589",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_33",
            endQuest = "17314158757496644",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_34",
            endQuest = "17314158764936692",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_35",
            endQuest = "17314159105227967",
            endPort = "In"
          },
          {
            startQuest = "17314158718306368",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "17314158724016422",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "17314158736686489",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "17314158744976543",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "17314158750836589",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "17314158757496644",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "17314158764936692",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "17314159105227967",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_36",
            endQuest = "17356272081113354",
            endPort = "In"
          },
          {
            startQuest = "17356272081113354",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_37",
            endQuest = "17368228387664070",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_38",
            endQuest = "17368228387664071",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_39",
            endQuest = "17368228387664072",
            endPort = "In"
          },
          {
            startQuest = "17368228387664070",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "17368228387664071",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "17368228387664072",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_40",
            endQuest = "17395312773002752",
            endPort = "In"
          },
          {
            startQuest = "17395312773002752",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_41",
            endQuest = "17428073952052318",
            endPort = "In"
          },
          {
            startQuest = "1704175979455219193",
            startPort = "Branch_42",
            endQuest = "17428074018192401",
            endPort = "In"
          },
          {
            startQuest = "17428073952052318",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          },
          {
            startQuest = "17428074018192401",
            startPort = "Out",
            endQuest = "1704175979455219190",
            endPort = "Success"
          }
        },
        nodeData = {
          ["1704175979455219189"] = {
            key = "1704175979455219189",
            type = "QuestStartNode",
            name = "QuestStart",
            pos = {x = 412.1517595307918, y = 584.8973607038123},
            propsData = {ModeType = 0}
          },
          ["1704175979455219190"] = {
            key = "1704175979455219190",
            type = "QuestSuccessNode",
            name = "QuestSuccess",
            pos = {x = 2577.5, y = 457.08333333333337},
            propsData = {ModeType = 0}
          },
          ["1704175979455219191"] = {
            key = "1704175979455219191",
            type = "QuestFailNode",
            name = "QuestFail",
            pos = {x = 2603.8333333333335, y = 1322.5},
            propsData = {}
          },
          ["1704175979455219192"] = {
            key = "1704175979455219192",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1461.4672459893047, y = 274.9478609625669},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70013101,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700131",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219193"] = {
            key = "1704175979455219193",
            type = "BranchTriggerNode",
            name = "触发分支节点",
            pos = {x = 694.3727598566309, y = 297.4802867383512},
            propsData = {
              Branches = {
                700131,
                700132,
                700133,
                700134,
                700135,
                700136,
                700137,
                700138,
                700139,
                700140,
                700141,
                700142,
                700143,
                700144,
                700145,
                700146,
                700147,
                700148,
                700149,
                700150,
                700151,
                700152,
                700153,
                700154,
                700155,
                700156,
                700157,
                700160,
                700161,
                700162,
                700163,
                700164,
                700165,
                700166,
                700167,
                700168,
                700169,
                700170,
                700171,
                700179,
                700200,
                700300
              }
            }
          },
          ["1704175979455219194"] = {
            key = "1704175979455219194",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1746.497549019608, y = 278.4705882352939},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70013201,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700132",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219195"] = {
            key = "1704175979455219195",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2030.8787878787878, y = 627.6740196078433},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70013901,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700139",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219196"] = {
            key = "1704175979455219196",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1747.9166666666667, y = 626.8250891265599},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70013801,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700138",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219197"] = {
            key = "1704175979455219197",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1466.1243872549019, y = 618.8014705882355},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70013701,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700137",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219198"] = {
            key = "1704175979455219198",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2016.5259024064171, y = 451.5193850267382},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70013601,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700136",
              BlendInTime = 1.2,
              BlendOutTime = 0.8,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219199"] = {
            key = "1704175979455219199",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1749.7910539215686, y = 454.97794117647084},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70013501,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700135",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219200"] = {
            key = "1704175979455219200",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1460.3731617647059, y = 436.45133053221286},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70013401,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700134",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219201"] = {
            key = "1704175979455219201",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2022.454044117647, y = 280.3385854341734},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70013301,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700133",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219202"] = {
            key = "1704175979455219202",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1456.5191387559807, y = 773.5574162679427},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70014001,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700140",
              BlendInTime = 1,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219203"] = {
            key = "1704175979455219203",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1746.8967611336034, y = 771.5566170671434},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70014101,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700141",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219204"] = {
            key = "1704175979455219204",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2026.3824754193176, y = 770.7851884957148},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70014201,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700142",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219205"] = {
            key = "1704175979455219205",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1463.693664230506, y = 933.521302381829},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70014301,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700143",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219206"] = {
            key = "1704175979455219206",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1751.2141437509858, y = 932.7705031810297},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70014401,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700144",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219207"] = {
            key = "1704175979455219207",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2032.6998580367, y = 931.9490746096011},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70014501,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700145",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219208"] = {
            key = "1704175979455219208",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1460.877830064672, y = 1106.164359324886},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70014601,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700146",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219209"] = {
            key = "1704175979455219209",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1749.2554524422947, y = 1104.1635601240866},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70014701,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700147",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219210"] = {
            key = "1704175979455219210",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2030.741166728009, y = 1104.592131552658},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70014801,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700148",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219211"] = {
            key = "1704175979455219211",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1467.1952126820545, y = 1267.3782454387722},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70014901,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700149",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "FadeIn",
              OutType = "FadeOut",
              ShowFadeDetail = false,
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1704175979455219212"] = {
            key = "1704175979455219212",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1754.1442636311058, y = 1265.3060176665442},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70015001,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700150",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17129843082235147"] = {
            key = "17129843082235147",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2032.285714285715, y = 1265.4285714285713},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70015101,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_700151",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1722254702094641871"] = {
            key = "1722254702094641871",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1464.5083387563375, y = 1422.6929900340763},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 70015201,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["1722254726660642415"] = {
            key = "1722254726660642415",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1768.4159922139904, y = 1420.358435699522},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 70015301,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0.5,
              BlendOutTime = 0.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = false,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17225029985382094313"] = {
            key = "17225029985382094313",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2033.131400268428, y = 1418.0372009771093},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70015401,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 1,
              BlendOutTime = 1,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17234509240164952"] = {
            key = "17234509240164952",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1464.8527539267373, y = 1560.5455796353629},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70015501,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_OldPhoto",
              BlendInTime = 2,
              BlendOutTime = 1.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17234625758366435"] = {
            key = "17234625758366435",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1759.1399085950168, y = 1564.4344685242518},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70015601,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_EnlikeSecret",
              BlendInTime = 3,
              BlendOutTime = 1.5,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17234626099686766"] = {
            key = "17234626099686766",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2038.262715612561, y = 1562.7678018575853},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70015701,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "Stage_101167",
              BlendInTime = 4,
              BlendOutTime = 3,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17314158718306368"] = {
            key = "17314158718306368",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1436.8331864513639, y = 2082.964929476607},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 70016001,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17314158724016422"] = {
            key = "17314158724016422",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1746.6368330151784, y = 2079.6830220432266},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 70016002,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17314158736686489"] = {
            key = "17314158736686489",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2028.5863421315878, y = 2081.6185059141944},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 70016003,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17314158744976543"] = {
            key = "17314158744976543",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1434.9397783167212, y = 2251.3520262508005},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70016004,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17314158750836589"] = {
            key = "17314158750836589",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1744.7013491442108, y = 2252.698449813212},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 70016005,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17314158757496644"] = {
            key = "17314158757496644",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2038.3479129590776, y = 2251.7735217848667},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70016006,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "cp2spstage02",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17314158764936692"] = {
            key = "17314158764936692",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1434.350718008166, y = 2440.65076397871},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70016007,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "cp2spstage01",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17314159105227967"] = {
            key = "17314159105227967",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1741.5035931834814, y = 2443.259459630884},
            propsData = {
              IsNpcNode = false,
              FirstDialogueId = 70016008,
              FlowAssetPath = "",
              TalkType = "NoIntFixSimple",
              TalkStageName = "",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              bNpcActionKeepIn = true,
              bNpcActionKeepOut = false,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17356272081113354"] = {
            key = "17356272081113354",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2032, y = 2436},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 70016009,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17368228387664070"] = {
            key = "17368228387664070",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1433.7635942982006, y = 2653.021034163268},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 70016010,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17368228387664071"] = {
            key = "17368228387664071",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1742.3282341793984, y = 2655.629729815442},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 70016011,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17368228387664072"] = {
            key = "17368228387664072",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2032.824640995917, y = 2648.3702701845577},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 70016012,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17395312773002752"] = {
            key = "17395312773002752",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1424, y = 2830.5},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 70016013,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17428073952052318"] = {
            key = "17428073952052318",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 1740.952380952381, y = 2831.3333333333335},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 7002001,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          },
          ["17428074018192401"] = {
            key = "17428074018192401",
            type = "TalkNode",
            name = "对话节点",
            pos = {x = 2044.9523809523807, y = 2829.3333333333335},
            propsData = {
              IsNpcNode = false,
              IsPlayerTurnToNPC = true,
              IsNPCTurnToPlayer = true,
              FirstDialogueId = 7003001,
              FlowAssetPath = "",
              TalkType = "FreeSimple",
              BlendInTime = 0,
              BlendOutTime = 0,
              InType = "BlendIn",
              OutType = "BlendOut",
              BlendEaseExp = 2,
              UseProceduralCamera = true,
              ProceduralCameraId = 1,
              HideNpcs = false,
              HideMonsters = true,
              HideAllBattleEntity = true,
              HideMechanismsFX = true,
              ShowSkipButton = false,
              ShowAutoPlayButton = true,
              ShowReviewButton = true,
              ShowWikiButton = true,
              SkipToOption = false,
              DisableNpcOptimization = false,
              DoNotReceiveCharacterShadow = false,
              BeginNewTargetPointName = "",
              EndNewTargetPointName = "",
              CameraLookAtTartgetPoint = "",
              RestoreStand = false,
              PauseNpcBT = true,
              TalkActors = {
                {
                  TalkActorType = "Player",
                  TalkActorId = 0,
                  TalkActorVisible = true
                }
              },
              OptionType = "normal",
              FreezeWorldComposition = false,
              bTravelFullLoadWorldComposition = false,
              SwitchToMaster = "None",
              PlayerSwitchEmoIdle = true,
              NormalOptions = {},
              OverrideFailBlend = false
            }
          }
        },
        commentData = {
          ["173141604891711302"] = {
            key = "173141604891711302",
            name = "别删",
            position = {x = 1374.967828807605, y = 1993.3856868398602},
            size = {width = 933.032171192395, height = 912.6143131601398}
          }
        }
      }
    }
  },
  commentData = {}
}
